UPDATE core_nga SET world_region = 'Europe' WHERE name = 'Latium';
UPDATE core_nga SET world_region = 'Europe' WHERE name = 'Paris Basin';
UPDATE core_nga SET world_region = 'Europe' WHERE name = 'Iceland';
UPDATE core_nga SET world_region = 'Europe' WHERE name = 'Crete';
UPDATE core_nga SET world_region = 'Africa' WHERE name = 'Upper Egypt';
UPDATE core_nga SET world_region = 'Africa' WHERE name = 'Niger Inland Delta';
UPDATE core_nga SET world_region = 'Africa' WHERE name = 'Ghanaian Coast';
UPDATE core_nga SET world_region = 'Southwest Asia' WHERE name = 'Southern Mesopotamia';
UPDATE core_nga SET world_region = 'Southwest Asia' WHERE name = 'Susiana';
UPDATE core_nga SET world_region = 'Southwest Asia' WHERE name = 'Galilee';
UPDATE core_nga SET world_region = 'Southwest Asia' WHERE name = 'Konya Plain';
UPDATE core_nga SET world_region = 'Southwest Asia' WHERE name = 'Yemeni Coastal Plain';
UPDATE core_nga SET world_region = 'Central Eurasia' WHERE name = 'Sogdiana';
UPDATE core_nga SET world_region = 'Central Eurasia' WHERE name = 'Orkhon Valley';
UPDATE core_nga SET world_region = 'Central Eurasia' WHERE name = 'Lena River Valley';
UPDATE core_nga SET world_region = 'South Asia' WHERE name = 'Kachi Plain';
UPDATE core_nga SET world_region = 'South Asia' WHERE name = 'Middle Ganga';
UPDATE core_nga SET world_region = 'South Asia' WHERE name = 'Deccan';
UPDATE core_nga SET world_region = 'South Asia' WHERE name = 'Garo Hills';
UPDATE core_nga SET world_region = 'Southeast Asia' WHERE name = 'Cambodian Basin';
UPDATE core_nga SET world_region = 'Southeast Asia' WHERE name = 'Central Java';
UPDATE core_nga SET world_region = 'Southeast Asia' WHERE name = 'Kapuasi Basin';
UPDATE core_nga SET world_region = 'East Asia' WHERE name = 'Middle Yellow River Valley';
UPDATE core_nga SET world_region = 'East Asia' WHERE name = 'Kansai';
UPDATE core_nga SET world_region = 'East Asia' WHERE name = 'Southern China Hills';
UPDATE core_nga SET world_region = 'Oceania-Australia' WHERE name = 'Big Island Hawaii';
UPDATE core_nga SET world_region = 'Oceania-Australia' WHERE name = 'Oro PNG';
UPDATE core_nga SET world_region = 'Oceania-Australia' WHERE name = 'Chuuk Islands';
UPDATE core_nga SET world_region = 'North America' WHERE name = 'Valley of Oaxaca';
UPDATE core_nga SET world_region = 'North America' WHERE name = 'Basin of Mexico';
UPDATE core_nga SET world_region = 'North America' WHERE name = 'Cahokia';
UPDATE core_nga SET world_region = 'North America' WHERE name = 'Finger Lakes';
UPDATE core_nga SET world_region = 'South America' WHERE name = 'Cuzco';
UPDATE core_nga SET world_region = 'South America' WHERE name = 'North Colombia';
UPDATE core_nga SET world_region = 'South America' WHERE name = 'Lowland Andes';