INSERT INTO core_nga (id, name, subregion, nga_code, longitude, latitude, capital_city, fao_country) VALUES (1, 'Latium', 'Italy', 'IT', 12.486948, 41.890407, 'Rome', 'Italy');
INSERT INTO core_nga (id, name, subregion, nga_code, longitude, latitude, capital_city, fao_country) VALUES (2, 'Paris Basin', 'France', 'FR', 2.312458, 48.866111, 'Paris', 'France');
INSERT INTO core_nga (id, name, subregion, nga_code, longitude, latitude, capital_city, fao_country) VALUES (3, 'Iceland', 'Iceland', 'IS', -21.891497, 64.133088, 'Reykjavik', 'Iceland');
INSERT INTO core_nga (id, name, subregion, nga_code, longitude, latitude, capital_city, fao_country) VALUES (4, 'Crete', 'Greece', 'GR', 25.1442, 35.3387, 'Heraklion', 'Greece');
INSERT INTO core_nga (id, name, subregion, nga_code, longitude, latitude, capital_city, fao_country) VALUES (5, 'Upper Egypt', 'Egypt', 'EG', 32.714706, 25.725715, 'Luxor', 'Egypt');
INSERT INTO core_nga (id, name, subregion, nga_code, longitude, latitude, capital_city, fao_country) VALUES (6, 'Niger Inland Delta', 'Mali', 'ML', -3.041703, 16.717549, 'Timbuctu', 'Mali');
INSERT INTO core_nga (id, name, subregion, nga_code, longitude, latitude, capital_city, fao_country) VALUES (7, 'Ghanaian Coast', 'Ghana', 'GH', -0.21792, 5.573135, 'Accra', 'Ghana');
INSERT INTO core_nga (id, name, subregion, nga_code, longitude, latitude, capital_city, fao_country) VALUES (8, 'Southern Mesopotamia', 'Mesopotamia', 'IQ', 44.42, 32.47, 'Babylon (Hillah)', 'Iraq');
INSERT INTO core_nga (id, name, subregion, nga_code, longitude, latitude, capital_city, fao_country) VALUES (9, 'Susiana', 'Susiana', 'IR', 48.235564, 32.382851, 'Susa (Shush)', 'Iraq');
INSERT INTO core_nga (id, name, subregion, nga_code, longitude, latitude, capital_city, fao_country) VALUES (10, 'Galilee', 'Levant', 'IL', 35.3035, 32.6996, 'Nazareth', 'Israel');
INSERT INTO core_nga (id, name, subregion, nga_code, longitude, latitude, capital_city, fao_country) VALUES (11, 'Konya Plain', 'Turkey', 'TR', 32.521164, 37.877845, 'Konya', 'Turkey');
INSERT INTO core_nga (id, name, subregion, nga_code, longitude, latitude, capital_city, fao_country) VALUES (12, 'Yemeni Coastal Plain', 'Yemen', 'YE', 43.315739, 14.850891, 'Sanaa', 'Yemen');
INSERT INTO core_nga (id, name, subregion, nga_code, longitude, latitude, capital_city, fao_country) VALUES (13, 'Kachi Plain', 'Pakistan', 'PK', 67.628836, 29.377664, 'Mehrgarh', 'Pakistan');
INSERT INTO core_nga (id, name, subregion, nga_code, longitude, latitude, capital_city, fao_country) VALUES (14, 'Middle Ganga', 'Uttar Pradesh', 'UTPR', 82.7, 25.75, 'Jaunpur', 'India');
INSERT INTO core_nga (id, name, subregion, nga_code, longitude, latitude, capital_city, fao_country) VALUES (15, 'Deccan', 'Deccan', 'DEC', 76.625407, 15.386856, 'Kampli', 'India');
INSERT INTO core_nga (id, name, subregion, nga_code, longitude, latitude, capital_city, fao_country) VALUES (16, 'Garo Hills', 'Assam', 'ASM', 90.5185390109, 25.4444444439, 'Tura', 'India');
INSERT INTO core_nga (id, name, subregion, nga_code, longitude, latitude, capital_city, fao_country) VALUES (17, 'Cambodian Basin', 'Cambodia', 'KH', 103.8667, 13.4125, 'Angkor Wat', 'Cambodia');
INSERT INTO core_nga (id, name, subregion, nga_code, longitude, latitude, capital_city, fao_country) VALUES (18, 'Central Java', 'Indonesia', 'JV', 110.403498, -6.985678, 'Semarang', 'Indonesia');
INSERT INTO core_nga (id, name, subregion, nga_code, longitude, latitude, capital_city, fao_country) VALUES (19, 'Kapuasi Basin', 'Malaysia', 'KAL', 112.405971685, 0.77412081365, 'Borneo', 'Indonesia');
INSERT INTO core_nga (id, name, subregion, nga_code, longitude, latitude, capital_city, fao_country) VALUES (20, 'Middle Yellow River Valley', 'Henan', 'CN', 112.517587, 34.701825, 'Luoyang', 'China');
INSERT INTO core_nga (id, name, subregion, nga_code, longitude, latitude, capital_city, fao_country) VALUES (21, 'Kansai', 'Japan', 'JP', 135.7622, 35.02528, 'Kyoto', 'Japan');
INSERT INTO core_nga (id, name, subregion, nga_code, longitude, latitude, capital_city, fao_country) VALUES (22, 'Southern China Hills', 'Yunnan', 'YUN', 103.99173096, 27.5388341428, 'Guizhou', 'China');
INSERT INTO core_nga (id, name, subregion, nga_code, longitude, latitude, capital_city, fao_country) VALUES (23, 'Sogdiana', 'Uzbekistan', 'UZ', 66.93817, 39.631284, 'Samarkand', 'Uzbekistan');
INSERT INTO core_nga (id, name, subregion, nga_code, longitude, latitude, capital_city, fao_country) VALUES (24, 'Orkhon Valley', 'Mongolia', 'MN', 102.845486, 47.200757, 'Karakorum', 'Mongolia');
INSERT INTO core_nga (id, name, subregion, nga_code, longitude, latitude, capital_city, fao_country) VALUES (25, 'Lena River Valley', 'East Siberia', 'YAK', 129.379494854, 63.4628222423, 'Yakutsk', 'Russia');
INSERT INTO core_nga (id, name, subregion, nga_code, longitude, latitude, capital_city, fao_country) VALUES (26, 'Valley of Oaxaca', 'Oaxaca', 'OAX', -96.761022, 17.041135, 'Monte Alban', 'Mexico');
INSERT INTO core_nga (id, name, subregion, nga_code, longitude, latitude, capital_city, fao_country) VALUES (27, 'Basin of Mexico', 'Mexico', 'MX', -99.13, 19.43, 'Ciudad de Mexico', 'Mexico');
INSERT INTO core_nga (id, name, subregion, nga_code, longitude, latitude, capital_city, fao_country) VALUES (28, 'Cahokia', 'Illinois', 'USMO', -90.062035, 38.658938, 'St. Louis', 'USA');
INSERT INTO core_nga (id, name, subregion, nga_code, longitude, latitude, capital_city, fao_country) VALUES (29, 'Finger Lakes', 'New York', 'USNY', -77.021375, 42.70498, 'Seneca Falls', 'USA');
INSERT INTO core_nga (id, name, subregion, nga_code, longitude, latitude, capital_city, fao_country) VALUES (30, 'Cuzco', 'Peru', 'PE', -72.067772, -13.47738, 'Cuzco', 'Peru');
INSERT INTO core_nga (id, name, subregion, nga_code, longitude, latitude, capital_city, fao_country) VALUES (31, 'North Colombia', 'Colombia', 'CO', -73.6403880979, 10.7802871821, 'Santa Marta', 'Colombia');
INSERT INTO core_nga (id, name, subregion, nga_code, longitude, latitude, capital_city, fao_country) VALUES (32, 'Lowland Andes', 'Ecuador', 'EC', -77.6741904014, -2.89537519716, 'Logrono', 'Ecuador');
INSERT INTO core_nga (id, name, subregion, nga_code, longitude, latitude, capital_city, fao_country) VALUES (33, 'Big Island Hawaii', 'Hawaii', 'USHI', -155.916989, 19.528931, 'Kona', 'USA');
INSERT INTO core_nga (id, name, subregion, nga_code, longitude, latitude, capital_city, fao_country) VALUES (34, 'Chuuk Islands', 'Micronesia', 'MI', 151.601918, 7.351343, 'Chuuk', 'Micronesia');
INSERT INTO core_nga (id, name, subregion, nga_code, longitude, latitude, capital_city, fao_country) VALUES (35, 'Oro PNG', 'New Guinea', 'NG', 148.193783, -8.590711, 'Oro', 'PNG');