UPDATE core_polity SET long_name = 'Latium - Copper Age' WHERE name = 'ItLatCA';
UPDATE core_polity SET long_name = 'Latium - Bronze Age' WHERE name = 'ItLatBA';
UPDATE core_polity SET long_name = 'Latium - Iron Age' WHERE name = 'ItLatIA';
UPDATE core_polity SET long_name = 'Roman Kingdom' WHERE name = 'ItRomRg';
UPDATE core_polity SET long_name = 'Roman Republic' WHERE name = 'ItRomER';
UPDATE core_polity SET long_name = 'Middle Roman Republic' WHERE name = 'ItRomMR';
UPDATE core_polity SET long_name = 'Late Roman Republic' WHERE name = 'ItRomLR';
UPDATE core_polity SET long_name = 'Roman Empire - Principate' WHERE name = 'ItRomPr';
UPDATE core_polity SET long_name = 'Roman Empire - Dominate' WHERE name = 'TrRomDm';
UPDATE core_polity SET long_name = 'Western Roman Empire - Late Antiquity' WHERE name = 'ItRomWe';
UPDATE core_polity SET long_name = 'Ostrogothic Kingdom' WHERE name = 'ItOstrg';
UPDATE core_polity SET long_name = 'Exarchate of Ravenna' WHERE name = 'ItRav**';
UPDATE core_polity SET long_name = 'Republic of St Peter I' WHERE name = 'ItStPet';
UPDATE core_polity SET long_name = 'Rome - Republic of St Peter II' WHERE name = 'ItPapEM';
UPDATE core_polity SET long_name = 'Papal States - High Medieval Period' WHERE name = 'ItPapHM';
UPDATE core_polity SET long_name = 'Papal States - Renaissance Period' WHERE name = 'ItPapRn';
UPDATE core_polity SET long_name = 'Papal States - Medieval Period I' WHERE name = 'ItPapM1';
UPDATE core_polity SET long_name = 'Papal States - Medieval Period II' WHERE name = 'ItPapM2';
UPDATE core_polity SET long_name = 'Early Bronze Age Beaker Culture' WHERE name = 'FrBeakr';
UPDATE core_polity SET long_name = 'Atlantic Complex' WHERE name = 'FrAtlBA';
UPDATE core_polity SET long_name = 'Hallstatt A-B1' WHERE name = 'FrHallA';
UPDATE core_polity SET long_name = 'Hallstatt B2-3' WHERE name = 'FrHallB';
UPDATE core_polity SET long_name = 'Hallstatt C' WHERE name = 'FrHallC';
UPDATE core_polity SET long_name = 'Hallstatt D' WHERE name = 'FrHallD';
UPDATE core_polity SET long_name = 'La Tene A-B1' WHERE name = 'FrTeneA';
UPDATE core_polity SET long_name = 'La Tene B2-C1' WHERE name = 'FrTeneB';
UPDATE core_polity SET long_name = 'La Tene C2-D' WHERE name = 'FrTeneC';
UPDATE core_polity SET long_name = 'East Roman Empire' WHERE name = 'TrERom*';
UPDATE core_polity SET long_name = 'Early Merovingian' WHERE name = 'FrMervE';
UPDATE core_polity SET long_name = 'Middle Merovingian' WHERE name = 'FrMervM';
UPDATE core_polity SET long_name = 'Proto-Carolingian' WHERE name = 'FrMervL';
UPDATE core_polity SET long_name = 'Carolingian Empire I' WHERE name = 'FrCarlE';
UPDATE core_polity SET long_name = 'Carolingian Empire II' WHERE name = 'FrCarlL';
UPDATE core_polity SET long_name = 'Proto-French Kingdom' WHERE name = 'FrCaptE';
UPDATE core_polity SET long_name = 'French Kingdom - Late Capetian' WHERE name = 'FrCaptL';
UPDATE core_polity SET long_name = 'French Kingdom - Early Valois' WHERE name = 'FrValoE';
UPDATE core_polity SET long_name = 'French Kingdom - Late Valois' WHERE name = 'FrValoL';
UPDATE core_polity SET long_name = 'French Kingdom - Early Bourbon' WHERE name = 'FrBurbE';
UPDATE core_polity SET long_name = 'French Kingdom - Late Bourbon' WHERE name = 'FrBurbL';
UPDATE core_polity SET long_name = 'Icelandic Commonwealth' WHERE name = 'IsCommw';
UPDATE core_polity SET long_name = 'Kingdom of Norway' WHERE name = 'NorKing';
UPDATE core_polity SET long_name = 'Neolithic Crete' WHERE name = 'GrCrNeo';
UPDATE core_polity SET long_name = 'Prepalatial Crete' WHERE name = 'GrCrPre';
UPDATE core_polity SET long_name = 'The Old Palace Crete' WHERE name = 'GrCrOPa';
UPDATE core_polity SET long_name = 'New Palace Crete' WHERE name = 'GrCrNPa';
UPDATE core_polity SET long_name = 'Monopalatial Crete' WHERE name = 'GrCrMPa';
UPDATE core_polity SET long_name = 'Postpalatial Crete' WHERE name = 'GrCrPPa';
UPDATE core_polity SET long_name = 'Final Postpalatial Crete' WHERE name = 'GrCrFPa';
UPDATE core_polity SET long_name = 'Geometric Crete' WHERE name = 'GrCrGeo';
UPDATE core_polity SET long_name = 'Archaic Crete' WHERE name = 'GrCrArc';
UPDATE core_polity SET long_name = 'Classical Crete' WHERE name = 'GrCrCls';
UPDATE core_polity SET long_name = 'Hellenistic  Crete' WHERE name = 'GrCrHel';
UPDATE core_polity SET long_name = 'Byzantine Empire I' WHERE name = 'TrByzM1';
UPDATE core_polity SET long_name = 'The Emirate of Crete' WHERE name = 'GrCrEmr';
UPDATE core_polity SET long_name = 'Byzantine Empire II' WHERE name = 'TrByzM2';
UPDATE core_polity SET long_name = 'Byzantine Empire III' WHERE name = 'TrByzM3';
UPDATE core_polity SET long_name = 'Republic of Venice III' WHERE name = 'ItVenR3';
UPDATE core_polity SET long_name = 'Republic of Venice IV' WHERE name = 'ItVenR4';
UPDATE core_polity SET long_name = 'Ottoman Empire III' WHERE name = 'TrOttm4';
UPDATE core_polity SET long_name = 'Badarian' WHERE name = 'EgBadar';
UPDATE core_polity SET long_name = 'Naqada I' WHERE name = 'EgNaqa1';
UPDATE core_polity SET long_name = 'Naqada II' WHERE name = 'EgNaqa2';
UPDATE core_polity SET long_name = 'Egypt - Dynasty 0' WHERE name = 'EgNaqa3';
UPDATE core_polity SET long_name = 'Egypt - Dynasty I' WHERE name = 'EgDyn1*';
UPDATE core_polity SET long_name = 'Egypt - Dynasty II' WHERE name = 'EgDyn2*';
UPDATE core_polity SET long_name = 'Egypt - Classic Old Kingdom' WHERE name = 'EgOldK1';
UPDATE core_polity SET long_name = 'Egypt - Late Old Kingdom' WHERE name = 'EgOldK2';
UPDATE core_polity SET long_name = 'Egypt - Period of the Regions' WHERE name = 'EgRegns';
UPDATE core_polity SET long_name = 'Egypt - Middle Kingdom' WHERE name = 'EgMidKg';
UPDATE core_polity SET long_name = 'Egypt - Thebes-Hyksos Period' WHERE name = 'EgThebH';
UPDATE core_polity SET long_name = 'Egypt - New Kingdom Thutmosid Period' WHERE name = 'EgNKThu';
UPDATE core_polity SET long_name = 'Egypt - New Kingdom Ramesside Period' WHERE name = 'EgNKRam';
UPDATE core_polity SET long_name = 'Egypt - Thebes-Libyan Period' WHERE name = 'EgThebL';
UPDATE core_polity SET long_name = 'Egypt - Kushite Period' WHERE name = 'SdKusht';
UPDATE core_polity SET long_name = 'Egypt - Saite Period' WHERE name = 'EgSaite';
UPDATE core_polity SET long_name = 'Achaemenid Empire' WHERE name = 'IrAchae';
UPDATE core_polity SET long_name = 'Egypt - Inter-Occupation Period' WHERE name = 'EgIntOc';
UPDATE core_polity SET long_name = 'Ptolemaic Kingdom I' WHERE name = 'EgPtol1';
UPDATE core_polity SET long_name = 'Ptolemaic Kingdom II' WHERE name = 'EgPtol2';
UPDATE core_polity SET long_name = 'Umayyad Caliphate' WHERE name = 'SyCalUm';
UPDATE core_polity SET long_name = 'Abbasid Caliphate I' WHERE name = 'IqAbbs1';
UPDATE core_polity SET long_name = 'Egypt - Tulunid-Ikhshidid Period' WHERE name = 'EgTulIk';
UPDATE core_polity SET long_name = 'Fatimid Caliphate' WHERE name = 'TnFatim';
UPDATE core_polity SET long_name = 'Ayyubid Sultanate' WHERE name = 'EgAyyub';
UPDATE core_polity SET long_name = 'Egypt - Mamluk Sultanate I' WHERE name = 'EgMamBh';
UPDATE core_polity SET long_name = 'Egypt - Mamluk Sultanate II' WHERE name = 'EgMamCP';
UPDATE core_polity SET long_name = 'Egypt - Mamluk Sultanate III' WHERE name = 'EgMamBu';
UPDATE core_polity SET long_name = 'Ottoman Empire II' WHERE name = 'TrOttm3';
UPDATE core_polity SET long_name = 'Jenne-jeno I' WHERE name = 'MlJeJe1';
UPDATE core_polity SET long_name = 'Jenne-jeno II' WHERE name = 'MlJeJe2';
UPDATE core_polity SET long_name = 'Jenne-jeno III' WHERE name = 'MlJeJe3';
UPDATE core_polity SET long_name = 'Jenne-jeno IV' WHERE name = 'MlJeJe4';
UPDATE core_polity SET long_name = 'Ghana Empire I' WHERE name = 'MrWagdM';
UPDATE core_polity SET long_name = 'Ghana Empire II' WHERE name = 'MrWagdL';
UPDATE core_polity SET long_name = 'Mali Empire' WHERE name = 'MlMali*';
UPDATE core_polity SET long_name = 'Songhai Empire - Askiya Dynasty' WHERE name = 'MlSong2';
UPDATE core_polity SET long_name = 'Saadi Sultanate' WHERE name = 'MaSaadi';
UPDATE core_polity SET long_name = 'Segou Kingdom' WHERE name = 'MlSegou';
UPDATE core_polity SET long_name = 'Bamana kingdom' WHERE name = 'MlBaman';
UPDATE core_polity SET long_name = 'Akan - Pre-Ashanti' WHERE name = 'GhAshnE';
UPDATE core_polity SET long_name = 'Ashanti Empire' WHERE name = 'GhAshnL';
UPDATE core_polity SET long_name = 'Southern Mesopotamia Neolithic' WHERE name = 'IqSoNeo';
UPDATE core_polity SET long_name = 'Ubaid' WHERE name = 'IqUbaid';
UPDATE core_polity SET long_name = 'Uruk' WHERE name = 'IqUruk*';
UPDATE core_polity SET long_name = 'Early Dynastic' WHERE name = 'IqEDyn*';
UPDATE core_polity SET long_name = 'Akkadian Empire' WHERE name = 'IqAkkad';
UPDATE core_polity SET long_name = 'Ur - Dynasty III' WHERE name = 'IqUrIII';
UPDATE core_polity SET long_name = 'Isin-Larsa' WHERE name = 'IqIsinL';
UPDATE core_polity SET long_name = 'Amorite Babylonia' WHERE name = 'IqBabAm';
UPDATE core_polity SET long_name = 'Kassite Babylonia' WHERE name = 'IqBabKs';
UPDATE core_polity SET long_name = 'Second Dynasty of Isin' WHERE name = 'IqIsin2';
UPDATE core_polity SET long_name = 'Bazi Dynasty' WHERE name = 'IqBazi*';
UPDATE core_polity SET long_name = 'Dynasty of E' WHERE name = 'IqDynE*';
UPDATE core_polity SET long_name = 'Neo-Assyrian Empire' WHERE name = 'IqNAssr';
UPDATE core_polity SET long_name = 'Neo-Babylonian Empire' WHERE name = 'IqNeoBb';
UPDATE core_polity SET long_name = 'Seleucid Empire' WHERE name = 'IrSeleu';
UPDATE core_polity SET long_name = 'Parthian Empire I' WHERE name = 'IrPart1';
UPDATE core_polity SET long_name = 'Parthian Empire II' WHERE name = 'IrPart2';
UPDATE core_polity SET long_name = 'Sassanid Empire I' WHERE name = 'IrSasn1';
UPDATE core_polity SET long_name = 'Sassanid Empire II' WHERE name = 'IrSasn2';
UPDATE core_polity SET long_name = 'Buyid Confederation' WHERE name = 'IrBuyid';
UPDATE core_polity SET long_name = 'Seljuk Empire' WHERE name = 'IrSeljq';
UPDATE core_polity SET long_name = 'Abbasid Caliphate II' WHERE name = 'IqAbbs2';
UPDATE core_polity SET long_name = 'Il-khanate' WHERE name = 'IrIlkhn';
UPDATE core_polity SET long_name = 'Timurid Empire' WHERE name = 'UzTimur';
UPDATE core_polity SET long_name = 'Safavid Empire' WHERE name = 'IrSafvd';
UPDATE core_polity SET long_name = 'Pre-Ceramic Period' WHERE name = 'IrPrCer';
UPDATE core_polity SET long_name = 'Formative Period' WHERE name = 'IrForma';
UPDATE core_polity SET long_name = 'Susiana - Muhammad Jaffar' WHERE name = 'IrArcha';
UPDATE core_polity SET long_name = 'Susiana A' WHERE name = 'IrKhzE*';
UPDATE core_polity SET long_name = 'Susiana B' WHERE name = 'IrKhzEM';
UPDATE core_polity SET long_name = 'Susiana - Early Ubaid' WHERE name = 'IrKhzM*';
UPDATE core_polity SET long_name = 'Susiana - Late Ubaid' WHERE name = 'IrKhzL*';
UPDATE core_polity SET long_name = 'Susa I' WHERE name = 'IrSusa1';
UPDATE core_polity SET long_name = 'Susa II' WHERE name = 'IrSusa2';
UPDATE core_polity SET long_name = 'Susa III' WHERE name = 'IrSusa3';
UPDATE core_polity SET long_name = 'Elam - Awan Dynasty I' WHERE name = 'IrAwanE';
UPDATE core_polity SET long_name = 'Elam - Shimashki Period' WHERE name = 'IrShima';
UPDATE core_polity SET long_name = 'Elam - Early Sukkalmah' WHERE name = 'IrSukkE';
UPDATE core_polity SET long_name = 'Elam - Late Sukkalmah' WHERE name = 'IrSukkL';
UPDATE core_polity SET long_name = 'Elam - Kidinuid Period' WHERE name = 'IrMElm1';
UPDATE core_polity SET long_name = 'Elam - Igihalkid Period' WHERE name = 'IrMElm2';
UPDATE core_polity SET long_name = 'Elam - Shutrukid Period' WHERE name = 'IrMElm3';
UPDATE core_polity SET long_name = 'Elam - Crisis Period' WHERE name = 'IrElmCP';
UPDATE core_polity SET long_name = 'Elam I' WHERE name = 'IrNElm1';
UPDATE core_polity SET long_name = 'Elam II' WHERE name = 'IrNElm2';
UPDATE core_polity SET long_name = 'Elam III' WHERE name = 'IrNElm3';
UPDATE core_polity SET long_name = 'Elymais II' WHERE name = 'IrElym2';
UPDATE core_polity SET long_name = 'Sasanid Empire II' WHERE name = 'IrSasn2';
UPDATE core_polity SET long_name = 'Ak Koyunlu' WHERE name = 'IrAkKoy';
UPDATE core_polity SET long_name = 'Qajar' WHERE name = 'IrQajar';
UPDATE core_polity SET long_name = 'Canaan' WHERE name = 'IlCanaa';
UPDATE core_polity SET long_name = 'Kenaan' WHERE name = 'LbAcPho';
UPDATE core_polity SET long_name = 'Yisrael' WHERE name = 'IlYisrl';
UPDATE core_polity SET long_name = 'Yehuda' WHERE name = 'IlJudea';
UPDATE core_polity SET long_name = 'Konya Plain - Early Neolithic' WHERE name = 'TrNeoER';
UPDATE core_polity SET long_name = 'Konya Plain - Ceramic Neolithic' WHERE name = 'TrNeoCR';
UPDATE core_polity SET long_name = 'Konya Plain - Late Neolithic' WHERE name = 'TrNeoLT';
UPDATE core_polity SET long_name = 'Konya Plain - Early Chalcolithic' WHERE name = 'TrClcER';
UPDATE core_polity SET long_name = 'Konya Plain - Late Chalcolithic' WHERE name = 'TrClcLT';
UPDATE core_polity SET long_name = 'Konya Plain - Early Bronze Age' WHERE name = 'TrBrzER';
UPDATE core_polity SET long_name = 'Middle Bronze Age in Central Anatolia' WHERE name = 'TrBrzMD';
UPDATE core_polity SET long_name = 'Hatti - Old Kingdom' WHERE name = 'TrHatOK';
UPDATE core_polity SET long_name = 'Konya Plain - Late Bronze Age II' WHERE name = 'TrBrzL2';
UPDATE core_polity SET long_name = 'Hatti - New Kingdom' WHERE name = 'TrHatNK';
UPDATE core_polity SET long_name = 'Neo-Hittite Kingdoms' WHERE name = 'TrNHitt';
UPDATE core_polity SET long_name = 'Tabal Kingdoms' WHERE name = 'TrTabal';
UPDATE core_polity SET long_name = 'Phrygian Kingdom' WHERE name = 'TrPhryg';
UPDATE core_polity SET long_name = 'Kingdom of Lydia' WHERE name = 'TrLydia';
UPDATE core_polity SET long_name = 'Kingdom of Lysimachus' WHERE name = 'TrLysim';
UPDATE core_polity SET long_name = 'Late Cappadocia' WHERE name = 'TrCappL';
UPDATE core_polity SET long_name = 'Sultanate of Rum' WHERE name = 'TrRum**';
UPDATE core_polity SET long_name = 'Ottoman Emirate' WHERE name = 'TrOttm1';
UPDATE core_polity SET long_name = 'Ottoman Empire I' WHERE name = 'TrOttm2';
UPDATE core_polity SET long_name = 'Yemen - Late Neolithic' WHERE name = 'YeNeoL*';
UPDATE core_polity SET long_name = 'Yemen - Late Bronze Age' WHERE name = 'YeLBA**';
UPDATE core_polity SET long_name = 'Sabaean Commonwealth' WHERE name = 'YeSabaC';
UPDATE core_polity SET long_name = 'Qatabanian Commonwealth' WHERE name = 'YeQatab';
UPDATE core_polity SET long_name = 'Kingdom of Saba and Dhu Raydan' WHERE name = 'YeSaRay';
UPDATE core_polity SET long_name = 'Aksum I' WHERE name = 'EtAksm1';
UPDATE core_polity SET long_name = 'Himyar I' WHERE name = 'YeHmyr1';
UPDATE core_polity SET long_name = 'Himyar II' WHERE name = 'YeHmyr2';
UPDATE core_polity SET long_name = 'Ziyadid Dynasty' WHERE name = 'YeZiyad';
UPDATE core_polity SET long_name = 'Era of the War Lords' WHERE name = 'YeWarLd';
UPDATE core_polity SET long_name = 'Rasulids' WHERE name = 'YeRasul';
UPDATE core_polity SET long_name = 'Tahirids' WHERE name = 'YeTahir';
UPDATE core_polity SET long_name = 'Yemen - Qasimid Dynasty' WHERE name = 'YeQasmi';
UPDATE core_polity SET long_name = 'Sarazm' WHERE name = 'TjSaraz';
UPDATE core_polity SET long_name = 'Andronovo' WHERE name = 'KzAndro';
UPDATE core_polity SET long_name = 'Koktepe I' WHERE name = 'UzKok01';
UPDATE core_polity SET long_name = 'Ancient Khwarazm' WHERE name = 'UzKhw01';
UPDATE core_polity SET long_name = 'Koktepe II' WHERE name = 'UzKok02';
UPDATE core_polity SET long_name = 'Greco-Bactrian Kingdom' WHERE name = 'AfGrBct';
UPDATE core_polity SET long_name = 'Tocharians' WHERE name = 'AfTochr';
UPDATE core_polity SET long_name = 'Kushan Empire' WHERE name = 'AfKushn';
UPDATE core_polity SET long_name = 'Kidarite Kingdom' WHERE name = 'AfKidar';
UPDATE core_polity SET long_name = 'Hepthalite Empire' WHERE name = 'AfHepht';
UPDATE core_polity SET long_name = 'Western Turk Khaganate' WHERE name = 'KgWTurk';
UPDATE core_polity SET long_name = 'Sogdiana - City-States Period' WHERE name = 'UzSogdi';
UPDATE core_polity SET long_name = 'Samanid Empire' WHERE name = 'UzSamnd';
UPDATE core_polity SET long_name = 'Kara-Khanids' WHERE name = 'KgKarKh';
UPDATE core_polity SET long_name = 'Chagatai Khaganate' WHERE name = 'UzChagt';
UPDATE core_polity SET long_name = 'Khanate of Bukhara' WHERE name = 'UzJanid';
UPDATE core_polity SET long_name = 'Early Xiongnu' WHERE name = 'MnXngnE';
UPDATE core_polity SET long_name = 'Xiongnu Imperial Confederation' WHERE name = 'MnXngnM';
UPDATE core_polity SET long_name = 'Late Xiongnu' WHERE name = 'MnXngnL';
UPDATE core_polity SET long_name = 'Xianbei Confederation' WHERE name = 'MnXianb';
UPDATE core_polity SET long_name = 'Rouran Khaganate' WHERE name = 'MnRourn';
UPDATE core_polity SET long_name = 'Eastern Turk Khaganate' WHERE name = 'MnETurk';
UPDATE core_polity SET long_name = 'Second Turk Khaganate' WHERE name = 'MnTurk2';
UPDATE core_polity SET long_name = 'Uigur Khaganate' WHERE name = 'MnUigur';
UPDATE core_polity SET long_name = 'Shiwei' WHERE name = 'MnShiwe';
UPDATE core_polity SET long_name = 'Khitan 2' WHERE name = 'MnKhitn';
UPDATE core_polity SET long_name = 'Early Mongols' WHERE name = 'MnMongE';
UPDATE core_polity SET long_name = 'Mongol Empire' WHERE name = 'MnMngKh';
UPDATE core_polity SET long_name = 'Late Mongols' WHERE name = 'MnMongL';
UPDATE core_polity SET long_name = 'Zungharian Empire' WHERE name = 'MnZungh';
UPDATE core_polity SET long_name = 'Late Qing' WHERE name = 'CnQingL';
UPDATE core_polity SET long_name = 'Sakha - Early' WHERE name = 'RuYakuE';
UPDATE core_polity SET long_name = 'Sakha - Late' WHERE name = 'RuYakuL';
UPDATE core_polity SET long_name = 'Kachi Plain - Aceramic Neolithic' WHERE name = 'PkAcerN';
UPDATE core_polity SET long_name = 'Kachi Plain - Ceramic Neolithic' WHERE name = 'PkCeraN';
UPDATE core_polity SET long_name = 'Kachi Plain - Chalcolithic' WHERE name = 'PkChalc';
UPDATE core_polity SET long_name = 'Kachi Plain - Pre-Urban Period' WHERE name = 'PkPreUr';
UPDATE core_polity SET long_name = 'Kachi Plain - Urban Period I' WHERE name = 'PkUrbn1';
UPDATE core_polity SET long_name = 'Kachi Plain - Urban Period II' WHERE name = 'PkUrbn2';
UPDATE core_polity SET long_name = 'Kachi Plain - Post-Urban Period' WHERE name = 'PkPostU';
UPDATE core_polity SET long_name = 'Kachi Plain - Proto-Historic Period' WHERE name = 'PkProto';
UPDATE core_polity SET long_name = 'Mauryan Empire' WHERE name = 'InMaury';
UPDATE core_polity SET long_name = 'Indo-Greek Kingdom' WHERE name = 'PkIndGr';
UPDATE core_polity SET long_name = 'Sind - Abbasid-Fatimid Period' WHERE name = 'PkSind1';
UPDATE core_polity SET long_name = 'Principality of Ghur' WHERE name = 'AfGhurd';
UPDATE core_polity SET long_name = 'Delhi Sultanate' WHERE name = 'InDelh*';
UPDATE core_polity SET long_name = 'Sind - Samma Dynasty' WHERE name = 'PkSind2';
UPDATE core_polity SET long_name = 'Mughal Empire' WHERE name = 'InMugl*';
UPDATE core_polity SET long_name = 'Durrani Empire' WHERE name = 'AfDurrn';
UPDATE core_polity SET long_name = 'Neolithic Middle Ganga' WHERE name = 'InGangN';
UPDATE core_polity SET long_name = 'Chalcolithic Middle Ganga' WHERE name = 'InGangC';
UPDATE core_polity SET long_name = 'Mahajanapada era' WHERE name = 'InMahaJ';
UPDATE core_polity SET long_name = 'Sunga Empire' WHERE name = 'InSunga';
UPDATE core_polity SET long_name = 'Kingdom of Ayodhya' WHERE name = 'InAyodE';
UPDATE core_polity SET long_name = 'Gupta Dynasty' WHERE name = 'InGupta';
UPDATE core_polity SET long_name = 'Maghada' WHERE name = 'InMagad';
UPDATE core_polity SET long_name = 'Kanauj' WHERE name = 'InKanau';
UPDATE core_polity SET long_name = 'Rashtrakuta Empire' WHERE name = 'InRasht';
UPDATE core_polity SET long_name = 'Gurjar' WHERE name = 'InGurjr';
UPDATE core_polity SET long_name = 'Gahadavala' WHERE name = 'InGhdvl';
UPDATE core_polity SET long_name = 'Deccan - Neolithic' WHERE name = 'InDecNL';
UPDATE core_polity SET long_name = 'Deccan - Iron Age' WHERE name = 'InDecIA';
UPDATE core_polity SET long_name = 'Post-Mauryan Kingdoms' WHERE name = 'InDecKg';
UPDATE core_polity SET long_name = 'Satavahana Empire' WHERE name = 'InSataL';
UPDATE core_polity SET long_name = 'Vakataka Kingdom' WHERE name = 'InVakat';
UPDATE core_polity SET long_name = 'Kadamba Empire' WHERE name = 'InKadam';
UPDATE core_polity SET long_name = 'Chalukyas of Badami' WHERE name = 'InChaBd';
UPDATE core_polity SET long_name = 'Chalukyas of Kalyani' WHERE name = 'InChaKl';
UPDATE core_polity SET long_name = 'Hoysala Kingdom' WHERE name = 'InHoysa';
UPDATE core_polity SET long_name = 'Kampili Kingdom' WHERE name = 'InKampi';
UPDATE core_polity SET long_name = 'Vijayanagara Empire' WHERE name = 'InVijay';
UPDATE core_polity SET long_name = 'Second British Empire' WHERE name = 'GbEmpr2';
UPDATE core_polity SET long_name = 'Early Garo' WHERE name = 'InGaroE';
UPDATE core_polity SET long_name = 'Late Garo' WHERE name = 'InGaroL';
UPDATE core_polity SET long_name = 'Bronze Age Cambodia' WHERE name = 'KhMekBA';
UPDATE core_polity SET long_name = 'Iron Age Cambodia' WHERE name = 'KhMekIA';
UPDATE core_polity SET long_name = 'Funan I' WHERE name = 'KhFunaE';
UPDATE core_polity SET long_name = 'Funan II' WHERE name = 'KhFunaL';
UPDATE core_polity SET long_name = 'Chenla' WHERE name = 'KhChenl';
UPDATE core_polity SET long_name = 'Early Angkor' WHERE name = 'KhAngkE';
UPDATE core_polity SET long_name = 'Classical Angkor' WHERE name = 'KhAngkC';
UPDATE core_polity SET long_name = 'Late Angkor' WHERE name = 'KhAngkL';
UPDATE core_polity SET long_name = 'Khmer Kingdom' WHERE name = 'KhCambd';
UPDATE core_polity SET long_name = 'Ayutthaya' WHERE name = 'ThAyuth';
UPDATE core_polity SET long_name = 'Rattanakosin' WHERE name = 'ThRattn';
UPDATE core_polity SET long_name = 'Java - Buni Culture' WHERE name = 'IdCJBun';
UPDATE core_polity SET long_name = 'Kalingga Kingdom' WHERE name = 'IdKalin';
UPDATE core_polity SET long_name = 'Medang Kingdom' WHERE name = 'IdMedng';
UPDATE core_polity SET long_name = 'Kediri Kingdom' WHERE name = 'IdKedir';
UPDATE core_polity SET long_name = 'Majapahit Kingdom' WHERE name = 'IdMajap';
UPDATE core_polity SET long_name = 'Mataram Sultanate' WHERE name = 'IdMatrm';
UPDATE core_polity SET long_name = 'Iban - Pre-Brooke' WHERE name = 'IdBrokE';
UPDATE core_polity SET long_name = 'Iban - Brooke Raj and Colonial' WHERE name = 'IdBrokL';
UPDATE core_polity SET long_name = 'Peiligang' WHERE name = 'CnPeili';
UPDATE core_polity SET long_name = 'Yangshao' WHERE name = 'CnYngsh';
UPDATE core_polity SET long_name = 'Longshan' WHERE name = 'CnLngsh';
UPDATE core_polity SET long_name = 'Erlitou' WHERE name = 'CnErlit';
UPDATE core_polity SET long_name = 'Erligang' WHERE name = 'CnErlig';
UPDATE core_polity SET long_name = 'Late Shang' WHERE name = 'CnShang';
UPDATE core_polity SET long_name = 'Western Zhou' WHERE name = 'CnWZhou';
UPDATE core_polity SET long_name = 'Jin State - Spring and Autumn Period' WHERE name = 'CnJinSA';
UPDATE core_polity SET long_name = 'Wei State - Warring States Period' WHERE name = 'CnWeiWS';
UPDATE core_polity SET long_name = 'Western Han' WHERE name = 'CnWHan*';
UPDATE core_polity SET long_name = 'Eastern Han' WHERE name = 'CnEHan*';
UPDATE core_polity SET long_name = 'Western Jin' WHERE name = 'CnErJin';
UPDATE core_polity SET long_name = 'Northern Wei' WHERE name = 'CnNWei*';
UPDATE core_polity SET long_name = 'Sui Dynasty' WHERE name = 'CnSui**';
UPDATE core_polity SET long_name = 'Early Tang Dynasty' WHERE name = 'CnTangE';
UPDATE core_polity SET long_name = 'Later Tang Dynasty' WHERE name = 'CnTangL';
UPDATE core_polity SET long_name = 'Northern Song' WHERE name = 'CnNSong';
UPDATE core_polity SET long_name = 'Later Jin' WHERE name = 'CnLrJin';
UPDATE core_polity SET long_name = 'Yuan Dynasty' WHERE name = 'CnYuan*';
UPDATE core_polity SET long_name = 'Ming Dynasty' WHERE name = 'CnMing*';
UPDATE core_polity SET long_name = 'Early Qing' WHERE name = 'CnQingE';
UPDATE core_polity SET long_name = 'Incipient Jomon' WHERE name = 'JpJomo1';
UPDATE core_polity SET long_name = 'Initial Jomon' WHERE name = 'JpJomo2';
UPDATE core_polity SET long_name = 'Early Jomon' WHERE name = 'JpJomo3';
UPDATE core_polity SET long_name = 'Middle Jomon ' WHERE name = 'JpJomo4';
UPDATE core_polity SET long_name = 'Late Jomon ' WHERE name = 'JpJomo5';
UPDATE core_polity SET long_name = 'Final Jomon ' WHERE name = 'JpJomo6';
UPDATE core_polity SET long_name = 'Kansai - Yayoi Period' WHERE name = 'JpYayoi';
UPDATE core_polity SET long_name = 'Kansai - Kofun Period' WHERE name = 'JpKofun';
UPDATE core_polity SET long_name = 'Kansai - Asuka Period' WHERE name = 'JpAsuka';
UPDATE core_polity SET long_name = 'Kansai - Nara Period' WHERE name = 'JpNara*';
UPDATE core_polity SET long_name = 'Kansai - Heian Period' WHERE name = 'JpHeian';
UPDATE core_polity SET long_name = 'Kamakura Shogunate' WHERE name = 'JpKamak';
UPDATE core_polity SET long_name = 'Ashikaga Shogunate' WHERE name = 'JpAshik';
UPDATE core_polity SET long_name = 'Japan - Sengoku Jidai' WHERE name = 'JpSengk';
UPDATE core_polity SET long_name = 'Japan - Azuchi, Momoyama' WHERE name = 'JpAzMom';
UPDATE core_polity SET long_name = 'Tokugawa Shogunate' WHERE name = 'JpTokgw';
UPDATE core_polity SET long_name = 'Hmong - Late Qing' WHERE name = 'CnHQngL';
UPDATE core_polity SET long_name = 'Hmong - Early Chinese' WHERE name = 'CnHChin';
UPDATE core_polity SET long_name = 'Hawaii I' WHERE name = 'Hawaii1';
UPDATE core_polity SET long_name = 'Hawaii II' WHERE name = 'Hawaii2';
UPDATE core_polity SET long_name = 'Hawaii III' WHERE name = 'Hawaii3';
UPDATE core_polity SET long_name = 'Kingdom of Hawaii - Kamehameha Period' WHERE name = 'USKameh';
UPDATE core_polity SET long_name = 'Orokaiva - Pre-Colonial' WHERE name = 'PgOrokE';
UPDATE core_polity SET long_name = 'Orokaiva - Colonial' WHERE name = 'PgOrokL';
UPDATE core_polity SET long_name = 'Chuuk - Early Truk' WHERE name = 'FmTrukE';
UPDATE core_polity SET long_name = 'Chuuk - Late Truk' WHERE name = 'FmTrukL';
UPDATE core_polity SET long_name = 'Oaxaca - Tierras Largas' WHERE name = 'MxTieLa';
UPDATE core_polity SET long_name = 'Oaxaca - San Jose' WHERE name = 'MxSanGu';
UPDATE core_polity SET long_name = 'Oaxaca - Rosario' WHERE name = 'MxRosar';
UPDATE core_polity SET long_name = 'Early Monte Alban I' WHERE name = 'MxAlb1E';
UPDATE core_polity SET long_name = 'Monte Alban Late I' WHERE name = 'MxAlb1L';
UPDATE core_polity SET long_name = 'Monte Alban II' WHERE name = 'MxAlb2*';
UPDATE core_polity SET long_name = 'Monte Alban III' WHERE name = 'MxAlb3A';
UPDATE core_polity SET long_name = 'Monte Alban IIIB and IV' WHERE name = 'MxAlb3B';
UPDATE core_polity SET long_name = 'Monte Alban V' WHERE name = 'MxAlb5*';
UPDATE core_polity SET long_name = 'Spanish Empire' WHERE name = 'EsHabsb';
UPDATE core_polity SET long_name = 'Archaic Basin of Mexico' WHERE name = 'MxArch*';
UPDATE core_polity SET long_name = 'Initial Formative Basin of Mexico' WHERE name = 'MxInitl';
UPDATE core_polity SET long_name = 'Early Formative Basin of Mexico' WHERE name = 'MxFormE';
UPDATE core_polity SET long_name = 'Middle Formative Basin of Mexico' WHERE name = 'MxFormM';
UPDATE core_polity SET long_name = 'Late Formative Basin of Mexico' WHERE name = 'MxFormL';
UPDATE core_polity SET long_name = 'Terminal Formative Basin of Mexico' WHERE name = 'MxFormT';
UPDATE core_polity SET long_name = 'Classic Basin of Mexico' WHERE name = 'MxClass';
UPDATE core_polity SET long_name = 'Epiclassic Basin of Mexico' WHERE name = 'MxEpicl';
UPDATE core_polity SET long_name = 'Toltecs' WHERE name = 'MxToltc';
UPDATE core_polity SET long_name = 'Middle Postclassic Basin of Mexico' WHERE name = 'MxPostM';
UPDATE core_polity SET long_name = 'Aztec Empire' WHERE name = 'MxAztec';
UPDATE core_polity SET long_name = 'Cahokia - Early Woodland' WHERE name = 'USMisEW';
UPDATE core_polity SET long_name = 'Cahokia - Middle Woodland' WHERE name = 'USMisMW';
UPDATE core_polity SET long_name = 'Cahokia - Late Woodland I' WHERE name = 'USMisRo';
UPDATE core_polity SET long_name = 'Cahokia - Late Woodland II' WHERE name = 'USMisMu';
UPDATE core_polity SET long_name = 'Cahokia - Late Woodland III' WHERE name = 'USMisPa';
UPDATE core_polity SET long_name = 'Cahokia - Emergent Mississippian I' WHERE name = 'USMisSp';
UPDATE core_polity SET long_name = 'Cahokia - Emergent Mississippian II' WHERE name = 'USMisME';
UPDATE core_polity SET long_name = 'Cahokia - Lohman-Stirling' WHERE name = 'USCahoE';
UPDATE core_polity SET long_name = 'Cahokia - Moorehead' WHERE name = 'USCahoL';
UPDATE core_polity SET long_name = 'Cahokia - Sand Prairie' WHERE name = 'USMisSd';
UPDATE core_polity SET long_name = 'Oneota' WHERE name = 'USOneot';
UPDATE core_polity SET long_name = 'Early Illinois Confederation' WHERE name = 'USIllin';
UPDATE core_polity SET long_name = 'Proto-Iroquois Confederacy' WHERE name = 'UsIroqP';
UPDATE core_polity SET long_name = 'Haudenosaunee Confederacy - Early' WHERE name = 'UsIroqE';
UPDATE core_polity SET long_name = 'Haudenosaunee Confederacy - Late' WHERE name = 'UsIroqL';
UPDATE core_polity SET long_name = 'Cuzco - Late Formative' WHERE name = 'PeCuzLF';
UPDATE core_polity SET long_name = 'Cuzco - Early Intermediate I' WHERE name = 'PeCuzE1';
UPDATE core_polity SET long_name = 'Cuzco - Early Intermediate II' WHERE name = 'PeCuzE2';
UPDATE core_polity SET long_name = 'Wari Empire' WHERE name = 'PeWari*';
UPDATE core_polity SET long_name = 'Cuzco - Late Intermediate I' WHERE name = 'PeCuzL1';
UPDATE core_polity SET long_name = 'Cuzco - Late Intermediate II' WHERE name = 'PeCuzL2';
UPDATE core_polity SET long_name = 'Inca Empire' WHERE name = 'PeInca*';
UPDATE core_polity SET long_name = 'Neguanje' WHERE name = 'CoNahua';
UPDATE core_polity SET long_name = 'Tairona' WHERE name = 'CoTairo';
UPDATE core_polity SET long_name = 'Jivaro - Colonial' WHERE name = 'EcJivaE';
UPDATE core_polity SET long_name = 'Jivaro - Ecuadorian' WHERE name = 'EcJivaL';