UPDATE core_polity SET long_name = 'Archaic Basin of Mexico' WHERE name = 'MxArch*';
UPDATE core_polity SET long_name = 'Initial Formative Basin of Mexico' WHERE name = 'MxInitl';
UPDATE core_polity SET long_name = 'Early Formative Basin of Mexico' WHERE name = 'MxFormE';
UPDATE core_polity SET long_name = 'Middle Formative Basin of Mexico' WHERE name = 'MxFormM';
UPDATE core_polity SET long_name = 'Late Formative Basin of Mexico' WHERE name = 'MxFormL';
UPDATE core_polity SET long_name = 'Terminal Formative Basin of Mexico' WHERE name = 'MxFormT';
UPDATE core_polity SET long_name = 'Classic Basin of Mexico' WHERE name = 'MxClass';
UPDATE core_polity SET long_name = 'Epiclassic Basin of Mexico' WHERE name = 'MxEpicl';
UPDATE core_polity SET long_name = 'Toltecs' WHERE name = 'MxToltc';
UPDATE core_polity SET long_name = 'Middle Postclassic Basin of Mexico' WHERE name = 'MxPostM';
UPDATE core_polity SET long_name = 'Aztec Empire' WHERE name = 'MxAztec';
UPDATE core_polity SET long_name = 'Hawaii I' WHERE name = 'Hawaii1';
UPDATE core_polity SET long_name = 'Hawaii II' WHERE name = 'Hawaii2';
UPDATE core_polity SET long_name = 'Hawaii III' WHERE name = 'Hawaii3';
UPDATE core_polity SET long_name = 'Kingdom of Hawaii - Kamehameha Period' WHERE name = 'USKameh';
UPDATE core_polity SET long_name = 'Kingdom of Hawaii - Post-Kamehameha Period' WHERE name = 'USHawai';
UPDATE core_polity SET long_name = 'Cahokia - Early Woodland' WHERE name = 'USMisEW';
UPDATE core_polity SET long_name = 'Cahokia - Middle Woodland' WHERE name = 'USMisMW';
UPDATE core_polity SET long_name = 'Cahokia - Late Woodland I' WHERE name = 'USMisRo';
UPDATE core_polity SET long_name = 'Cahokia - Late Woodland II' WHERE name = 'USMisMu';
UPDATE core_polity SET long_name = 'Cahokia - Late Woodland III' WHERE name = 'USMisPa';
UPDATE core_polity SET long_name = 'Cahokia - Emergent Mississippian I' WHERE name = 'USMisSp';
UPDATE core_polity SET long_name = 'Cahokia - Sand Prairie' WHERE name = 'USMisSd';
UPDATE core_polity SET long_name = 'Oneota' WHERE name = 'USOneot';
UPDATE core_polity SET long_name = 'Early Illinois Confederation' WHERE name = 'USIllin';
UPDATE core_polity SET long_name = 'Late Illinois Confederation' WHERE name = 'USIllinL';
UPDATE core_polity SET long_name = 'Cahokia - Lohman-Stirling' WHERE name = 'USCahoE';
UPDATE core_polity SET long_name = 'Cahokia - Moorehead' WHERE name = 'USCahoL';
UPDATE core_polity SET long_name = 'Cahokia - Emergent Mississippian II' WHERE name = 'USMisME';
UPDATE core_polity SET long_name = 'Bronze Age Cambodia' WHERE name = 'KhMekBA';
UPDATE core_polity SET long_name = 'Bronze Age Cambodia' WHERE name = 'KhMekIA';
UPDATE core_polity SET long_name = 'Funan I' WHERE name = 'KhFunaE';
UPDATE core_polity SET long_name = 'Funan II' WHERE name = 'KhFunaL';
UPDATE core_polity SET long_name = 'Chenla' WHERE name = 'KhChenl';
UPDATE core_polity SET long_name = 'Early Angkor' WHERE name = 'KhAngkE';
UPDATE core_polity SET long_name = 'Classical Angkor' WHERE name = 'KhAngkC';
UPDATE core_polity SET long_name = 'Late Angkor' WHERE name = 'KhAngkL';
UPDATE core_polity SET long_name = 'Khmer Kingdom' WHERE name = 'KhCambd';
UPDATE core_polity SET long_name = 'Ayutthaya' WHERE name = 'ThAyuth';
UPDATE core_polity SET long_name = 'Rattanakosin' WHERE name = 'ThRattn';
UPDATE core_polity SET long_name = 'Java - Buni Culture' WHERE name = 'IdCJBun';
UPDATE core_polity SET long_name = 'Kalingga Kingdom' WHERE name = 'IdKalin';
UPDATE core_polity SET long_name = 'Medang Kingdom' WHERE name = 'IdMedng';
UPDATE core_polity SET long_name = 'Kediri Kingdom' WHERE name = 'IdKedir';
UPDATE core_polity SET long_name = 'Majapahit Kingdom' WHERE name = 'IdMajap';
UPDATE core_polity SET long_name = 'Mataram Sultanate' WHERE name = 'IdMatrm';
UPDATE core_polity SET long_name = 'Monagrillo' WHERE name = 'PaMonag';
UPDATE core_polity SET long_name = 'La Mula-Sarigua' WHERE name = 'PaLaMul';
UPDATE core_polity SET long_name = 'Early Greater Coclé' WHERE name = 'PaCocl1';
UPDATE core_polity SET long_name = 'Middle Greater Coclé' WHERE name = 'PaCocl2';
UPDATE core_polity SET long_name = 'Late Greater Coclé' WHERE name = 'PaCocl3';
UPDATE core_polity SET long_name = 'Chuuk - Early Truk' WHERE name = 'FmTrukE';
UPDATE core_polity SET long_name = 'Chuuk - Late Truk' WHERE name = 'FmTrukL';
UPDATE core_polity SET long_name = 'Neolithic Crete' WHERE name = 'GrCrNeo';
UPDATE core_polity SET long_name = 'Prepalatial Crete' WHERE name = 'GrCrPre';
UPDATE core_polity SET long_name = 'The Old Palace Crete' WHERE name = 'GrCrOPa';
UPDATE core_polity SET long_name = 'New Palace Crete' WHERE name = 'GrCrNPa';
UPDATE core_polity SET long_name = 'Monopalatial Crete' WHERE name = 'GrCrMPa';
UPDATE core_polity SET long_name = 'Postpalatial Crete' WHERE name = 'GrCrPPa';
UPDATE core_polity SET long_name = 'Final Postpalatial Crete' WHERE name = 'GrCrFPa';
UPDATE core_polity SET long_name = 'Geometric Crete' WHERE name = 'GrCrGeo';
UPDATE core_polity SET long_name = 'Archaic Crete' WHERE name = 'GrCrArc';
UPDATE core_polity SET long_name = 'Classical Crete' WHERE name = 'GrCrCls';
UPDATE core_polity SET long_name = 'Hellenistic Crete' WHERE name = 'GrCrHel';
UPDATE core_polity SET long_name = 'Roman Empire - Principate' WHERE name = 'ItRomPr';
UPDATE core_polity SET long_name = 'Roman Empire - Dominate' WHERE name = 'TrRomDm';
UPDATE core_polity SET long_name = 'East Roman Empire' WHERE name = 'TrERom*';
UPDATE core_polity SET long_name = 'Byzantine Empire I' WHERE name = 'TrByzM1';
UPDATE core_polity SET long_name = 'The Emirate of Crete' WHERE name = 'GrCrEmr';
UPDATE core_polity SET long_name = 'Bzyantine Empire II' WHERE name = 'TrByzM2';
UPDATE core_polity SET long_name = 'Bzyantine Empire III' WHERE name = 'TrByzM3';
UPDATE core_polity SET long_name = 'Cuzco - Late Formative' WHERE name = 'PeCuzLF';
UPDATE core_polity SET long_name = 'Cuzco - Early Intermediate I' WHERE name = 'PeCuzE1';
UPDATE core_polity SET long_name = 'Cuzco - Early Intermediate II' WHERE name = 'PeCuzE2';
UPDATE core_polity SET long_name = 'Wari Empire' WHERE name = 'PeWari*';
UPDATE core_polity SET long_name = 'Cuzco - Late Intermediate I' WHERE name = 'PeCuzL1';
UPDATE core_polity SET long_name = 'Cuzco - Late Intermediate II' WHERE name = 'PeCuzL2';
UPDATE core_polity SET long_name = 'Inca Empire' WHERE name = 'PeInca*';
UPDATE core_polity SET long_name = 'Spanish Empire I' WHERE name = 'EsHabsb';
UPDATE core_polity SET long_name = 'Deccan - Neolithic' WHERE name = 'InDecNL';
UPDATE core_polity SET long_name = 'Deccan - Iron Age' WHERE name = 'InDecIA';
UPDATE core_polity SET long_name = 'Mauryan Empire' WHERE name = 'InMaury';
UPDATE core_polity SET long_name = 'Post-Mauryan Kingdoms' WHERE name = 'InDecKg';
UPDATE core_polity SET long_name = 'Satavahana Empire' WHERE name = 'InSataL';
UPDATE core_polity SET long_name = 'Vakataka Kingdom' WHERE name = 'InVakat';
UPDATE core_polity SET long_name = 'Kadamba Empire' WHERE name = 'InKadam';
UPDATE core_polity SET long_name = 'Chalukyas of Badami' WHERE name = 'InChaBd';
UPDATE core_polity SET long_name = 'Rashtrakuta Empire' WHERE name = 'InRasht';
UPDATE core_polity SET long_name = 'Chalukyas of Kalyani' WHERE name = 'InChaKl';
UPDATE core_polity SET long_name = 'Hoysala Kingdom' WHERE name = 'InHoysa';
UPDATE core_polity SET long_name = 'Kampili Kingdom' WHERE name = 'InKampi';
UPDATE core_polity SET long_name = 'Vijayanagara Empire' WHERE name = 'InVijay';
UPDATE core_polity SET long_name = 'Mughal Empire' WHERE name = 'InMugl*';
UPDATE core_polity SET long_name = 'British Empire I' WHERE name = 'GbEmpr2';
UPDATE core_polity SET long_name = 'Proto-Iroquois Confederacy' WHERE name = 'UsIroqP';
UPDATE core_polity SET long_name = 'Haudenosaunee Confederacy - Early' WHERE name = 'UsIroqE';
UPDATE core_polity SET long_name = 'Haudenosaunee Confederacy - Late' WHERE name = 'UsIroqL';
UPDATE core_polity SET long_name = 'Canaan' WHERE name = 'IlCanaa';
UPDATE core_polity SET long_name = 'Phoenician Empire' WHERE name = 'LbAcPho';
UPDATE core_polity SET long_name = 'Yisrael' WHERE name = 'IlYisrl';
UPDATE core_polity SET long_name = 'Neo-Assyrian Empire' WHERE name = 'IqNAssr';
UPDATE core_polity SET long_name = 'Achaemenid Empire' WHERE name = 'IrAchae';
UPDATE core_polity SET long_name = 'Seleucid Empire' WHERE name = 'IrSeleu';
UPDATE core_polity SET long_name = 'Ptolemaic Kingdom I' WHERE name = 'EgPtol1';
UPDATE core_polity SET long_name = 'Yehuda' WHERE name = 'IlJudea';
UPDATE core_polity SET long_name = 'Early Garo' WHERE name = 'InGaroE';
UPDATE core_polity SET long_name = 'Late Garo' WHERE name = 'InGaroL';
UPDATE core_polity SET long_name = 'Akan - Pre-Ashanti' WHERE name = 'GhAshnE';
UPDATE core_polity SET long_name = 'Ashanti Empire' WHERE name = 'GhAshnL';
UPDATE core_polity SET long_name = 'Icelandic Commonwealth' WHERE name = 'IsCommw';
UPDATE core_polity SET long_name = 'Kingdom of Norway' WHERE name = 'NorKing';
UPDATE core_polity SET long_name = 'Kachi Plain - Aceramic Neolithic' WHERE name = 'PkAcerN';
UPDATE core_polity SET long_name = 'Kachi Plain - Ceramic Neolithic' WHERE name = 'PkCeraN';
UPDATE core_polity SET long_name = 'Kachi Plain - Chalcolithic' WHERE name = 'PkChalc';
UPDATE core_polity SET long_name = 'Kachi Plain - Pre-Urban Period' WHERE name = 'PkPreUr';
UPDATE core_polity SET long_name = 'Kachi Plain - Urban Period I' WHERE name = 'PkUrbn1';
UPDATE core_polity SET long_name = 'Kachi Plain - Urban Period II' WHERE name = 'PkUrbn2';
UPDATE core_polity SET long_name = 'Kachi Plain - Post-Urban Period' WHERE name = 'PkPostU';
UPDATE core_polity SET long_name = 'Kachi Plain - Proto-Historic Period' WHERE name = 'PkProto';
UPDATE core_polity SET long_name = 'Parthian Empire I' WHERE name = 'IrPart1';
UPDATE core_polity SET long_name = 'Indo-Greek Kingdom' WHERE name = 'PkIndGr';
UPDATE core_polity SET long_name = 'Kushan Empire' WHERE name = 'AfKushn';
UPDATE core_polity SET long_name = 'Sasanid Empire I' WHERE name = 'IrSasn1';
UPDATE core_polity SET long_name = 'Hepthalite Empire' WHERE name = 'AfHepht';
UPDATE core_polity SET long_name = 'Sasanid Empire II' WHERE name = 'IrSasn2';
UPDATE core_polity SET long_name = 'Umayyad Caliphate' WHERE name = 'SyCalUm';
UPDATE core_polity SET long_name = 'Abbasid Caliphate I' WHERE name = 'IqAbbs1';
UPDATE core_polity SET long_name = 'Sind - Abbasid-Fatimid Period' WHERE name = 'PkSind1';
UPDATE core_polity SET long_name = 'Principality of Ghur' WHERE name = 'AfGhurd';
UPDATE core_polity SET long_name = 'Delhi Sultanate' WHERE name = 'InDelh*';
UPDATE core_polity SET long_name = 'Sind - Samma Dynasty' WHERE name = 'PkSind2';
UPDATE core_polity SET long_name = 'Durrani Empire' WHERE name = 'AfDurrn';
UPDATE core_polity SET long_name = 'Japan - Incipient Jomon' WHERE name = 'JpJomo1';
UPDATE core_polity SET long_name = 'Japan - Initial Jomon' WHERE name = 'JpJomo2';
UPDATE core_polity SET long_name = 'Japan - Early Jomon' WHERE name = 'JpJomo3';
UPDATE core_polity SET long_name = 'Japan - Middle Jomon' WHERE name = 'JpJomo4';
UPDATE core_polity SET long_name = 'Japan - Late Jomon' WHERE name = 'JpJomo5';
UPDATE core_polity SET long_name = 'Japan - Final Jomon' WHERE name = 'JpJomo6';
UPDATE core_polity SET long_name = 'Kansai - Yayoi Period' WHERE name = 'JpYayoi';
UPDATE core_polity SET long_name = 'Kansai - Kofun Period' WHERE name = 'JpKofun';
UPDATE core_polity SET long_name = 'Kansai - Asuka Period' WHERE name = 'JpAsuka';
UPDATE core_polity SET long_name = 'Kansai - Heian Period' WHERE name = 'JpHeian';
UPDATE core_polity SET long_name = 'Kamakura Shogunate' WHERE name = 'JpKamak';
UPDATE core_polity SET long_name = 'Ashikaga Shogunate' WHERE name = 'JpAshik';
UPDATE core_polity SET long_name = 'Japan - Sengoku Jidai' WHERE name = 'JpSengk';
UPDATE core_polity SET long_name = 'Japan - Azuchi‚ÄìMomoyama' WHERE name = 'JpAzMom';
UPDATE core_polity SET long_name = 'Tokugawa Shogunate' WHERE name = 'JpTokgw';
UPDATE core_polity SET long_name = 'Iban - Pre-Brooke' WHERE name = 'IdBrokE';
UPDATE core_polity SET long_name = 'Iban - Brooke Raj and Colonial' WHERE name = 'IdBrokL';
UPDATE core_polity SET long_name = 'Konya Plain - Early Neolithic' WHERE name = 'TrNeoER';
UPDATE core_polity SET long_name = 'Konya Plain - Ceramic Neolithic' WHERE name = 'TrNeoCR';
UPDATE core_polity SET long_name = 'Konya Plain - Late Neolithic' WHERE name = 'TrNeoLT';
UPDATE core_polity SET long_name = 'Konya Plain - Early Chalcolithic' WHERE name = 'TrClcER';
UPDATE core_polity SET long_name = 'Konya Plain - Late Chalcolithic' WHERE name = 'TrClcLT';
UPDATE core_polity SET long_name = 'Konya Plain - Early Bronze Age' WHERE name = 'TrBrzER';
UPDATE core_polity SET long_name = 'Middle Bronze Age in Central Anatolia' WHERE name = 'TrBrzMD';
UPDATE core_polity SET long_name = 'Hatti - Old Kingdom' WHERE name = 'TrHatOK';
UPDATE core_polity SET long_name = 'Konya Plain - Late Bronze Age II' WHERE name = 'TrBrzL2';
UPDATE core_polity SET long_name = 'Hatti - New Kingdom' WHERE name = 'TrHatNK';
UPDATE core_polity SET long_name = 'Neo-Hittite Kingdoms' WHERE name = 'TrNHitt';
UPDATE core_polity SET long_name = 'Phrygian Kingdom' WHERE name = 'TrPhryg';
UPDATE core_polity SET long_name = 'Tabal Kingdoms' WHERE name = 'TrTabal';
UPDATE core_polity SET long_name = 'Kingdom of Lydia' WHERE name = 'TrLydia';
UPDATE core_polity SET long_name = 'Kingdom of Lysimachus' WHERE name = 'TrLysim';
UPDATE core_polity SET long_name = 'Late Cappadocia' WHERE name = 'TrCappL';
UPDATE core_polity SET long_name = 'Sultanate of Rum' WHERE name = 'TrRum**';
UPDATE core_polity SET long_name = 'Il-khanate' WHERE name = 'IrIlkhn';
UPDATE core_polity SET long_name = 'Ottoman Emirate' WHERE name = 'TrOttm1';
UPDATE core_polity SET long_name = 'Ottoman Empire I' WHERE name = 'TrOttm2';
UPDATE core_polity SET long_name = 'Ottoman Empire II' WHERE name = 'TrOttm3';
UPDATE core_polity SET long_name = 'Ottoman Empire III' WHERE name = 'TrOttm4';
UPDATE core_polity SET long_name = 'Ottoman Empire IV' WHERE name = 'TrOttm5';
UPDATE core_polity SET long_name = 'Latium - Copper Age' WHERE name = 'ItLatCA';
UPDATE core_polity SET long_name = 'Latium - Bronze Age' WHERE name = 'ItLatBA';
UPDATE core_polity SET long_name = 'Latium - Iron Age' WHERE name = 'ItLatIA';
UPDATE core_polity SET long_name = 'Roman Kingdom' WHERE name = 'ItRomRg';
UPDATE core_polity SET long_name = 'Roman Republic' WHERE name = 'ItRomER';
UPDATE core_polity SET long_name = 'Middle Roman Republic' WHERE name = 'ItRomMR';
UPDATE core_polity SET long_name = 'Late Roman Republic' WHERE name = 'ItRomLR';
UPDATE core_polity SET long_name = 'Western Roman Empire - Late Antiquity' WHERE name = 'ItRomWe';
UPDATE core_polity SET long_name = 'Ostrogothic Kingdom' WHERE name = 'ItOstrg';
UPDATE core_polity SET long_name = 'Exarchate of Ravenna' WHERE name = 'ItRav**';
UPDATE core_polity SET long_name = 'Republic of St Peter I' WHERE name = 'ItStPet';
UPDATE core_polity SET long_name = 'Rome - Republic of St Peter II' WHERE name = 'ItPapEM';
UPDATE core_polity SET long_name = 'Papal States - High Medieval Period' WHERE name = 'ItPapHM';
UPDATE core_polity SET long_name = 'Papal States - Renaissance Period' WHERE name = 'ItPapRn';
UPDATE core_polity SET long_name = 'Papal States - Medieval Period I' WHERE name = 'ItPapM1';
UPDATE core_polity SET long_name = 'Papal States - Medieval Period II' WHERE name = 'ItPapM2';
UPDATE core_polity SET long_name = 'Sakha - Early' WHERE name = 'RuYakuE';
UPDATE core_polity SET long_name = 'Sakha - Late' WHERE name = 'RuYakuL';
UPDATE core_polity SET long_name = 'Shuar - Colonial' WHERE name = 'EcJivaE';
UPDATE core_polity SET long_name = 'Shuar - Ecuadorian' WHERE name = 'EcJivaL';
UPDATE core_polity SET long_name = 'Egypt New Kingdom, Thutmosid Period' WHERE name = 'EgNKThu';
UPDATE core_polity SET long_name = 'Egypt, New Kingdom Ramesside Period' WHERE name = 'EgNKRam';
UPDATE core_polity SET long_name = 'Egypt Theban Period' WHERE name = 'EgThebL';
UPDATE core_polity SET long_name = 'Carthage Empire' WHERE name = 'TnCarth';
UPDATE core_polity SET long_name = 'Kush Kingdom' WHERE name = 'SdKush';
UPDATE core_polity SET long_name = 'Egypt Saite Period' WHERE name = 'EgSaite';
UPDATE core_polity SET long_name = 'Meroe' WHERE name = 'Meroe';
UPDATE core_polity SET long_name = 'Egypt Inter-Occupation Dynasties' WHERE name = 'EgIntOc';
UPDATE core_polity SET long_name = 'Numidia' WHERE name = 'DzNumid';
UPDATE core_polity SET long_name = 'Ptolemaic Kingdom II' WHERE name = 'EgPtol2';
UPDATE core_polity SET long_name = 'Axum I' WHERE name = 'EtAksm1';
UPDATE core_polity SET long_name = 'Mauretania' WHERE name = 'MaKgMau';
UPDATE core_polity SET long_name = 'Axum II' WHERE name = 'EtAksm2';
UPDATE core_polity SET long_name = 'Vandal Kingdom' WHERE name = 'DzVandal';
UPDATE core_polity SET long_name = 'Makuria Kingdom I' WHERE name = 'SdMakur1';
UPDATE core_polity SET long_name = 'Axum III' WHERE name = 'EtAksm3';
UPDATE core_polity SET long_name = 'Alodia Kingdom' WHERE name = 'SdAlodia';
UPDATE core_polity SET long_name = 'Makuria Kingdom II' WHERE name = 'SdMakur2';
UPDATE core_polity SET long_name = 'Middle Wagadu Empire' WHERE name = 'MrWagdM';
UPDATE core_polity SET long_name = 'Tahert' WHERE name = 'DzTahrt';
UPDATE core_polity SET long_name = 'Idrisids' WHERE name = 'MaIdris';
UPDATE core_polity SET long_name = 'Makuria Kingdom III' WHERE name = 'SdMakur3';
UPDATE core_polity SET long_name = 'Kanem Empire' WHERE name = 'TdKanem';
UPDATE core_polity SET long_name = 'Fatimid Caliphate' WHERE name = 'TnFatim';
UPDATE core_polity SET long_name = 'Zirids' WHERE name = 'TnZirid';
UPDATE core_polity SET long_name = 'Almoravids' WHERE name = 'MaAlmor';
UPDATE core_polity SET long_name = 'Later Wagadu Empire' WHERE name = 'MrWagdL';
UPDATE core_polity SET long_name = 'Almohad Empire' WHERE name = 'MaAlmoh';
UPDATE core_polity SET long_name = 'Banu Ghaniya' WHERE name = 'IbBnGhn';
UPDATE core_polity SET long_name = 'Zagwe' WHERE name = 'EtZagwe';
UPDATE core_polity SET long_name = 'Hafsid Dynasty' WHERE name = 'TnHafsid';
UPDATE core_polity SET long_name = 'Mali Empire' WHERE name = 'MlMali*';
UPDATE core_polity SET long_name = 'Tlemcen' WHERE name = 'DzTlmcn';
UPDATE core_polity SET long_name = 'Zayyanid Berber Kingdom' WHERE name = 'DzBrbZy';
UPDATE core_polity SET long_name = 'Mamluk Sultanate I' WHERE name = 'EgMamBh';
UPDATE core_polity SET long_name = 'Marinid Dynasty' WHERE name = 'MaMarinid';
UPDATE core_polity SET long_name = 'Ethiopia Kingdom' WHERE name = 'EtEthiK';
UPDATE core_polity SET long_name = 'Malacca Sultanate' WHERE name = 'SoIfatS';
UPDATE core_polity SET long_name = 'Mamluk Sultanate II' WHERE name = 'EgMamCP';
UPDATE core_polity SET long_name = 'Songhai Empire' WHERE name = 'MlSong1';
UPDATE core_polity SET long_name = 'Bornu Empire' WHERE name = 'TdBornu';
UPDATE core_polity SET long_name = 'Mamluk Sultanate III' WHERE name = 'EgMamBu';
UPDATE core_polity SET long_name = 'Wattasid' WHERE name = 'MaWaFez';
UPDATE core_polity SET long_name = 'Kingdom of Congo' WHERE name = 'AoKngo2';
UPDATE core_polity SET long_name = 'Songhai Empire' WHERE name = 'MlSong2';
UPDATE core_polity SET long_name = 'Late Shang Dynasty' WHERE name = 'CnShang';
UPDATE core_polity SET long_name = 'Western Zhou Kingdom' WHERE name = 'CnWZhou';
UPDATE core_polity SET long_name = 'cn_jin_dyn_spring_and_autumn' WHERE name = 'CnJinSA';
UPDATE core_polity SET long_name = 'Chu Kingdom - Spring Autumn Period' WHERE name = 'CnChuSA';
UPDATE core_polity SET long_name = 'Wu Confederacy' WHERE name = 'CnWuCfd';
UPDATE core_polity SET long_name = 'Yue Kingdom' WHERE name = 'CnYueKg';
UPDATE core_polity SET long_name = 'Chu Kingdom - Warring States Period' WHERE name = 'CnChuWS';
UPDATE core_polity SET long_name = 'Qin Empire' WHERE name = 'CnImQin';
UPDATE core_polity SET long_name = 'Western Han Empire' WHERE name = 'CnWHan*';
UPDATE core_polity SET long_name = 'Goguryeo Kingdom' WHERE name = 'KrGogur';
UPDATE core_polity SET long_name = 'Eastern Han Empire' WHERE name = 'CnEHan*';
UPDATE core_polity SET long_name = 'Western Jin Dynasty' WHERE name = 'CnErJin';
UPDATE core_polity SET long_name = 'Eastern Jin Dynasty' WHERE name = 'cn_eastern_jin_dyn';
UPDATE core_polity SET long_name = 'Later Yan Kingdom' WHERE name = 'CnLrYan';
UPDATE core_polity SET long_name = 'Later Qin Kingdom' WHERE name = 'CnLrQin';
UPDATE core_polity SET long_name = 'Northern Wei Kingdom' WHERE name = 'CnNWei*';
UPDATE core_polity SET long_name = 'Southern Qi State' WHERE name = 'CnSouQi';
UPDATE core_polity SET long_name = 'Asuka Kingdom' WHERE name = 'JpAsuka';
UPDATE core_polity SET long_name = 'Sui Dynasty' WHERE name = 'CnSui**';
UPDATE core_polity SET long_name = 'Early Tang Dynasty' WHERE name = 'CnTangE';
UPDATE core_polity SET long_name = 'Balhae Kingdom' WHERE name = 'KrBalha';
UPDATE core_polity SET long_name = 'Nara Kingdom' WHERE name = 'JpNara*';
UPDATE core_polity SET long_name = 'Later Tang Dynasty' WHERE name = 'CnTangL';
UPDATE core_polity SET long_name = 'Heian' WHERE name = 'JpHeian';
UPDATE core_polity SET long_name = 'Goryeo Kingdom' WHERE name = 'KrGorye';
UPDATE core_polity SET long_name = 'Jurchen Dynasty' WHERE name = 'CnLrJin';
UPDATE core_polity SET long_name = 'Mongol Empire' WHERE name = 'MnMngKh';
UPDATE core_polity SET long_name = 'Great Yuan' WHERE name = 'CnYuan*';
UPDATE core_polity SET long_name = 'Ming Dynasty' WHERE name = 'CnMing*';
UPDATE core_polity SET long_name = 'Joseon Dynasty' WHERE name = 'KrJoseon';
UPDATE core_polity SET long_name = 'Warring States Japan' WHERE name = 'JpSengk';
UPDATE core_polity SET long_name = 'Third Scythian Kingdom' WHERE name = 'UaSky3K';
UPDATE core_polity SET long_name = 'Xiongnu Confederacy' WHERE name = 'MnXngnM';
UPDATE core_polity SET long_name = 'Kangju' WHERE name = 'UzKangj';
UPDATE core_polity SET long_name = 'Xiongnu Confederacy' WHERE name = 'MnXngnL';
UPDATE core_polity SET long_name = 'Loulan-Shanshan kingdom' WHERE name = 'CnLouIn';
UPDATE core_polity SET long_name = 'Tuyuhun' WHERE name = 'CnTuyhn';
UPDATE core_polity SET long_name = 'Chionites' WHERE name = 'KzChion';
UPDATE core_polity SET long_name = 'Rouran Khaganate' WHERE name = 'MnRourn';
UPDATE core_polity SET long_name = 'Yueban' WHERE name = 'KzYueba';
UPDATE core_polity SET long_name = 'Kingdom of the Huns' WHERE name = 'HuKHuns';
UPDATE core_polity SET long_name = 'Kidarite Kingdom' WHERE name = 'AfKidar';
UPDATE core_polity SET long_name = 'Hephtalites' WHERE name = 'AfHepht';
UPDATE core_polity SET long_name = 'Western Turk Khaganate' WHERE name = 'KgWTurk';
UPDATE core_polity SET long_name = 'Eastern Turk Khaganate' WHERE name = 'MnETurk';
UPDATE core_polity SET long_name = 'Avar Kingdom' WHERE name = 'HuAvarK';
UPDATE core_polity SET long_name = 'Khazar Empire' WHERE name = 'RuKhazar';
UPDATE core_polity SET long_name = 'Uyghur Khaganate' WHERE name = 'MnUigur';
UPDATE core_polity SET long_name = 'Samanid' WHERE name = 'UzSamnd';
UPDATE core_polity SET long_name = 'Khitan' WHERE name = 'MnKhitn';
UPDATE core_polity SET long_name = 'Kara Khanids' WHERE name = 'KgKarKh';
UPDATE core_polity SET long_name = 'Kingdom of Georgia II' WHERE name = 'GeGeoK2';
UPDATE core_polity SET long_name = 'Xixia' WHERE name = 'CnXixia';
UPDATE core_polity SET long_name = 'Principality of Ryazan' WHERE name = 'RuRyazan';
UPDATE core_polity SET long_name = 'Russian Principate' WHERE name = 'UaRusPr';
UPDATE core_polity SET long_name = 'Kara Khitai Khanate' WHERE name = 'TmKarKh';
UPDATE core_polity SET long_name = 'Khwarezmid Empire' WHERE name = 'TmKhwrz';
UPDATE core_polity SET long_name = 'Chagatai Khanate' WHERE name = 'UzChagt';
UPDATE core_polity SET long_name = 'Oirats' WHERE name = 'KzOirat';
UPDATE core_polity SET long_name = 'Kazan Khanate' WHERE name = 'RuKazan';
UPDATE core_polity SET long_name = 'Crimean Khanate' WHERE name = 'RuCrKha';
UPDATE core_polity SET long_name = 'Sibir Khanate' WHERE name = 'RuSibir';
UPDATE core_polity SET long_name = 'Shaybanid Kingdom' WHERE name = 'UzShayb';
UPDATE core_polity SET long_name = 'Anglo-Saxon England' WHERE name = 'GBEnglK';
UPDATE core_polity SET long_name = 'Visigothic Kingdom' WHERE name = 'EsVisigoth';
UPDATE core_polity SET long_name = 'Early Merovingian' WHERE name = 'FrMervE';
UPDATE core_polity SET long_name = 'Lombard Kingdom' WHERE name = 'ItLombr';
UPDATE core_polity SET long_name = 'Middle Merovingian' WHERE name = 'FrMervM';
UPDATE core_polity SET long_name = 'Aquitania' WHERE name = 'FrAquit';
UPDATE core_polity SET long_name = 'Bulgaria - Early' WHERE name = 'BgErBlg';
UPDATE core_polity SET long_name = 'Carolingian Empire I' WHERE name = 'FrCarlE';
UPDATE core_polity SET long_name = 'Cordoba Caliphate' WHERE name = 'EsCordo';
UPDATE core_polity SET long_name = 'Carolingian Empire II' WHERE name = 'FrCarlL';
UPDATE core_polity SET long_name = 'Bulgaria - Middle' WHERE name = 'BgMdBlg';
UPDATE core_polity SET long_name = 'Novgorod Land' WHERE name = 'RuNovPr';
UPDATE core_polity SET long_name = 'Kievan Rus' WHERE name = 'UaKiev1';
UPDATE core_polity SET long_name = 'Leon' WHERE name = 'EsLeon';
UPDATE core_polity SET long_name = 'Holy Roman Empire I' WHERE name = 'DeHRE';
UPDATE core_polity SET long_name = 'Polish Kingdom' WHERE name = 'PlPoliK';
UPDATE core_polity SET long_name = 'Volga Kingdom' WHERE name = 'BgVolga';
UPDATE core_polity SET long_name = 'Hungary Kingdom' WHERE name = 'HuKingdom';
UPDATE core_polity SET long_name = 'Aragon Kingdom' WHERE name = 'EsAragn';
UPDATE core_polity SET long_name = 'Castille Kingdom' WHERE name = 'EsCastil';
UPDATE core_polity SET long_name = 'Norman England' WHERE name = 'GBEnglK';
UPDATE core_polity SET long_name = 'Novgorod Republic' WHERE name = 'RuNovRp';
UPDATE core_polity SET long_name = 'Plantagenet England' WHERE name = 'GBEnglK';
UPDATE core_polity SET long_name = 'Vladimir-Suzdal' WHERE name = 'RuVldSz';
UPDATE core_polity SET long_name = 'Sicily Kingdom' WHERE name = 'ItSicilK';
UPDATE core_polity SET long_name = 'High Medieval Bohemian Kingdom' WHERE name = 'CzBohem';
UPDATE core_polity SET long_name = 'Galicia-Volhynia Principality' WHERE name = 'UaGalicia';
UPDATE core_polity SET long_name = 'Leon & Castille' WHERE name = 'EsLeCas';
UPDATE core_polity SET long_name = 'Teutonic Order' WHERE name = 'PlTeuton';
UPDATE core_polity SET long_name = 'Late Medieval Bohemian Kingdom' WHERE name = 'CzBohem';
UPDATE core_polity SET long_name = 'Holy Roman Empire II' WHERE name = 'DeHRE';
UPDATE core_polity SET long_name = 'fr_valois_k_1' WHERE name = 'FrValoE';
UPDATE core_polity SET long_name = 'Poland-Lithuania Kingdom' WHERE name = 'PlPoLit';
UPDATE core_polity SET long_name = 'Kalmar Union' WHERE name = 'SeKalma';
UPDATE core_polity SET long_name = 'Early Modern Bohemia' WHERE name = 'CzBohem';
UPDATE core_polity SET long_name = 'Grand Principality of Moscow, Rurikid Dynasty' WHERE name = 'RuMoskva';
UPDATE core_polity SET long_name = 'Tudor and Early Stuart England' WHERE name = 'GBEnglK';
UPDATE core_polity SET long_name = 'Swedish Kingdom' WHERE name = 'SeSwedi';
UPDATE core_polity SET long_name = 'Holy Roman Empire III' WHERE name = 'DeHRE';
UPDATE core_polity SET long_name = 'British Empire II' WHERE name = 'GbEmpr2';
UPDATE core_polity SET long_name = 'Babylonian Empire' WHERE name = 'IqBabKs';
UPDATE core_polity SET long_name = 'Mitanni Kingdom' WHERE name = 'SyMitan';
UPDATE core_polity SET long_name = 'Urartu Kingdom' WHERE name = 'TrUrart';
UPDATE core_polity SET long_name = 'Neo-Hittite Kingdom' WHERE name = 'TrNHitt';
UPDATE core_polity SET long_name = 'Phyrgian Kingdom' WHERE name = 'TrPhryg';
UPDATE core_polity SET long_name = 'Median Persian Empire' WHERE name = 'IrMedes';
UPDATE core_polity SET long_name = 'Lydian Kingdom' WHERE name = 'TrLydia';
UPDATE core_polity SET long_name = 'Neo-Babylonian Empire' WHERE name = 'IqNeoBb';
UPDATE core_polity SET long_name = 'Atropatene Kingdom' WHERE name = 'IrAtrop';
UPDATE core_polity SET long_name = 'Lysimachus Kingdom' WHERE name = 'TrLysim';
UPDATE core_polity SET long_name = 'Seleucids' WHERE name = 'IrSeleu';
UPDATE core_polity SET long_name = 'Nabataean Kingdom' WHERE name = 'JoNabat';
UPDATE core_polity SET long_name = 'Pergamon Kingdom' WHERE name = 'TrPergm';
UPDATE core_polity SET long_name = 'Greco-Bactiran Kingdom' WHERE name = 'AfGrBct';
UPDATE core_polity SET long_name = 'Armenian Kingdom' WHERE name = 'AmArtax';
UPDATE core_polity SET long_name = 'Indo-Parthian Kingdom' WHERE name = 'PkIndPR';
UPDATE core_polity SET long_name = 'Himyar I' WHERE name = 'YeHmyr1';
UPDATE core_polity SET long_name = 'Himyar II' WHERE name = 'YeHmyr2';
UPDATE core_polity SET long_name = 'Lakhmid Kigdom' WHERE name = 'IqLakhm';
UPDATE core_polity SET long_name = 'Ghassanid Kingdom' WHERE name = 'JoGhass';
UPDATE core_polity SET long_name = 'Omani Azd Tribe' WHERE name = 'OmAzd';
UPDATE core_polity SET long_name = 'Yemen Hijaz' WHERE name = 'SaRashd';
UPDATE core_polity SET long_name = 'Ummayad Caliphate' WHERE name = 'SyCalUm';
UPDATE core_polity SET long_name = 'Yemen Ziyad Dynasty' WHERE name = 'YeZiyad';
UPDATE core_polity SET long_name = 'Saffarid Caliphate' WHERE name = 'IrSaffr';
UPDATE core_polity SET long_name = 'Tulunid Interregnum' WHERE name = 'EgTulIk';
UPDATE core_polity SET long_name = 'Buwayhid Confederation' WHERE name = 'IrBuyid';
UPDATE core_polity SET long_name = 'Ghaznavid Empire' WHERE name = 'AfGhazn';
UPDATE core_polity SET long_name = 'Ghur Principality' WHERE name = 'AfGhurd';
UPDATE core_polity SET long_name = 'Seljuk Sultanate' WHERE name = 'IrSeljq';
UPDATE core_polity SET long_name = 'Yemen - Era of Warlords' WHERE name = 'YeWarLd';
UPDATE core_polity SET long_name = 'Byzantine Empire III' WHERE name = 'TrByzM3';
UPDATE core_polity SET long_name = 'Rum Sultanate' WHERE name = 'TrRum**';
UPDATE core_polity SET long_name = 'Oman Imamate' WHERE name = 'OmImamat';
UPDATE core_polity SET long_name = 'Ayyubid Sultunate' WHERE name = 'EgAyyub';
UPDATE core_polity SET long_name = 'Rasulid Dynasty' WHERE name = 'YeRasul';
UPDATE core_polity SET long_name = 'Ilkhanate' WHERE name = 'IrIlkhn';
UPDATE core_polity SET long_name = 'Jayarid Khanate' WHERE name = 'IrJalay';
UPDATE core_polity SET long_name = 'Timurids' WHERE name = 'UzTimur';
UPDATE core_polity SET long_name = 'Ak Koyunlu' WHERE name = 'IrAkkoy';
UPDATE core_polity SET long_name = 'Yemen - Tahirid Dynasty' WHERE name = 'YeTahir';
UPDATE core_polity SET long_name = 'Astrakhan Khanate' WHERE name = 'RuAstrakh';
UPDATE core_polity SET long_name = 'Safavid Empire' WHERE name = 'IrSafvd';
UPDATE core_polity SET long_name = 'Viet Baiyu Kingdom' WHERE name = 'CnBaiyu';
UPDATE core_polity SET long_name = 'Kalinga Kingdom' WHERE name = 'IdKalin';
UPDATE core_polity SET long_name = 'Nanzhao Kingdom' WHERE name = 'CnNanzh';
UPDATE core_polity SET long_name = 'Srivijaya Empire' WHERE name = 'IdSrivi';
UPDATE core_polity SET long_name = 'Dali Kingdom' WHERE name = 'CnDali';
UPDATE core_polity SET long_name = 'Bagan' WHERE name = 'MmPagan';
UPDATE core_polity SET long_name = 'Sukhotai' WHERE name = 'ThSukho';
UPDATE core_polity SET long_name = 'Lan Xang Kingdom' WHERE name = 'LaLanXang';
UPDATE core_polity SET long_name = 'Ava Kingdom' WHERE name = 'MmAva';
UPDATE core_polity SET long_name = 'Malacca Sultanate' WHERE name = 'MySultM';
UPDATE core_polity SET long_name = 'Mataram Kingdom' WHERE name = 'IdMatrm';
UPDATE core_polity SET long_name = 'Mahajanapada Era' WHERE name = 'InMahaJ';
UPDATE core_polity SET long_name = 'Maurya Empire' WHERE name = 'InMaury';
UPDATE core_polity SET long_name = 'Sunga Dynasty' WHERE name = 'InSunga';
UPDATE core_polity SET long_name = 'Indo-Graeco-Phrygian Kingdom' WHERE name = 'PkIndGr';
UPDATE core_polity SET long_name = 'Western Satraps' WHERE name = 'PkWSatrp';
UPDATE core_polity SET long_name = 'Yaudheya Republic' WHERE name = 'InYaudh';
UPDATE core_polity SET long_name = 'Gupta Dynasty' WHERE name = 'InGupta';
UPDATE core_polity SET long_name = 'Kamarupa Kingdom' WHERE name = 'InKamar';
UPDATE core_polity SET long_name = 'Magadha' WHERE name = 'InMagad';
UPDATE core_polity SET long_name = 'Maitraka Dynasty' WHERE name = 'InMaitr';
UPDATE core_polity SET long_name = 'Gurjara-Pratihara Kingdom' WHERE name = 'InGurPr';
UPDATE core_polity SET long_name = 'Maukhari Dynasty' WHERE name = 'InMaukh';
UPDATE core_polity SET long_name = 'Tibet Kingdom' WHERE name = 'CnTibet';
UPDATE core_polity SET long_name = 'Karkota Dynasty' WHERE name = 'InKarkt';
UPDATE core_polity SET long_name = 'Pala Empire' WHERE name = 'InPala';
UPDATE core_polity SET long_name = 'Chola Empire' WHERE name = 'InChol*';
UPDATE core_polity SET long_name = 'Utpala Dynasty' WHERE name = 'InUtpal';
UPDATE core_polity SET long_name = 'Solankis' WHERE name = 'InSolan';
UPDATE core_polity SET long_name = 'Chandela Kingdom' WHERE name = 'InChandel';
UPDATE core_polity SET long_name = 'Chauhana Dynasty' WHERE name = 'InChauh';
UPDATE core_polity SET long_name = 'Paramara Dynasty' WHERE name = 'InParam';
UPDATE core_polity SET long_name = 'Lohara Dynasty' WHERE name = 'InLohar';
UPDATE core_polity SET long_name = 'Ganga Kingdom' WHERE name = 'InGanga';
UPDATE core_polity SET long_name = 'Gahadavala Dynasty' WHERE name = 'InGhdvl';
UPDATE core_polity SET long_name = 'Kalachuri Empire' WHERE name = 'InKalch';
UPDATE core_polity SET long_name = 'Kakatiya Dynasty' WHERE name = 'InKakat';
UPDATE core_polity SET long_name = 'Yadava Dynasty' WHERE name = 'InYadav';
UPDATE core_polity SET long_name = 'Bengal Sultanate' WHERE name = 'BdBengl';
UPDATE core_polity SET long_name = 'Kashmiri Sultanate' WHERE name = 'InKashm';
UPDATE core_polity SET long_name = 'Bahmani Sultanate' WHERE name = 'InBahma';
UPDATE core_polity SET long_name = 'Sharqi' WHERE name = 'InSharq';
UPDATE core_polity SET long_name = 'Bijapur Sultanate' WHERE name = 'InBijap';
UPDATE core_polity SET long_name = 'Neolithic Middle Ganga' WHERE name = 'InGangN';
UPDATE core_polity SET long_name = 'Chalcolithic Middle Ganga' WHERE name = 'InGangC';
UPDATE core_polity SET long_name = 'Mahajanapada era' WHERE name = 'InMahaJ';
UPDATE core_polity SET long_name = 'Sunga Empire' WHERE name = 'InSunga';
UPDATE core_polity SET long_name = 'Kingdom of Ayodhya' WHERE name = 'InAyodE';
UPDATE core_polity SET long_name = 'Maghada' WHERE name = 'InMagad';
UPDATE core_polity SET long_name = 'Kanauj' WHERE name = 'InKanau';
UPDATE core_polity SET long_name = 'Gurjar' WHERE name = 'InGurjr';
UPDATE core_polity SET long_name = 'Yangshao' WHERE name = 'CnYngsh';
UPDATE core_polity SET long_name = 'Longshan' WHERE name = 'CnLngsh';
UPDATE core_polity SET long_name = 'Erlitou' WHERE name = 'CnErlit';
UPDATE core_polity SET long_name = 'Erligang' WHERE name = 'CnErlig';
UPDATE core_polity SET long_name = 'Late Shang' WHERE name = 'CnShang';
UPDATE core_polity SET long_name = 'Western Zhou' WHERE name = 'CnWZhou';
UPDATE core_polity SET long_name = 'Jin' WHERE name = 'CnJinSA';
UPDATE core_polity SET long_name = 'Eastern Zhou' WHERE name = 'CnZhuWS';
UPDATE core_polity SET long_name = 'Early Wei Dynasty' WHERE name = 'CnWeiWS';
UPDATE core_polity SET long_name = 'Western Jin' WHERE name = 'CnErJin';
UPDATE core_polity SET long_name = 'Northern Wei' WHERE name = 'CnNWei*';
UPDATE core_polity SET long_name = 'Northern Song' WHERE name = 'CnNSong';
UPDATE core_polity SET long_name = 'Later Jin' WHERE name = 'CnLrJin';
UPDATE core_polity SET long_name = 'Southern Song' WHERE name = 'CnSSong';
UPDATE core_polity SET long_name = 'Great Ming' WHERE name = 'CnMing*';
UPDATE core_polity SET long_name = 'Early Qing' WHERE name = 'CnQingE';
UPDATE core_polity SET long_name = 'Late Qing' WHERE name = 'CnQingL';
UPDATE core_polity SET long_name = 'Jenne-jeno I' WHERE name = 'MlJeJe1';
UPDATE core_polity SET long_name = 'Jenne-jeno II' WHERE name = 'MlJeJe2';
UPDATE core_polity SET long_name = 'Early Wagadu Empire' WHERE name = 'MrWagdE';
UPDATE core_polity SET long_name = 'Jenne-jeno III' WHERE name = 'MlJeJe3';
UPDATE core_polity SET long_name = 'Jenne-jeno IV' WHERE name = 'MlJeJe4';
UPDATE core_polity SET long_name = 'Songhai Empire - Askiya Dynasty' WHERE name = 'MlSong2';
UPDATE core_polity SET long_name = 'Saadi Sultanate' WHERE name = 'MaSaadi';
UPDATE core_polity SET long_name = 'Segou Kingdom' WHERE name = 'MlSegou';
UPDATE core_polity SET long_name = 'Bamana kingdom' WHERE name = 'MlBaman';
UPDATE core_polity SET long_name = 'Neguanje' WHERE name = 'CoNahua';
UPDATE core_polity SET long_name = 'Tairona' WHERE name = 'CoTairo';
UPDATE core_polity SET long_name = 'Early Xiongnu' WHERE name = 'MnXngnE';
UPDATE core_polity SET long_name = 'Xiongnu Imperial Confederation' WHERE name = 'MnXngnM';
UPDATE core_polity SET long_name = 'Late Xiongnu' WHERE name = 'MnXngnL';
UPDATE core_polity SET long_name = 'Xianbei Confederation' WHERE name = 'MnXianb';
UPDATE core_polity SET long_name = 'Shiwei' WHERE name = 'MnShiwe';
UPDATE core_polity SET long_name = 'Second Turk Khaganate' WHERE name = 'MnTurk2';
UPDATE core_polity SET long_name = 'Uigur Khaganate' WHERE name = 'MnUigur';
UPDATE core_polity SET long_name = 'Khitan 2' WHERE name = 'MnKhit';
UPDATE core_polity SET long_name = 'Early Mongols' WHERE name = 'MnMongE';
UPDATE core_polity SET long_name = 'Late Mongols' WHERE name = 'MnMongL';
UPDATE core_polity SET long_name = 'Zungharian Empire' WHERE name = 'MnZungh';
UPDATE core_polity SET long_name = 'Orokaiva - Pre-Colonial' WHERE name = 'PgOrokE';
UPDATE core_polity SET long_name = 'Orokaiva - Colonial' WHERE name = 'PgOrokL';
UPDATE core_polity SET long_name = 'Beaker Culture' WHERE name = 'FrBeakr';
UPDATE core_polity SET long_name = 'Atlantic Complex' WHERE name = 'FrAtlBA';
UPDATE core_polity SET long_name = 'Hallstatt A-B1' WHERE name = 'FrHallA';
UPDATE core_polity SET long_name = 'Hallstatt B2-3' WHERE name = 'FrHallB';
UPDATE core_polity SET long_name = 'Hallstatt C' WHERE name = 'FrHallC';
UPDATE core_polity SET long_name = 'Hallstatt D' WHERE name = 'FrHallD';
UPDATE core_polity SET long_name = 'La Tene A-B1' WHERE name = 'FrTeneA';
UPDATE core_polity SET long_name = 'La Tene B2-C1' WHERE name = 'FrTeneB';
UPDATE core_polity SET long_name = 'La Tene C2-D' WHERE name = 'FrTeneC';
UPDATE core_polity SET long_name = 'Proto-Carolingian' WHERE name = 'FrMervL';
UPDATE core_polity SET long_name = 'Proto-French Kingdom' WHERE name = 'FrCaptE';
UPDATE core_polity SET long_name = 'French Kingdom - Late Capetian' WHERE name = 'FrCaptL';
UPDATE core_polity SET long_name = 'French Kingdom - Early Valois' WHERE name = 'FrValoE';
UPDATE core_polity SET long_name = 'French Kingdom - Late Valois' WHERE name = 'FrValoL';
UPDATE core_polity SET long_name = 'French Kingdom - Early Bourbon' WHERE name = 'FrBurbE';
UPDATE core_polity SET long_name = 'French Kingdom - Late Bourbon' WHERE name = 'FrBurbL';
UPDATE core_polity SET long_name = 'Sarazm' WHERE name = 'TjSaraz';
UPDATE core_polity SET long_name = 'Andronovo' WHERE name = 'KzAndro';
UPDATE core_polity SET long_name = 'Koktepe I' WHERE name = 'UzKok01';
UPDATE core_polity SET long_name = 'Ancient Khwarazm' WHERE name = 'UzKhw01';
UPDATE core_polity SET long_name = 'Koktepe II' WHERE name = 'UzKok02';
UPDATE core_polity SET long_name = 'Greco-Bactrian Kingdom' WHERE name = 'AfGrBct';
UPDATE core_polity SET long_name = 'Tocharians' WHERE name = 'AfTochr';
UPDATE core_polity SET long_name = 'Sogdiana - City-States Period' WHERE name = 'UzSogdi';
UPDATE core_polity SET long_name = 'Samanid Empire' WHERE name = 'UzSamnd';
UPDATE core_polity SET long_name = 'Kara-Khanids' WHERE name = 'KgKarKh';
UPDATE core_polity SET long_name = 'Timurid Empire' WHERE name = 'UzTimur';
UPDATE core_polity SET long_name = 'Khanate of Bukhara' WHERE name = 'UzJanid';
UPDATE core_polity SET long_name = 'Hmong - Late Qing' WHERE name = 'CnHQngL';
UPDATE core_polity SET long_name = 'Hmong - Early Chinese' WHERE name = 'CnHChin';
UPDATE core_polity SET long_name = 'Southern Mesopotamia Neolithic' WHERE name = 'IqSoNeo';
UPDATE core_polity SET long_name = 'Ubaid' WHERE name = 'IqUbaid';
UPDATE core_polity SET long_name = 'Uruk' WHERE name = 'IqUruk*';
UPDATE core_polity SET long_name = 'Early Dynastic' WHERE name = 'IqEDyn*';
UPDATE core_polity SET long_name = 'Akkadian Empire' WHERE name = 'IqAkkad';
UPDATE core_polity SET long_name = 'Ur - Dynasty III' WHERE name = 'IqUrIII';
UPDATE core_polity SET long_name = 'Isin-Larsa' WHERE name = 'IqIsinL';
UPDATE core_polity SET long_name = 'Amorite Babylonia' WHERE name = 'IqBabAm';
UPDATE core_polity SET long_name = 'Kassite Babylonia' WHERE name = 'IqBabKs';
UPDATE core_polity SET long_name = 'Second Dynasty of Isin' WHERE name = 'IqIsin2';
UPDATE core_polity SET long_name = 'Bazi Dynasty' WHERE name = 'IqBazi*';
UPDATE core_polity SET long_name = 'Dynasty of E' WHERE name = 'IqDynE*';
UPDATE core_polity SET long_name = 'Parthian Empire II' WHERE name = 'IrPart2';
UPDATE core_polity SET long_name = 'Buyid Confederation' WHERE name = 'IrBuyid';
UPDATE core_polity SET long_name = 'Seljuk Empire' WHERE name = 'IrSeljq';
UPDATE core_polity SET long_name = 'Abbasid Caliphate II' WHERE name = 'IqAbbs2';
UPDATE core_polity SET long_name = 'Pre-Ceramic Period' WHERE name = 'IrPrCer';
UPDATE core_polity SET long_name = 'Formative Period' WHERE name = 'IrForma';
UPDATE core_polity SET long_name = 'Susiana - Muhammad Jaffar' WHERE name = 'IrArcha';
UPDATE core_polity SET long_name = 'Susiana A' WHERE name = 'IrKhzE*';
UPDATE core_polity SET long_name = 'Susiana B' WHERE name = 'IrKhzEM';
UPDATE core_polity SET long_name = 'Susiana - Early Ubaid' WHERE name = 'IrKhzM*';
UPDATE core_polity SET long_name = 'Susiana - Late Ubaid' WHERE name = 'IrKhzL*';
UPDATE core_polity SET long_name = 'Susa I' WHERE name = 'IrSusa1';
UPDATE core_polity SET long_name = 'Susa II' WHERE name = 'IrSusa2';
UPDATE core_polity SET long_name = 'Susa III' WHERE name = 'IrSusa3';
UPDATE core_polity SET long_name = 'Elam - Awan Dynasty I' WHERE name = 'IrAwanE';
UPDATE core_polity SET long_name = 'Elam - Shimashki Period' WHERE name = 'IrShima';
UPDATE core_polity SET long_name = 'Elam - Early Sukkalmah' WHERE name = 'IrSukkE';
UPDATE core_polity SET long_name = 'Elam - Late Sukkalmah' WHERE name = 'IrSukkL';
UPDATE core_polity SET long_name = 'Elam - Kidinuid Period' WHERE name = 'IrMElm1';
UPDATE core_polity SET long_name = 'Elam - Igihalkid Period' WHERE name = 'IrMElm2';
UPDATE core_polity SET long_name = 'Elam - Shutrukid Period' WHERE name = 'IrMElm3';
UPDATE core_polity SET long_name = 'Elam - Crisis Period' WHERE name = 'IrElmCP';
UPDATE core_polity SET long_name = 'Elam I' WHERE name = 'IrNElm1';
UPDATE core_polity SET long_name = 'Elam II' WHERE name = 'IrNElm2';
UPDATE core_polity SET long_name = 'Elam III' WHERE name = 'IrNElm3';
UPDATE core_polity SET long_name = 'Macedonian Empire' WHERE name = 'GrMaced';
UPDATE core_polity SET long_name = 'Elymais II' WHERE name = 'IrElym2';
UPDATE core_polity SET long_name = 'Ak Koyunlu' WHERE name = 'IrAkKoy';
UPDATE core_polity SET long_name = 'Qajar' WHERE name = 'IrQajar';
UPDATE core_polity SET long_name = 'Badarian' WHERE name = 'EgBadar';
UPDATE core_polity SET long_name = 'Naqada I' WHERE name = 'EgNaqa1';
UPDATE core_polity SET long_name = 'Naqada II' WHERE name = 'EgNaqa2';
UPDATE core_polity SET long_name = 'Egypt - Dynasty 0' WHERE name = 'EgNaqa3';
UPDATE core_polity SET long_name = 'Egypt - Dynasty I' WHERE name = 'EgDyn1*';
UPDATE core_polity SET long_name = 'Egypt - Dynasty II' WHERE name = 'EgDyn2*';
UPDATE core_polity SET long_name = 'Egypt - Classic Old Kingdom' WHERE name = 'EgOldK1';
UPDATE core_polity SET long_name = 'Egypt - Late Old Kingdom' WHERE name = 'EgOldK2';
UPDATE core_polity SET long_name = 'Egypt - Period of the Regions' WHERE name = 'EgRegns';
UPDATE core_polity SET long_name = 'Egypt - Middle Kingdom' WHERE name = 'EgMidKg';
UPDATE core_polity SET long_name = 'Egypt - Thebes-Hyksos Period' WHERE name = 'EgThebH';
UPDATE core_polity SET long_name = 'Egypt - New Kingdom Thutmosid Period' WHERE name = 'EgNKThu';
UPDATE core_polity SET long_name = 'Egypt - New Kingdom Ramesside Period' WHERE name = 'EgNKRam';
UPDATE core_polity SET long_name = 'Egypt - Thebes-Libyan Period' WHERE name = 'EgThebL';
UPDATE core_polity SET long_name = 'Egypt - Kushite Period' WHERE name = 'SdKusht';
UPDATE core_polity SET long_name = 'Egypt - Saite Period' WHERE name = 'EgSaite';
UPDATE core_polity SET long_name = 'Egypt - Inter-Occupation Period' WHERE name = 'EgIntOc';
UPDATE core_polity SET long_name = 'Egypt - Tulunid-Ikhshidid Period' WHERE name = 'EgTulIk';
UPDATE core_polity SET long_name = 'Ayyubid Sultanate' WHERE name = 'EgAyyub';
UPDATE core_polity SET long_name = 'Egypt - Mamluk Sultanate I' WHERE name = 'EgMamBh';
UPDATE core_polity SET long_name = 'Egypt - Mamluk Sultanate II' WHERE name = 'EgMamCP';
UPDATE core_polity SET long_name = 'Egypt - Mamluk Sultanate III' WHERE name = 'EgMamBu';
UPDATE core_polity SET long_name = 'Oaxaca - Tierras Largas' WHERE name = 'MxTieLa';
UPDATE core_polity SET long_name = 'Oaxaca - San Jose' WHERE name = 'MxSanGu';
UPDATE core_polity SET long_name = 'Oaxaca - Rosario' WHERE name = 'MxRosar';
UPDATE core_polity SET long_name = 'Early Monte Alban I' WHERE name = 'MxAlb1E';
UPDATE core_polity SET long_name = 'Monte Alban Late I' WHERE name = 'MxAlb1L';
UPDATE core_polity SET long_name = 'Monte Alban II' WHERE name = 'MxAlb2*';
UPDATE core_polity SET long_name = 'Monte Alban III' WHERE name = 'MxAlb3A';
UPDATE core_polity SET long_name = 'Monte Alban IIIB and IV' WHERE name = 'MxAlb3B';
UPDATE core_polity SET long_name = 'Monte Alban V Early Postclassic' WHERE name = 'MxAlbEP';
UPDATE core_polity SET long_name = 'Monte Alban V Late Postclassic' WHERE name = 'MxAlbLP';
UPDATE core_polity SET long_name = 'Monte Alban V' WHERE name = 'MxAlb5*';
UPDATE core_polity SET long_name = 'Early Nyoro' WHERE name = 'UgEarlyNyoro';
UPDATE core_polity SET long_name = 'Cwezi Dynasty' WHERE name = 'UgCwezi';
UPDATE core_polity SET long_name = 'Bito Dynasty' WHERE name = 'UgBito';
UPDATE core_polity SET long_name = 'Neolithic Yemen' WHERE name = 'YeNeoL*';
UPDATE core_polity SET long_name = 'Yemen - Late Bronze Age' WHERE name = 'YeLBA**';
UPDATE core_polity SET long_name = 'Sabaean Commonwealth' WHERE name = 'YeSabaC';
UPDATE core_polity SET long_name = 'Qatabanian Commonwealth' WHERE name = 'YeQatab';
UPDATE core_polity SET long_name = 'Kingdom of Saba and Dhu Raydan' WHERE name = 'YeSaRay';
UPDATE core_polity SET long_name = 'Yemen - Qasimid Dynasty' WHERE name = 'YeQasmi';
UPDATE core_polity SET long_name = 'Ottoman Empire Late Period' WHERE name = 'YeOttoL';
UPDATE core_polity SET long_name = 'Peiligang' WHERE name = 'CnPeili';
UPDATE core_polity SET long_name = 'Republic of Venice III' WHERE name = 'ItVenR3';
UPDATE core_polity SET long_name = 'Republic of Venice IV' WHERE name = 'ItVenR4';
UPDATE core_polity SET long_name = 'Five Dynasties Period' WHERE name = 'Cn5Dyna';
UPDATE core_polity SET long_name = 'Wei Kingdom' WHERE name = 'CnWei3*';
UPDATE core_polity SET long_name = 'Italian Kingdom Late Antiquity' WHERE name = 'ItRomLA';UPDATE core_polity SET new_name = 'mx_basin_of_mexico_1' WHERE name = 'MxArch*';
UPDATE core_polity SET new_name = 'mx_basin_of_mexico_2' WHERE name = 'MxInitl';
UPDATE core_polity SET new_name = 'mx_basin_of_mexico_3' WHERE name = 'MxFormE';
UPDATE core_polity SET new_name = 'mx_basin_of_mexico_4' WHERE name = 'MxFormM';
UPDATE core_polity SET new_name = 'mx_basin_of_mexico_5' WHERE name = 'MxFormL';
UPDATE core_polity SET new_name = 'mx_basin_of_mexico_6' WHERE name = 'MxFormT';
UPDATE core_polity SET new_name = 'mx_basin_of_mexico_7' WHERE name = 'MxClass';
UPDATE core_polity SET new_name = 'mx_basin_of_mexico_8' WHERE name = 'MxEpicl';
UPDATE core_polity SET new_name = 'mx_toltec' WHERE name = 'MxToltc';
UPDATE core_polity SET new_name = 'mx_basin_of_mexico_10' WHERE name = 'MxPostM';
UPDATE core_polity SET new_name = 'mx_aztec_emp' WHERE name = 'MxAztec';
UPDATE core_polity SET new_name = 'us_hawaii_1' WHERE name = 'Hawaii1';
UPDATE core_polity SET new_name = 'us_hawaii_2' WHERE name = 'Hawaii2';
UPDATE core_polity SET new_name = 'us_hawaii_3' WHERE name = 'Hawaii3';
UPDATE core_polity SET new_name = 'us_kamehameha_k' WHERE name = 'USKameh';
UPDATE core_polity SET new_name = 'us_hawaii_k' WHERE name = 'USHawai';
UPDATE core_polity SET new_name = 'us_woodland_1' WHERE name = 'USMisEW';
UPDATE core_polity SET new_name = 'us_woodland_2' WHERE name = 'USMisMW';
UPDATE core_polity SET new_name = 'us_woodland_3' WHERE name = 'USMisRo';
UPDATE core_polity SET new_name = 'us_woodland_4' WHERE name = 'USMisMu';
UPDATE core_polity SET new_name = 'us_woodland_5' WHERE name = 'USMisPa';
UPDATE core_polity SET new_name = 'us_emergent_mississippian_1' WHERE name = 'USMisSp';
UPDATE core_polity SET new_name = 'us_cahokia_3' WHERE name = 'USMisSd';
UPDATE core_polity SET new_name = 'us_oneota' WHERE name = 'USOneot';
UPDATE core_polity SET new_name = 'us_early_illinois_confederation' WHERE name = 'USIllin';
UPDATE core_polity SET new_name = 'us_late_illinois_confederation' WHERE name = 'USIllinL';
UPDATE core_polity SET new_name = 'us_cahokia_1' WHERE name = 'USCahoE';
UPDATE core_polity SET new_name = 'us_cahokia_2' WHERE name = 'USCahoL';
UPDATE core_polity SET new_name = 'us_emergent_mississippian_2' WHERE name = 'USMisME';
UPDATE core_polity SET new_name = 'kh_cambodia_ba' WHERE name = 'KhMekBA';
UPDATE core_polity SET new_name = 'kh_cambodia_ia' WHERE name = 'KhMekIA';
UPDATE core_polity SET new_name = 'kh_funan_1' WHERE name = 'KhFunaE';
UPDATE core_polity SET new_name = 'kh_funan_2' WHERE name = 'KhFunaL';
UPDATE core_polity SET new_name = 'kh_chenla' WHERE name = 'KhChenl';
UPDATE core_polity SET new_name = 'kh_angkor_1' WHERE name = 'KhAngkE';
UPDATE core_polity SET new_name = 'kh_angkor_2' WHERE name = 'KhAngkC';
UPDATE core_polity SET new_name = 'kh_angkor_3' WHERE name = 'KhAngkL';
UPDATE core_polity SET new_name = 'kh_khmer_k' WHERE name = 'KhCambd';
UPDATE core_polity SET new_name = 'th_ayutthaya' WHERE name = 'ThAyuth';
UPDATE core_polity SET new_name = 'th_rattanakosin' WHERE name = 'ThRattn';
UPDATE core_polity SET new_name = 'id_buni' WHERE name = 'IdCJBun';
UPDATE core_polity SET new_name = 'id_kalingga_k' WHERE name = 'IdKalin';
UPDATE core_polity SET new_name = 'id_medang_k' WHERE name = 'IdMedng';
UPDATE core_polity SET new_name = 'id_kediri_k' WHERE name = 'IdKedir';
UPDATE core_polity SET new_name = 'id_majapahit_k' WHERE name = 'IdMajap';
UPDATE core_polity SET new_name = 'eg_mataram_sultanate' WHERE name = 'IdMatrm';
UPDATE core_polity SET new_name = 'pa_monagrillo' WHERE name = 'PaMonag';
UPDATE core_polity SET new_name = 'pa_la_mula_sarigua' WHERE name = 'PaLaMul';
UPDATE core_polity SET new_name = 'pa_cocle_1' WHERE name = 'PaCocl1';
UPDATE core_polity SET new_name = 'pa_cocle_2' WHERE name = 'PaCocl2';
UPDATE core_polity SET new_name = 'pa_cocle_3' WHERE name = 'PaCocl3';
UPDATE core_polity SET new_name = 'fm_truk_1' WHERE name = 'FmTrukE';
UPDATE core_polity SET new_name = 'fm_truk_2' WHERE name = 'FmTrukL';
UPDATE core_polity SET new_name = 'gr_crete_nl' WHERE name = 'GrCrNeo';
UPDATE core_polity SET new_name = 'gr_crete_pre_palace' WHERE name = 'GrCrPre';
UPDATE core_polity SET new_name = 'gr_crete_old_palace' WHERE name = 'GrCrOPa';
UPDATE core_polity SET new_name = 'gr_crete_new_palace' WHERE name = 'GrCrNPa';
UPDATE core_polity SET new_name = 'gr_crete_mono_palace' WHERE name = 'GrCrMPa';
UPDATE core_polity SET new_name = 'gr_crete_post_palace_1' WHERE name = 'GrCrPPa';
UPDATE core_polity SET new_name = 'gr_crete_post_palace_2' WHERE name = 'GrCrFPa';
UPDATE core_polity SET new_name = 'gr_crete_geometric' WHERE name = 'GrCrGeo';
UPDATE core_polity SET new_name = 'gr_crete_archaic' WHERE name = 'GrCrArc';
UPDATE core_polity SET new_name = 'gr_crete_classical' WHERE name = 'GrCrCls';
UPDATE core_polity SET new_name = 'gr_crete_hellenistic' WHERE name = 'GrCrHel';
UPDATE core_polity SET new_name = 'it_roman_principate' WHERE name = 'ItRomPr';
UPDATE core_polity SET new_name = 'it_roman_dominate' WHERE name = 'TrRomDm';
UPDATE core_polity SET new_name = 'tr_east_roman_emp' WHERE name = 'TrERom*';
UPDATE core_polity SET new_name = 'tr_byzantine_emp_1' WHERE name = 'TrByzM1';
UPDATE core_polity SET new_name = 'gr_crete_emirate' WHERE name = 'GrCrEmr';
UPDATE core_polity SET new_name = 'tr_byzantine_emp_2' WHERE name = 'TrByzM2';
UPDATE core_polity SET new_name = 'tr_byzantine_emp_3' WHERE name = 'TrByzM3';
UPDATE core_polity SET new_name = 'pe_cuzco_1' WHERE name = 'PeCuzLF';
UPDATE core_polity SET new_name = 'pe_cuzco_2' WHERE name = 'PeCuzE1';
UPDATE core_polity SET new_name = 'pe_cuzco_3' WHERE name = 'PeCuzE2';
UPDATE core_polity SET new_name = 'pe_wari_emp' WHERE name = 'PeWari*';
UPDATE core_polity SET new_name = 'pe_cuzco_5' WHERE name = 'PeCuzL1';
UPDATE core_polity SET new_name = 'pe_cuzco_6' WHERE name = 'PeCuzL2';
UPDATE core_polity SET new_name = 'pe_inca_emp' WHERE name = 'PeInca*';
UPDATE core_polity SET new_name = 'es_spanish_emp_1' WHERE name = 'EsHabsb';
UPDATE core_polity SET new_name = 'in_deccan_nl' WHERE name = 'InDecNL';
UPDATE core_polity SET new_name = 'in_deccan_ia' WHERE name = 'InDecIA';
UPDATE core_polity SET new_name = 'in_mauryan_emp' WHERE name = 'InMaury';
UPDATE core_polity SET new_name = 'in_post_mauryan_k' WHERE name = 'InDecKg';
UPDATE core_polity SET new_name = 'in_satavahana_emp' WHERE name = 'InSataL';
UPDATE core_polity SET new_name = 'in_vakataka_k' WHERE name = 'InVakat';
UPDATE core_polity SET new_name = 'in_kadamba_emp' WHERE name = 'InKadam';
UPDATE core_polity SET new_name = 'in_badami_chalukya_emp' WHERE name = 'InChaBd';
UPDATE core_polity SET new_name = 'in_rashtrakuta_emp' WHERE name = 'InRasht';
UPDATE core_polity SET new_name = 'in_kalyani_chalukya_emp' WHERE name = 'InChaKl';
UPDATE core_polity SET new_name = 'in_hoysala_k' WHERE name = 'InHoysa';
UPDATE core_polity SET new_name = 'in_kampili_k' WHERE name = 'InKampi';
UPDATE core_polity SET new_name = 'in_vijayanagara_emp' WHERE name = 'InVijay';
UPDATE core_polity SET new_name = 'in_mughal_emp' WHERE name = 'InMugl*';
UPDATE core_polity SET new_name = 'gb_british_emp_1' WHERE name = 'GbEmpr2';
UPDATE core_polity SET new_name = 'us_proto_haudenosaunee' WHERE name = 'UsIroqP';
UPDATE core_polity SET new_name = 'us_haudenosaunee_1' WHERE name = 'UsIroqE';
UPDATE core_polity SET new_name = 'us_haudenosaunee_2' WHERE name = 'UsIroqL';
UPDATE core_polity SET new_name = 'il_canaan' WHERE name = 'IlCanaa';
UPDATE core_polity SET new_name = 'lb_kenaan' WHERE name = 'LbAcPho';
UPDATE core_polity SET new_name = 'il_yisrael' WHERE name = 'IlYisrl';
UPDATE core_polity SET new_name = 'iq_neo_assyrian_emp' WHERE name = 'IqNAssr';
UPDATE core_polity SET new_name = 'ir_achaemenid_emp' WHERE name = 'IrAchae';
UPDATE core_polity SET new_name = 'ir_seleucid_emp' WHERE name = 'IrSeleu';
UPDATE core_polity SET new_name = 'eg_ptolemaic_k_1' WHERE name = 'EgPtol1';
UPDATE core_polity SET new_name = 'il_judea' WHERE name = 'IlJudea';
UPDATE core_polity SET new_name = 'in_achik_1' WHERE name = 'InGaroE';
UPDATE core_polity SET new_name = 'in_achik_2' WHERE name = 'InGaroL';
UPDATE core_polity SET new_name = 'gh_akan' WHERE name = 'GhAshnE';
UPDATE core_polity SET new_name = 'gh_ashanti_emp' WHERE name = 'GhAshnL';
UPDATE core_polity SET new_name = 'is_icelandic_commonwealth' WHERE name = 'IsCommw';
UPDATE core_polity SET new_name = 'no_norway_k' WHERE name = 'NorKing';
UPDATE core_polity SET new_name = 'pk_kachi_enl' WHERE name = 'PkAcerN';
UPDATE core_polity SET new_name = 'pk_kachi_lnl' WHERE name = 'PkCeraN';
UPDATE core_polity SET new_name = 'pk_kachi_ca' WHERE name = 'PkChalc';
UPDATE core_polity SET new_name = 'pk_kachi_pre_urban' WHERE name = 'PkPreUr';
UPDATE core_polity SET new_name = 'pk_kachi_urban_1' WHERE name = 'PkUrbn1';
UPDATE core_polity SET new_name = 'pk_kachi_urban_2' WHERE name = 'PkUrbn2';
UPDATE core_polity SET new_name = 'pk_kachi_post_urban' WHERE name = 'PkPostU';
UPDATE core_polity SET new_name = 'pk_kachi_proto_historic' WHERE name = 'PkProto';
UPDATE core_polity SET new_name = 'ir_parthian_emp_1' WHERE name = 'IrPart1';
UPDATE core_polity SET new_name = 'pk_indo_greek_k' WHERE name = 'PkIndGr';
UPDATE core_polity SET new_name = 'af_kushan_emp' WHERE name = 'AfKushn';
UPDATE core_polity SET new_name = 'ir_sassanid_emp_1' WHERE name = 'IrSasn1';
UPDATE core_polity SET new_name = 'af_hephthalite_emp' WHERE name = 'AfHepht';
UPDATE core_polity SET new_name = 'ir_sassanid_emp_2' WHERE name = 'IrSasn2';
UPDATE core_polity SET new_name = 'sy_umayyad_cal' WHERE name = 'SyCalUm';
UPDATE core_polity SET new_name = 'iq_abbasid_cal_1' WHERE name = 'IqAbbs1';
UPDATE core_polity SET new_name = 'pk_sind_abbasid_fatimid' WHERE name = 'PkSind1';
UPDATE core_polity SET new_name = 'af_ghur_principality' WHERE name = 'AfGhurd';
UPDATE core_polity SET new_name = 'in_delhi_sultanate' WHERE name = 'InDelh*';
UPDATE core_polity SET new_name = 'pk_samma_dyn' WHERE name = 'PkSind2';
UPDATE core_polity SET new_name = 'af_durrani_emp' WHERE name = 'AfDurrn';
UPDATE core_polity SET new_name = 'jp_jomon_1' WHERE name = 'JpJomo1';
UPDATE core_polity SET new_name = 'jp_jomon_2' WHERE name = 'JpJomo2';
UPDATE core_polity SET new_name = 'jp_jomon_3' WHERE name = 'JpJomo3';
UPDATE core_polity SET new_name = 'jp_jomon_4' WHERE name = 'JpJomo4';
UPDATE core_polity SET new_name = 'jp_jomon_5' WHERE name = 'JpJomo5';
UPDATE core_polity SET new_name = 'jp_jomon_6' WHERE name = 'JpJomo6';
UPDATE core_polity SET new_name = 'jp_yayoi' WHERE name = 'JpYayoi';
UPDATE core_polity SET new_name = 'jp_kofun' WHERE name = 'JpKofun';
UPDATE core_polity SET new_name = 'jp_asuka' WHERE name = 'JpAsuka';
UPDATE core_polity SET new_name = 'jp_heian' WHERE name = 'JpHeian';
UPDATE core_polity SET new_name = 'jp_kamakura' WHERE name = 'JpKamak';
UPDATE core_polity SET new_name = 'jp_ashikaga' WHERE name = 'JpAshik';
UPDATE core_polity SET new_name = 'jp_sengoku_jidai' WHERE name = 'JpSengk';
UPDATE core_polity SET new_name = 'jp_azuchi_momoyama' WHERE name = 'JpAzMom';
UPDATE core_polity SET new_name = 'jp_tokugawa_shogunate' WHERE name = 'JpTokgw';
UPDATE core_polity SET new_name = 'id_iban_1' WHERE name = 'IdBrokE';
UPDATE core_polity SET new_name = 'id_iban_2' WHERE name = 'IdBrokL';
UPDATE core_polity SET new_name = 'tr_konya_enl' WHERE name = 'TrNeoER';
UPDATE core_polity SET new_name = 'tr_konya_mnl' WHERE name = 'TrNeoCR';
UPDATE core_polity SET new_name = 'tr_konya_lnl' WHERE name = 'TrNeoLT';
UPDATE core_polity SET new_name = 'tr_konya_eca' WHERE name = 'TrClcER';
UPDATE core_polity SET new_name = 'tr_konya_lca' WHERE name = 'TrClcLT';
UPDATE core_polity SET new_name = 'tr_konya_eba' WHERE name = 'TrBrzER';
UPDATE core_polity SET new_name = 'tr_central_anatolia_mba' WHERE name = 'TrBrzMD';
UPDATE core_polity SET new_name = 'tr_hatti_old_k' WHERE name = 'TrHatOK';
UPDATE core_polity SET new_name = 'tr_konya_lba' WHERE name = 'TrBrzL2';
UPDATE core_polity SET new_name = 'tr_hatti_new_k' WHERE name = 'TrHatNK';
UPDATE core_polity SET new_name = 'tr_neo_hittite_k' WHERE name = 'TrNHitt';
UPDATE core_polity SET new_name = 'tr_phrygia_k' WHERE name = 'TrPhryg';
UPDATE core_polity SET new_name = 'tr_tabal_k' WHERE name = 'TrTabal';
UPDATE core_polity SET new_name = 'tr_lydia_k' WHERE name = 'TrLydia';
UPDATE core_polity SET new_name = 'tr_lysimachus_k' WHERE name = 'TrLysim';
UPDATE core_polity SET new_name = 'tr_cappadocia_2' WHERE name = 'TrCappL';
UPDATE core_polity SET new_name = 'tr_rum_sultanate' WHERE name = 'TrRum**';
UPDATE core_polity SET new_name = 'ir_il_khanate' WHERE name = 'IrIlkhn';
UPDATE core_polity SET new_name = 'tr_ottoman_emirate' WHERE name = 'TrOttm1';
UPDATE core_polity SET new_name = 'tr_ottoman_emp_1' WHERE name = 'TrOttm2';
UPDATE core_polity SET new_name = 'tr_ottoman_emp_2' WHERE name = 'TrOttm3';
UPDATE core_polity SET new_name = 'tr_ottoman_emp_3' WHERE name = 'TrOttm4';
UPDATE core_polity SET new_name = 'tr_ottoman_emp_4' WHERE name = 'TrOttm5';
UPDATE core_polity SET new_name = 'it_latium_ca' WHERE name = 'ItLatCA';
UPDATE core_polity SET new_name = 'it_latium_ba' WHERE name = 'ItLatBA';
UPDATE core_polity SET new_name = 'it_latium_ia' WHERE name = 'ItLatIA';
UPDATE core_polity SET new_name = 'it_roman_k' WHERE name = 'ItRomRg';
UPDATE core_polity SET new_name = 'it_roman_rep_1' WHERE name = 'ItRomER';
UPDATE core_polity SET new_name = 'it_roman_rep_2' WHERE name = 'ItRomMR';
UPDATE core_polity SET new_name = 'it_roman_rep_3' WHERE name = 'ItRomLR';
UPDATE core_polity SET new_name = 'it_western_roman_emp' WHERE name = 'ItRomWe';
UPDATE core_polity SET new_name = 'it_ostrogoth_k' WHERE name = 'ItOstrg';
UPDATE core_polity SET new_name = 'it_ravenna_exarchate' WHERE name = 'ItRav**';
UPDATE core_polity SET new_name = 'it_st_peter_rep_1' WHERE name = 'ItStPet';
UPDATE core_polity SET new_name = 'it_st_peter_rep_2' WHERE name = 'ItPapEM';
UPDATE core_polity SET new_name = 'it_papal_state_1' WHERE name = 'ItPapHM';
UPDATE core_polity SET new_name = 'it_papal_state_2' WHERE name = 'ItPapRn';
UPDATE core_polity SET new_name = 'it_papal_state_3' WHERE name = 'ItPapM1';
UPDATE core_polity SET new_name = 'it_papal_state_4' WHERE name = 'ItPapM2';
UPDATE core_polity SET new_name = 'ru_sakha_early' WHERE name = 'RuYakuE';
UPDATE core_polity SET new_name = 'ru_sakha_late' WHERE name = 'RuYakuL';
UPDATE core_polity SET new_name = 'ec_shuar_1' WHERE name = 'EcJivaE';
UPDATE core_polity SET new_name = 'ec_shuar_2' WHERE name = 'EcJivaL';
UPDATE core_polity SET new_name = 'eg_new_k_1' WHERE name = 'EgNKThu';
UPDATE core_polity SET new_name = 'eg_new_k_2' WHERE name = 'EgNKRam';
UPDATE core_polity SET new_name = 'eg_thebes_libyan' WHERE name = 'EgThebL';
UPDATE core_polity SET new_name = 'tn_carthage_emp' WHERE name = 'TnCarth';
UPDATE core_polity SET new_name = 'sd_kush_k' WHERE name = 'SdKush';
UPDATE core_polity SET new_name = 'eg_saite' WHERE name = 'EgSaite';
UPDATE core_polity SET new_name = 'sd_meroe' WHERE name = 'Meroe';
UPDATE core_polity SET new_name = 'eg_inter_occupation' WHERE name = 'EgIntOc';
UPDATE core_polity SET new_name = 'dz_numidia' WHERE name = 'DzNumid';
UPDATE core_polity SET new_name = 'eg_ptolemaic_k_2' WHERE name = 'EgPtol2';
UPDATE core_polity SET new_name = 'et_aksum_emp_1' WHERE name = 'EtAksm1';
UPDATE core_polity SET new_name = 'ma_mauretania' WHERE name = 'MaKgMau';
UPDATE core_polity SET new_name = 'et_aksum_emp_2' WHERE name = 'EtAksm2';
UPDATE core_polity SET new_name = 'dz_vandal_k' WHERE name = 'DzVandal';
UPDATE core_polity SET new_name = 'sd_makuria_k_1' WHERE name = 'SdMakur1';
UPDATE core_polity SET new_name = 'et_aksum_emp_3' WHERE name = 'EtAksm3';
UPDATE core_polity SET new_name = 'sd_alodia' WHERE name = 'SdAlodia';
UPDATE core_polity SET new_name = 'sd_makuria_k_2' WHERE name = 'SdMakur2';
UPDATE core_polity SET new_name = 'mr_wagadu_2' WHERE name = 'MrWagdM';
UPDATE core_polity SET new_name = 'dz_tahert' WHERE name = 'DzTahrt';
UPDATE core_polity SET new_name = 'ma_idrisid_dyn' WHERE name = 'MaIdris';
UPDATE core_polity SET new_name = 'sd_makuria_k_3' WHERE name = 'SdMakur3';
UPDATE core_polity SET new_name = 'td_kanem' WHERE name = 'TdKanem';
UPDATE core_polity SET new_name = 'tn_fatimid_cal' WHERE name = 'TnFatim';
UPDATE core_polity SET new_name = 'tn_zirid_dyn' WHERE name = 'TnZirid';
UPDATE core_polity SET new_name = 'ma_almoravid_dyn' WHERE name = 'MaAlmor';
UPDATE core_polity SET new_name = 'mr_wagadu_3' WHERE name = 'MrWagdL';
UPDATE core_polity SET new_name = 'ma_almohad_emp' WHERE name = 'MaAlmoh';
UPDATE core_polity SET new_name = 'ib_banu_ghaniya' WHERE name = 'IbBnGhn';
UPDATE core_polity SET new_name = 'et_zagwe' WHERE name = 'EtZagwe';
UPDATE core_polity SET new_name = 'tn_hafsid_dyn' WHERE name = 'TnHafsid';
UPDATE core_polity SET new_name = 'ml_mali_emp' WHERE name = 'MlMali*';
UPDATE core_polity SET new_name = 'dz_tlemcen' WHERE name = 'DzTlmcn';
UPDATE core_polity SET new_name = 'dz_zayyanid_dyn' WHERE name = 'DzBrbZy';
UPDATE core_polity SET new_name = 'eg_mamluk_sultanate_1' WHERE name = 'EgMamBh';
UPDATE core_polity SET new_name = 'ma_marinid_dyn' WHERE name = 'MaMarinid';
UPDATE core_polity SET new_name = 'et_ethiopian_k' WHERE name = 'EtEthiK';
UPDATE core_polity SET new_name = 'my_malacca_sultanate' WHERE name = 'SoIfatS';
UPDATE core_polity SET new_name = 'eg_mamluk_sultanate_2' WHERE name = 'EgMamCP';
UPDATE core_polity SET new_name = 'ml_songhai_1' WHERE name = 'MlSong1';
UPDATE core_polity SET new_name = 'td_bornu_emp' WHERE name = 'TdBornu';
UPDATE core_polity SET new_name = 'eg_mamluk_sultanate_3' WHERE name = 'EgMamBu';
UPDATE core_polity SET new_name = 'ma_wattasid_dyn' WHERE name = 'MaWaFez';
UPDATE core_polity SET new_name = 'ao_kongo_2' WHERE name = 'AoKngo2';
UPDATE core_polity SET new_name = 'ml_songhai_2' WHERE name = 'MlSong2';
UPDATE core_polity SET new_name = 'cn_late_shang_dyn' WHERE name = 'CnShang';
UPDATE core_polity SET new_name = 'cn_western_zhou_dyn' WHERE name = 'CnWZhou';
UPDATE core_polity SET new_name = 'cn_jin_spring_and_autumn' WHERE name = 'CnJinSA';
UPDATE core_polity SET new_name = 'cn_chu_dyn_spring_and_autumn' WHERE name = 'CnChuSA';
UPDATE core_polity SET new_name = 'cn_wu_confederacy' WHERE name = 'CnWuCfd';
UPDATE core_polity SET new_name = 'cn_yue_dyn' WHERE name = 'CnYueKg';
UPDATE core_polity SET new_name = 'cn_chu_k_warring_states' WHERE name = 'CnChuWS';
UPDATE core_polity SET new_name = 'cn_qin_emp' WHERE name = 'CnImQin';
UPDATE core_polity SET new_name = 'cn_western_han_dyn' WHERE name = 'CnWHan*';
UPDATE core_polity SET new_name = 'kr_goguryeo_k' WHERE name = 'KrGogur';
UPDATE core_polity SET new_name = 'cn_eastern_han_dyn' WHERE name = 'CnEHan*';
UPDATE core_polity SET new_name = 'cn_western_jin_dyn' WHERE name = 'CnErJin';
UPDATE core_polity SET new_name = 'cn_eastern_jin_dyn' WHERE name = 'cn_eastern_jin_dyn';
UPDATE core_polity SET new_name = 'cn_later_yan_dyn' WHERE name = 'CnLrYan';
UPDATE core_polity SET new_name = 'cn_later_qin_dyn' WHERE name = 'CnLrQin';
UPDATE core_polity SET new_name = 'cn_northern_wei_dyn' WHERE name = 'CnNWei*';
UPDATE core_polity SET new_name = 'cn_souther_qi_dyn' WHERE name = 'CnSouQi';
UPDATE core_polity SET new_name = 'jp_asuka' WHERE name = 'JpAsuka';
UPDATE core_polity SET new_name = 'cn_sui_dyn' WHERE name = 'CnSui**';
UPDATE core_polity SET new_name = 'cn_tang_dyn_1' WHERE name = 'CnTangE';
UPDATE core_polity SET new_name = 'kr_balhae_k' WHERE name = 'KrBalha';
UPDATE core_polity SET new_name = 'jp_nara' WHERE name = 'JpNara*';
UPDATE core_polity SET new_name = 'cn_tang_dyn_2' WHERE name = 'CnTangL';
UPDATE core_polity SET new_name = 'jp_heian' WHERE name = 'JpHeian';
UPDATE core_polity SET new_name = 'kr_goryeo_k' WHERE name = 'KrGorye';
UPDATE core_polity SET new_name = 'cn_later_jin_dyn' WHERE name = 'CnLrJin';
UPDATE core_polity SET new_name = 'mn_mongol_emp' WHERE name = 'MnMngKh';
UPDATE core_polity SET new_name = 'cn_yuan_dyn' WHERE name = 'CnYuan*';
UPDATE core_polity SET new_name = 'cn_ming_dyn' WHERE name = 'CnMing*';
UPDATE core_polity SET new_name = 'kr_joseon' WHERE name = 'KrJoseon';
UPDATE core_polity SET new_name = 'jp_sengoku_jidai' WHERE name = 'JpSengk';
UPDATE core_polity SET new_name = 'ua_skythian_k_3' WHERE name = 'UaSky3K';
UPDATE core_polity SET new_name = 'mn_hunnu_2' WHERE name = 'MnXngnM';
UPDATE core_polity SET new_name = 'uz_kangju' WHERE name = 'UzKangj';
UPDATE core_polity SET new_name = 'mn_hunnu_3' WHERE name = 'MnXngnL';
UPDATE core_polity SET new_name = 'cn_loulan_shanshan_k' WHERE name = 'CnLouIn';
UPDATE core_polity SET new_name = 'cn_tuyuhun' WHERE name = 'CnTuyhn';
UPDATE core_polity SET new_name = 'kz_chionite' WHERE name = 'KzChion';
UPDATE core_polity SET new_name = 'mn_rouran' WHERE name = 'MnRourn';
UPDATE core_polity SET new_name = 'kz_yueban' WHERE name = 'KzYueba';
UPDATE core_polity SET new_name = 'hu_hunnic_emp' WHERE name = 'HuKHuns';
UPDATE core_polity SET new_name = 'af_kidarite_k' WHERE name = 'AfKidar';
UPDATE core_polity SET new_name = 'af_hephthalite_emp' WHERE name = 'AfHepht';
UPDATE core_polity SET new_name = 'kg_eastern_turk_khaganate' WHERE name = 'KgWTurk';
UPDATE core_polity SET new_name = 'mn_turk_khaganate_1' WHERE name = 'MnETurk';
UPDATE core_polity SET new_name = 'hu_avar_k' WHERE name = 'HuAvarK';
UPDATE core_polity SET new_name = 'ru_khazar_emp' WHERE name = 'RuKhazar';
UPDATE core_polity SET new_name = 'mn_uygur_khaganate' WHERE name = 'MnUigur';
UPDATE core_polity SET new_name = 'uz_samanid_emp' WHERE name = 'UzSamnd';
UPDATE core_polity SET new_name = 'mn_khitan' WHERE name = 'MnKhitn';
UPDATE core_polity SET new_name = 'kg_kara_khanid_dyn' WHERE name = 'KgKarKh';
UPDATE core_polity SET new_name = 'ge_georgia_k_2' WHERE name = 'GeGeoK2';
UPDATE core_polity SET new_name = 'cn_xixia' WHERE name = 'CnXixia';
UPDATE core_polity SET new_name = 'ru_ryazan_principality' WHERE name = 'RuRyazan';
UPDATE core_polity SET new_name = 'ua_russian_principate' WHERE name = 'UaRusPr';
UPDATE core_polity SET new_name = 'tm_kara_khitai_khanate' WHERE name = 'TmKarKh';
UPDATE core_polity SET new_name = 'tm_khwarezmid_emp' WHERE name = 'TmKhwrz';
UPDATE core_polity SET new_name = 'uz_chagatai_khanate' WHERE name = 'UzChagt';
UPDATE core_polity SET new_name = 'kz_oirat' WHERE name = 'KzOirat';
UPDATE core_polity SET new_name = 'ru_kazan_khanate' WHERE name = 'RuKazan';
UPDATE core_polity SET new_name = 'ru_crimean_khanate' WHERE name = 'RuCrKha';
UPDATE core_polity SET new_name = 'ru_sibir_khanate' WHERE name = 'RuSibir';
UPDATE core_polity SET new_name = 'uz_shaybanid_k' WHERE name = 'UzShayb';
UPDATE core_polity SET new_name = 'gb_anglo_saxon' WHERE name = 'GBEnglK';
UPDATE core_polity SET new_name = 'es_visigothic_k' WHERE name = 'EsVisigoth';
UPDATE core_polity SET new_name = 'fr_merovingian_emp_1' WHERE name = 'FrMervE';
UPDATE core_polity SET new_name = 'it_lombard_k' WHERE name = 'ItLombr';
UPDATE core_polity SET new_name = 'fr_merovingian_emp_2' WHERE name = 'FrMervM';
UPDATE core_polity SET new_name = 'fr_aquitania' WHERE name = 'FrAquit';
UPDATE core_polity SET new_name = 'bg_bulgaria_early' WHERE name = 'BgErBlg';
UPDATE core_polity SET new_name = 'fr_carolingian_emp_1' WHERE name = 'FrCarlE';
UPDATE core_polity SET new_name = 'es_cordoba_cal' WHERE name = 'EsCordo';
UPDATE core_polity SET new_name = 'fr_carolingian_emp_2' WHERE name = 'FrCarlL';
UPDATE core_polity SET new_name = 'bg_bulgaria_medieval' WHERE name = 'BgMdBlg';
UPDATE core_polity SET new_name = 'ru_novgorod_land' WHERE name = 'RuNovPr';
UPDATE core_polity SET new_name = 'ua_kievan_rus' WHERE name = 'UaKiev1';
UPDATE core_polity SET new_name = 'es_leon_k' WHERE name = 'EsLeon';
UPDATE core_polity SET new_name = 'de_holy_roman_emp_1' WHERE name = 'DeHRE';
UPDATE core_polity SET new_name = 'pl_polish_k' WHERE name = 'PlPoliK';
UPDATE core_polity SET new_name = 'bg_volga_k' WHERE name = 'BgVolga';
UPDATE core_polity SET new_name = 'hu_hungary_k' WHERE name = 'HuKingdom';
UPDATE core_polity SET new_name = 'es_aragon_k' WHERE name = 'EsAragn';
UPDATE core_polity SET new_name = 'es_castille_k' WHERE name = 'EsCastil';
UPDATE core_polity SET new_name = 'gb_england_norman' WHERE name = 'GBEnglK';
UPDATE core_polity SET new_name = 'ru_novgorod_rep' WHERE name = 'RuNovRp';
UPDATE core_polity SET new_name = 'gb_england_plantagenet' WHERE name = 'GBEnglK';
UPDATE core_polity SET new_name = 'ru_vladimir_suzdal' WHERE name = 'RuVldSz';
UPDATE core_polity SET new_name = 'it_sicily_k' WHERE name = 'ItSicilK';
UPDATE core_polity SET new_name = 'cz_bohemian_k_1' WHERE name = 'CzBohem';
UPDATE core_polity SET new_name = 'ua_galicia_volhynia_principality' WHERE name = 'UaGalicia';
UPDATE core_polity SET new_name = 'es_leon_castille' WHERE name = 'EsLeCas';
UPDATE core_polity SET new_name = 'pl_teutonic_order' WHERE name = 'PlTeuton';
UPDATE core_polity SET new_name = 'cz_bohemian_k_2' WHERE name = 'CzBohem';
UPDATE core_polity SET new_name = 'de_holy_roman_emp_2' WHERE name = 'DeHRE';
UPDATE core_polity SET new_name = 'fr_valois_k_1' WHERE name = 'FrValoE';
UPDATE core_polity SET new_name = 'pl_poland_lithuania_k' WHERE name = 'PlPoLit';
UPDATE core_polity SET new_name = 'sv_kalmar_union' WHERE name = 'SeKalma';
UPDATE core_polity SET new_name = 'cz_bohemian_k_3' WHERE name = 'CzBohem';
UPDATE core_polity SET new_name = 'ru_moskva_rurik_dyn' WHERE name = 'RuMoskva';
UPDATE core_polity SET new_name = 'gb_england_tudor_and_early_stuart' WHERE name = 'GBEnglK';
UPDATE core_polity SET new_name = 'sv_swedish_k' WHERE name = 'SeSwedi';
UPDATE core_polity SET new_name = 'de_holy_roman_emp_3' WHERE name = 'DeHRE';
UPDATE core_polity SET new_name = 'gb_british_emp_2' WHERE name = 'GbEmpr2';
UPDATE core_polity SET new_name = 'iq_babylonia_2' WHERE name = 'IqBabKs';
UPDATE core_polity SET new_name = 'sy_mitanni_k' WHERE name = 'SyMitan';
UPDATE core_polity SET new_name = 'tr_urartu_k' WHERE name = 'TrUrart';
UPDATE core_polity SET new_name = 'tr_neo_hittite_k' WHERE name = 'TrNHitt';
UPDATE core_polity SET new_name = 'tr_phrygian_k' WHERE name = 'TrPhryg';
UPDATE core_polity SET new_name = 'ir_median_emp' WHERE name = 'IrMedes';
UPDATE core_polity SET new_name = 'tr_lydian_k' WHERE name = 'TrLydia';
UPDATE core_polity SET new_name = 'iq_neo_babylonian_emp' WHERE name = 'IqNeoBb';
UPDATE core_polity SET new_name = 'ir_atropatene_k' WHERE name = 'IrAtrop';
UPDATE core_polity SET new_name = 'tr_lysimachus_k' WHERE name = 'TrLysim';
UPDATE core_polity SET new_name = 'ir_seleucid_emp' WHERE name = 'IrSeleu';
UPDATE core_polity SET new_name = 'jo_nabataean_k' WHERE name = 'JoNabat';
UPDATE core_polity SET new_name = 'tr_pergamon_k' WHERE name = 'TrPergm';
UPDATE core_polity SET new_name = 'af_greco_bactrian_k' WHERE name = 'AfGrBct';
UPDATE core_polity SET new_name = 'am_artaxiad_dyn' WHERE name = 'AmArtax';
UPDATE core_polity SET new_name = 'pk_indo_parthian_k' WHERE name = 'PkIndPR';
UPDATE core_polity SET new_name = 'ye_himyar_1' WHERE name = 'YeHmyr1';
UPDATE core_polity SET new_name = 'ye_himyar_2' WHERE name = 'YeHmyr2';
UPDATE core_polity SET new_name = 'iq_lakhmid_k' WHERE name = 'IqLakhm';
UPDATE core_polity SET new_name = 'jo_ghassanid_k' WHERE name = 'JoGhass';
UPDATE core_polity SET new_name = 'om_azd' WHERE name = 'OmAzd';
UPDATE core_polity SET new_name = 'sa_rashidun_dyn' WHERE name = 'SaRashd';
UPDATE core_polity SET new_name = 'sy_umayyad_cal' WHERE name = 'SyCalUm';
UPDATE core_polity SET new_name = 'ye_ziyad_dyn' WHERE name = 'YeZiyad';
UPDATE core_polity SET new_name = 'ir_saffarid_emp' WHERE name = 'IrSaffr';
UPDATE core_polity SET new_name = 'eg_thulunid_ikhshidid' WHERE name = 'EgTulIk';
UPDATE core_polity SET new_name = 'ir_buyid_confederation' WHERE name = 'IrBuyid';
UPDATE core_polity SET new_name = 'af_ghaznavid_emp' WHERE name = 'AfGhazn';
UPDATE core_polity SET new_name = 'af_ghurid_principality' WHERE name = 'AfGhurd';
UPDATE core_polity SET new_name = 'ir_seljuk_sultanate' WHERE name = 'IrSeljq';
UPDATE core_polity SET new_name = 'ye_warlords' WHERE name = 'YeWarLd';
UPDATE core_polity SET new_name = 'tr_byzantine_emp_3' WHERE name = 'TrByzM3';
UPDATE core_polity SET new_name = 'tr_rum_sultanate' WHERE name = 'TrRum**';
UPDATE core_polity SET new_name = 'om_nabhani_imamate' WHERE name = 'OmImamat';
UPDATE core_polity SET new_name = 'eg_ayyubid_sultanate' WHERE name = 'EgAyyub';
UPDATE core_polity SET new_name = 'ye_resulid_dyn' WHERE name = 'YeRasul';
UPDATE core_polity SET new_name = 'ir_il_khanate' WHERE name = 'IrIlkhn';
UPDATE core_polity SET new_name = 'ir_jayarid_khanate' WHERE name = 'IrJalay';
UPDATE core_polity SET new_name = 'uz_timurid_emp' WHERE name = 'UzTimur';
UPDATE core_polity SET new_name = 'ir_ak_koyunlu' WHERE name = 'IrAkkoy';
UPDATE core_polity SET new_name = 'ye_tahirid_dyn' WHERE name = 'YeTahir';
UPDATE core_polity SET new_name = 'ru_astrakhan_khanate' WHERE name = 'RuAstrakh';
UPDATE core_polity SET new_name = 'ir_safavid_emp' WHERE name = 'IrSafvd';
UPDATE core_polity SET new_name = 'cn_viet_baiyu_k' WHERE name = 'CnBaiyu';
UPDATE core_polity SET new_name = 'id_kalinga_k' WHERE name = 'IdKalin';
UPDATE core_polity SET new_name = 'cn_nanzhao_k' WHERE name = 'CnNanzh';
UPDATE core_polity SET new_name = 'id_srivijaya_emp' WHERE name = 'IdSrivi';
UPDATE core_polity SET new_name = 'cn_dali_k' WHERE name = 'CnDali';
UPDATE core_polity SET new_name = 'mm_bagan' WHERE name = 'MmPagan';
UPDATE core_polity SET new_name = 'th_sukhotai' WHERE name = 'ThSukho';
UPDATE core_polity SET new_name = 'la_lan_xang_k' WHERE name = 'LaLanXang';
UPDATE core_polity SET new_name = 'mm_ava_k' WHERE name = 'MmAva';
UPDATE core_polity SET new_name = 'my_malacca_sultanate' WHERE name = 'MySultM';
UPDATE core_polity SET new_name = 'id_mataram_k' WHERE name = 'IdMatrm';
UPDATE core_polity SET new_name = 'in_mahajanapada' WHERE name = 'InMahaJ';
UPDATE core_polity SET new_name = 'in_mauryan_emp' WHERE name = 'InMaury';
UPDATE core_polity SET new_name = 'in_sunga_emp' WHERE name = 'InSunga';
UPDATE core_polity SET new_name = 'pk_indo_greek_k' WHERE name = 'PkIndGr';
UPDATE core_polity SET new_name = 'pk_western_satraps' WHERE name = 'PkWSatrp';
UPDATE core_polity SET new_name = 'in_yaudheya_rep' WHERE name = 'InYaudh';
UPDATE core_polity SET new_name = 'in_gupta_emp' WHERE name = 'InGupta';
UPDATE core_polity SET new_name = 'in_kamarupa_k' WHERE name = 'InKamar';
UPDATE core_polity SET new_name = 'in_maghada_k' WHERE name = 'InMagad';
UPDATE core_polity SET new_name = 'in_maitraka_dyn' WHERE name = 'InMaitr';
UPDATE core_polity SET new_name = 'in_gurjara_pratihara_k' WHERE name = 'InGurPr';
UPDATE core_polity SET new_name = 'in_maukhari_dyn' WHERE name = 'InMaukh';
UPDATE core_polity SET new_name = 'cn_tibet_k' WHERE name = 'CnTibet';
UPDATE core_polity SET new_name = 'in_karkota_dyn' WHERE name = 'InKarkt';
UPDATE core_polity SET new_name = 'in_pala_emp' WHERE name = 'InPala';
UPDATE core_polity SET new_name = 'in_chola_emp' WHERE name = 'InChol*';
UPDATE core_polity SET new_name = 'in_utpala_dyn' WHERE name = 'InUtpal';
UPDATE core_polity SET new_name = 'in_solanki_dyn' WHERE name = 'InSolan';
UPDATE core_polity SET new_name = 'in_chandela_k' WHERE name = 'InChandel';
UPDATE core_polity SET new_name = 'in_chauhana_dyn' WHERE name = 'InChauh';
UPDATE core_polity SET new_name = 'in_paramara_dyn' WHERE name = 'InParam';
UPDATE core_polity SET new_name = 'in_lohara_dyn' WHERE name = 'InLohar';
UPDATE core_polity SET new_name = 'in_ganga_k' WHERE name = 'InGanga';
UPDATE core_polity SET new_name = 'in_gahadavala_dyn' WHERE name = 'InGhdvl';
UPDATE core_polity SET new_name = 'in_kalachuri_emp' WHERE name = 'InKalch';
UPDATE core_polity SET new_name = 'in_kakatiya_dyn' WHERE name = 'InKakat';
UPDATE core_polity SET new_name = 'in_yadava_dyn' WHERE name = 'InYadav';
UPDATE core_polity SET new_name = 'bd_bengal_sultanate' WHERE name = 'BdBengl';
UPDATE core_polity SET new_name = 'in_kashmiri_sultanate' WHERE name = 'InKashm';
UPDATE core_polity SET new_name = 'in_bahmani_sultanate' WHERE name = 'InBahma';
UPDATE core_polity SET new_name = 'in_sharqi_dyn' WHERE name = 'InSharq';
UPDATE core_polity SET new_name = 'in_bijapur_sultanate' WHERE name = 'InBijap';
UPDATE core_polity SET new_name = 'in_ganga_nl' WHERE name = 'InGangN';
UPDATE core_polity SET new_name = 'in_ganga_ca' WHERE name = 'InGangC';
UPDATE core_polity SET new_name = 'in_mahajanapada' WHERE name = 'InMahaJ';
UPDATE core_polity SET new_name = 'in_sunga_emp' WHERE name = 'InSunga';
UPDATE core_polity SET new_name = 'in_ayodhya_k' WHERE name = 'InAyodE';
UPDATE core_polity SET new_name = 'in_maghada_k' WHERE name = 'InMagad';
UPDATE core_polity SET new_name = 'in_kanauj' WHERE name = 'InKanau';
UPDATE core_polity SET new_name = 'in_gurjar' WHERE name = 'InGurjr';
UPDATE core_polity SET new_name = 'cn_yangshao' WHERE name = 'CnYngsh';
UPDATE core_polity SET new_name = 'cn_longshan' WHERE name = 'CnLngsh';
UPDATE core_polity SET new_name = 'cn_erlitou' WHERE name = 'CnErlit';
UPDATE core_polity SET new_name = 'cn_erligang' WHERE name = 'CnErlig';
UPDATE core_polity SET new_name = 'cn_late_shang_dyn' WHERE name = 'CnShang';
UPDATE core_polity SET new_name = 'cn_western_zhou_dyn' WHERE name = 'CnWZhou';
UPDATE core_polity SET new_name = 'cn_jin_dyn_spring_and_autumn' WHERE name = 'CnJinSA';
UPDATE core_polity SET new_name = 'cn_eastern_zhou_warring_states' WHERE name = 'CnZhuWS';
UPDATE core_polity SET new_name = 'cn_wei_dyn_warring_states' WHERE name = 'CnWeiWS';
UPDATE core_polity SET new_name = 'cn_western_jin_dyn' WHERE name = 'CnErJin';
UPDATE core_polity SET new_name = 'cn_northern_wei_dyn' WHERE name = 'CnNWei*';
UPDATE core_polity SET new_name = 'cn_northern_song_dyn' WHERE name = 'CnNSong';
UPDATE core_polity SET new_name = 'cn_later_jin_dyn' WHERE name = 'CnLrJin';
UPDATE core_polity SET new_name = 'cn_southern_song_dyn' WHERE name = 'CnSSong';
UPDATE core_polity SET new_name = 'cn_ming_dyn' WHERE name = 'CnMing*';
UPDATE core_polity SET new_name = 'cn_qing_dyn_1' WHERE name = 'CnQingE';
UPDATE core_polity SET new_name = 'cn_qing_dyn_2' WHERE name = 'CnQingL';
UPDATE core_polity SET new_name = 'ml_jenne_jeno_1' WHERE name = 'MlJeJe1';
UPDATE core_polity SET new_name = 'ml_jenne_jeno_2' WHERE name = 'MlJeJe2';
UPDATE core_polity SET new_name = 'mr_wagadu_1' WHERE name = 'MrWagdE';
UPDATE core_polity SET new_name = 'ml_jenne_jeno_3' WHERE name = 'MlJeJe3';
UPDATE core_polity SET new_name = 'ml_jenne_jeno_4' WHERE name = 'MlJeJe4';
UPDATE core_polity SET new_name = 'ml_songhai_2' WHERE name = 'MlSong2';
UPDATE core_polity SET new_name = 'ma_saadi_sultanate' WHERE name = 'MaSaadi';
UPDATE core_polity SET new_name = 'ml_segou_k' WHERE name = 'MlSegou';
UPDATE core_polity SET new_name = 'ml_bamana_k' WHERE name = 'MlBaman';
UPDATE core_polity SET new_name = 'co_neguanje' WHERE name = 'CoNahua';
UPDATE core_polity SET new_name = 'co_tairona' WHERE name = 'CoTairo';
UPDATE core_polity SET new_name = 'mn_hunnu_early' WHERE name = 'MnXngnE';
UPDATE core_polity SET new_name = 'mn_hunnu_emp' WHERE name = 'MnXngnM';
UPDATE core_polity SET new_name = 'mn_hunnu_late' WHERE name = 'MnXngnL';
UPDATE core_polity SET new_name = 'mn_xianbei' WHERE name = 'MnXianb';
UPDATE core_polity SET new_name = 'mn_shiwei' WHERE name = 'MnShiwe';
UPDATE core_polity SET new_name = 'mn_turk_khaganate_2' WHERE name = 'MnTurk2';
UPDATE core_polity SET new_name = 'mn_uygur_khaganate' WHERE name = 'MnUigur';
UPDATE core_polity SET new_name = 'mn_khitan_2' WHERE name = 'MnKhit';
UPDATE core_polity SET new_name = 'mn_mongol_early' WHERE name = 'MnMongE';
UPDATE core_polity SET new_name = 'mn_mongol_late' WHERE name = 'MnMongL';
UPDATE core_polity SET new_name = 'mn_zungharian_emp' WHERE name = 'MnZungh';
UPDATE core_polity SET new_name = 'pg_orokaiva_pre_colonial' WHERE name = 'PgOrokE';
UPDATE core_polity SET new_name = 'pg_orokaiva_colonial' WHERE name = 'PgOrokL';
UPDATE core_polity SET new_name = 'fr_beaker_eba' WHERE name = 'FrBeakr';
UPDATE core_polity SET new_name = 'fr_atlantic_complex' WHERE name = 'FrAtlBA';
UPDATE core_polity SET new_name = 'fr_hallstatt_a_b1' WHERE name = 'FrHallA';
UPDATE core_polity SET new_name = 'fr_hallstatt_b2_3' WHERE name = 'FrHallB';
UPDATE core_polity SET new_name = 'fr_hallstatt_c' WHERE name = 'FrHallC';
UPDATE core_polity SET new_name = 'fr_hallstatt_d' WHERE name = 'FrHallD';
UPDATE core_polity SET new_name = 'fr_la_tene_a_b1' WHERE name = 'FrTeneA';
UPDATE core_polity SET new_name = 'fr_la_tene_b2_c1' WHERE name = 'FrTeneB';
UPDATE core_polity SET new_name = 'fr_la_tene_c2_d' WHERE name = 'FrTeneC';
UPDATE core_polity SET new_name = 'fr_merovingian_emp_3' WHERE name = 'FrMervL';
UPDATE core_polity SET new_name = 'fr_capetian_k_1' WHERE name = 'FrCaptE';
UPDATE core_polity SET new_name = 'fr_capetian_k_2' WHERE name = 'FrCaptL';
UPDATE core_polity SET new_name = 'fr_valois_k_1' WHERE name = 'FrValoE';
UPDATE core_polity SET new_name = 'fr_valois_k_2' WHERE name = 'FrValoL';
UPDATE core_polity SET new_name = 'fr_bourbon_k_1' WHERE name = 'FrBurbE';
UPDATE core_polity SET new_name = 'fr_bourbon_k_2' WHERE name = 'FrBurbL';
UPDATE core_polity SET new_name = 'tj_sarasm' WHERE name = 'TjSaraz';
UPDATE core_polity SET new_name = 'kz_andronovo' WHERE name = 'KzAndro';
UPDATE core_polity SET new_name = 'uz_koktepe_1' WHERE name = 'UzKok01';
UPDATE core_polity SET new_name = 'uz_khwarasm_1' WHERE name = 'UzKhw01';
UPDATE core_polity SET new_name = 'uz_koktepe_2' WHERE name = 'UzKok02';
UPDATE core_polity SET new_name = 'af_greco_bactrian_k' WHERE name = 'AfGrBct';
UPDATE core_polity SET new_name = 'af_tocharian' WHERE name = 'AfTochr';
UPDATE core_polity SET new_name = 'uz_sogdiana_city_states' WHERE name = 'UzSogdi';
UPDATE core_polity SET new_name = 'uz_samanid_emp' WHERE name = 'UzSamnd';
UPDATE core_polity SET new_name = 'kg_kara_khanid_dyn' WHERE name = 'KgKarKh';
UPDATE core_polity SET new_name = 'uz_timurid_emp' WHERE name = 'UzTimur';
UPDATE core_polity SET new_name = 'uz_janid_dyn' WHERE name = 'UzJanid';
UPDATE core_polity SET new_name = 'cn_hmong_1' WHERE name = 'CnHQngL';
UPDATE core_polity SET new_name = 'cn_hmong_2' WHERE name = 'CnHChin';
UPDATE core_polity SET new_name = 'iq_so_mesopotamia_nl' WHERE name = 'IqSoNeo';
UPDATE core_polity SET new_name = 'iq_ubaid' WHERE name = 'IqUbaid';
UPDATE core_polity SET new_name = 'iq_uruk' WHERE name = 'IqUruk*';
UPDATE core_polity SET new_name = 'iq_early_dynastic' WHERE name = 'IqEDyn*';
UPDATE core_polity SET new_name = 'iq_akkad_emp' WHERE name = 'IqAkkad';
UPDATE core_polity SET new_name = 'iq_ur_dyn_3' WHERE name = 'IqUrIII';
UPDATE core_polity SET new_name = 'iq_isin_larsa' WHERE name = 'IqIsinL';
UPDATE core_polity SET new_name = 'iq_babylonia_1' WHERE name = 'IqBabAm';
UPDATE core_polity SET new_name = 'iq_babylonia_2' WHERE name = 'IqBabKs';
UPDATE core_polity SET new_name = 'iq_isin_dynasty2' WHERE name = 'IqIsin2';
UPDATE core_polity SET new_name = 'iq_bazi_dyn' WHERE name = 'IqBazi*';
UPDATE core_polity SET new_name = 'iq_dynasty_e' WHERE name = 'IqDynE*';
UPDATE core_polity SET new_name = 'iq_parthian_emp_2' WHERE name = 'IrPart2';
UPDATE core_polity SET new_name = 'ir_buyid_confederation' WHERE name = 'IrBuyid';
UPDATE core_polity SET new_name = 'ir_seljuk_emp' WHERE name = 'IrSeljq';
UPDATE core_polity SET new_name = 'iq_abbasid_cal_2' WHERE name = 'IqAbbs2';
UPDATE core_polity SET new_name = 'ir_susiana_pre_ceramic' WHERE name = 'IrPrCer';
UPDATE core_polity SET new_name = 'ir_susiana_formative' WHERE name = 'IrForma';
UPDATE core_polity SET new_name = 'ir_susiana_archaic' WHERE name = 'IrArcha';
UPDATE core_polity SET new_name = 'ir_susiana_a' WHERE name = 'IrKhzE*';
UPDATE core_polity SET new_name = 'ir_susiana_b' WHERE name = 'IrKhzEM';
UPDATE core_polity SET new_name = 'ir_susiana_ubaid_1' WHERE name = 'IrKhzM*';
UPDATE core_polity SET new_name = 'ir_susiana_ubaid_2' WHERE name = 'IrKhzL*';
UPDATE core_polity SET new_name = 'ir_susa_1' WHERE name = 'IrSusa1';
UPDATE core_polity SET new_name = 'ir_susa_2' WHERE name = 'IrSusa2';
UPDATE core_polity SET new_name = 'ir_susa_3' WHERE name = 'IrSusa3';
UPDATE core_polity SET new_name = 'ir_elam_1' WHERE name = 'IrAwanE';
UPDATE core_polity SET new_name = 'ir_elam_2' WHERE name = 'IrShima';
UPDATE core_polity SET new_name = 'ir_elam_3' WHERE name = 'IrSukkE';
UPDATE core_polity SET new_name = 'ir_elam_4' WHERE name = 'IrSukkL';
UPDATE core_polity SET new_name = 'ir_elam_5' WHERE name = 'IrMElm1';
UPDATE core_polity SET new_name = 'ir_elam_6' WHERE name = 'IrMElm2';
UPDATE core_polity SET new_name = 'ir_elam_7' WHERE name = 'IrMElm3';
UPDATE core_polity SET new_name = 'ir_elam_8' WHERE name = 'IrElmCP';
UPDATE core_polity SET new_name = 'ir_neo_elam_1' WHERE name = 'IrNElm1';
UPDATE core_polity SET new_name = 'ir_neo_elam_2' WHERE name = 'IrNElm2';
UPDATE core_polity SET new_name = 'ir_neo_elam_3' WHERE name = 'IrNElm3';
UPDATE core_polity SET new_name = 'gr_macedonian_emp' WHERE name = 'GrMaced';
UPDATE core_polity SET new_name = 'it_elymais_2' WHERE name = 'IrElym2';
UPDATE core_polity SET new_name = 'ir_ak_koynlu' WHERE name = 'IrAkKoy';
UPDATE core_polity SET new_name = 'ir_qajar_dyn' WHERE name = 'IrQajar';
UPDATE core_polity SET new_name = 'eg_badarian' WHERE name = 'EgBadar';
UPDATE core_polity SET new_name = 'eg_naqada_1' WHERE name = 'EgNaqa1';
UPDATE core_polity SET new_name = 'eg_naqada_2' WHERE name = 'EgNaqa2';
UPDATE core_polity SET new_name = 'eg_naqada_3' WHERE name = 'EgNaqa3';
UPDATE core_polity SET new_name = 'eg_dynasty_1' WHERE name = 'EgDyn1*';
UPDATE core_polity SET new_name = 'eg_dynasty_2' WHERE name = 'EgDyn2*';
UPDATE core_polity SET new_name = 'eg_old_k_1' WHERE name = 'EgOldK1';
UPDATE core_polity SET new_name = 'eg_old_k_2' WHERE name = 'EgOldK2';
UPDATE core_polity SET new_name = 'eg_regions' WHERE name = 'EgRegns';
UPDATE core_polity SET new_name = 'eg_middle_k' WHERE name = 'EgMidKg';
UPDATE core_polity SET new_name = 'eg_thebes_hyksos' WHERE name = 'EgThebH';
UPDATE core_polity SET new_name = 'eg_new_k_1' WHERE name = 'EgNKThu';
UPDATE core_polity SET new_name = 'eg_new_k_2' WHERE name = 'EgNKRam';
UPDATE core_polity SET new_name = 'eg_thebes_libyan' WHERE name = 'EgThebL';
UPDATE core_polity SET new_name = 'eg_kushite' WHERE name = 'SdKusht';
UPDATE core_polity SET new_name = 'eg_saite' WHERE name = 'EgSaite';
UPDATE core_polity SET new_name = 'eg_inter_occupation' WHERE name = 'EgIntOc';
UPDATE core_polity SET new_name = 'eg_thulunid_ikhshidid' WHERE name = 'EgTulIk';
UPDATE core_polity SET new_name = 'eg_ayyubid_sultanate' WHERE name = 'EgAyyub';
UPDATE core_polity SET new_name = 'eg_mamluk_sultanate_1' WHERE name = 'EgMamBh';
UPDATE core_polity SET new_name = 'eg_mamluk_sultanate_2' WHERE name = 'EgMamCP';
UPDATE core_polity SET new_name = 'eg_mamluk_sultanate_3' WHERE name = 'EgMamBu';
UPDATE core_polity SET new_name = 'mx_tierras_largas' WHERE name = 'MxTieLa';
UPDATE core_polity SET new_name = 'mx_san_jose' WHERE name = 'MxSanGu';
UPDATE core_polity SET new_name = 'mx_rosario' WHERE name = 'MxRosar';
UPDATE core_polity SET new_name = 'mx_monte_alban_1_early' WHERE name = 'MxAlb1E';
UPDATE core_polity SET new_name = 'mx_monte_alban_1_late' WHERE name = 'MxAlb1L';
UPDATE core_polity SET new_name = 'mx_monte_alban_2' WHERE name = 'MxAlb2*';
UPDATE core_polity SET new_name = 'mx_monte_alban_3_a' WHERE name = 'MxAlb3A';
UPDATE core_polity SET new_name = 'mx_monte_alban_3_b_4' WHERE name = 'MxAlb3B';
UPDATE core_polity SET new_name = 'mx_monte_alban_5_a' WHERE name = 'MxAlbEP';
UPDATE core_polity SET new_name = 'mx_monte_alban_5_b' WHERE name = 'MxAlbLP';
UPDATE core_polity SET new_name = 'ug_early_nyoro' WHERE name = 'UgEarlyNyoro';
UPDATE core_polity SET new_name = 'ug_cwezi_dyn' WHERE name = 'UgCwezi';
UPDATE core_polity SET new_name = 'ug_bito_dyn' WHERE name = 'UgBito';
UPDATE core_polity SET new_name = 'ye_yemen_lnl' WHERE name = 'YeNeoL*';
UPDATE core_polity SET new_name = 'ye_yemen_lba' WHERE name = 'YeLBA**';
UPDATE core_polity SET new_name = 'ye_sabaen_commonwealth' WHERE name = 'YeSabaC';
UPDATE core_polity SET new_name = 'ye_qatabanian_commonwealth' WHERE name = 'YeQatab';
UPDATE core_polity SET new_name = 'ye_saba_k' WHERE name = 'YeSaRay';
UPDATE core_polity SET new_name = 'ye_qasimid_dyn' WHERE name = 'YeQasmi';
UPDATE core_polity SET new_name = 'tr_ottoman_emp_4' WHERE name = 'YeOttoL';
UPDATE core_polity SET new_name = 'cn_5dynasty' WHERE name = 'Cn5Dyna';
UPDATE core_polity SET new_name = 'cn_wei_k' WHERE name = 'CnWei3*';
UPDATE core_polity SET new_name = 'it_italy_k' WHERE name = 'ItRomLA';