UPDATE core_polity SET world_region = 'Europe' WHERE name = 'ItLatCA';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'ItLatBA';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'ItLatIA';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'ItRomRg';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'ItRomER';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'ItRomMR';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'ItRomLR';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'ItRomPr';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'TrRomDm';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'ItRomWe';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'ItOstrg';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'ItRav**';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'ItStPet';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'ItPapEM';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'ItPapHM';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'ItPapRn';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'ItPapM1';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'ItPapM2';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'FrBeakr';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'FrAtlBA';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'FrHallA';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'FrHallB';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'FrHallC';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'FrHallD';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'FrTeneA';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'FrTeneB';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'FrTeneC';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'TrERom*';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'FrMervE';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'FrMervM';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'FrMervL';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'FrCarlE';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'FrCarlL';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'FrCaptE';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'FrCaptL';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'FrValoE';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'FrValoL';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'FrBurbE';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'FrBurbL';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'IsCommw';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'NorKing';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'GrCrNeo';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'GrCrPre';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'GrCrOPa';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'GrCrNPa';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'GrCrMPa';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'GrCrPPa';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'GrCrFPa';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'GrCrGeo';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'GrCrArc';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'GrCrCls';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'GrCrHel';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'TrERom*';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'TrByzM1';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'GrCrEmr';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'TrByzM2';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'TrByzM3';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'ItVenR3';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'ItVenR4';
UPDATE core_polity SET world_region = 'Europe' WHERE name = 'TrOttm4';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'EgBadar';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'EgNaqa1';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'EgNaqa2';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'EgNaqa3';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'EgDyn1*';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'EgDyn2*';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'EgOldK1';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'EgOldK2';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'EgRegns';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'EgMidKg';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'EgThebH';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'EgNKThu';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'EgNKRam';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'EgThebL';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'SdKusht';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'EgSaite';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'IrAchae';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'EgIntOc';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'EgPtol1';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'EgPtol2';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'ItRomPr';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'TrRomDm';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'TrERom*';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'SyCalUm';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'IqAbbs1';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'EgTulIk';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'TnFatim';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'EgAyyub';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'EgMamBh';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'EgMamCP';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'EgMamBu';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'TrOttm3';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'TrOttm4';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'MlJeJe1';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'MlJeJe2';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'MlJeJe3';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'MlJeJe4';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'MrWagdM';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'MrWagdL';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'MlMali*';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'MlSong2';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'MaSaadi';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'MlSegou';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'MlBaman';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'GhAshnE';
UPDATE core_polity SET world_region = 'Africa' WHERE name = 'GhAshnL';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IqSoNeo';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IqUbaid';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IqUruk*';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IqEDyn*';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IqAkkad';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IqUrIII';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IqIsinL';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IqBabAm';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IqBabKs';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IqIsin2';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IqBazi*';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IqDynE*';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IqNAssr';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IqNeoBb';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IrAchae';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IrSeleu';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IrPart1';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IrPart2';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IrSasn1';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IrSasn2';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'SyCalUm';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IqAbbs1';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IrBuyid';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IrSeljq';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IqAbbs2';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IrIlkhn';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'UzTimur';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IrSafvd';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'TrOttm3';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'TrOttm4';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IrPrCer';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IrForma';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IrArcha';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IrKhzE*';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IrKhzEM';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IrKhzM*';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IrKhzL*';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IrSusa1';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IrSusa2';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IrSusa3';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IrAwanE';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IrShima';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IrSukkE';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IrSukkL';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IrMElm1';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IrMElm2';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IrMElm3';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IrElmCP';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IrNElm1';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IrNElm2';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IrNElm3';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IrElym2';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IrAkKoy';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IrQajar';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IlCanaa';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'LbAcPho';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IlYisrl';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'EgPtol1';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'IlJudea';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'TrNeoER';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'TrNeoCR';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'TrNeoLT';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'TrClcER';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'TrClcLT';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'TrBrzER';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'TrBrzMD';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'TrHatOK';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'TrBrzL2';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'TrHatNK';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'TrNHitt';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'TrTabal';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'TrPhryg';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'TrLydia';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'TrLysim';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'TrCappL';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'ItRomPr';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'TrRomDm';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'TrByzM1';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'TrByzM2';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'TrRum**';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'TrOttm1';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'TrOttm2';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'YeNeoL*';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'YeLBA**';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'YeSabaC';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'YeQatab';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'YeSaRay';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'EtAksm1';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'YeHmyr1';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'YeHmyr2';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'YeZiyad';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'YeWarLd';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'EgAyyub';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'YeRasul';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'YeTahir';
UPDATE core_polity SET world_region = 'Southwest Asia' WHERE name = 'YeQasmi';
UPDATE core_polity SET world_region = 'Central Eurasia' WHERE name = 'TjSaraz';
UPDATE core_polity SET world_region = 'Central Eurasia' WHERE name = 'KzAndro';
UPDATE core_polity SET world_region = 'Central Eurasia' WHERE name = 'UzKok01';
UPDATE core_polity SET world_region = 'Central Eurasia' WHERE name = 'UzKhw01';
UPDATE core_polity SET world_region = 'Central Eurasia' WHERE name = 'UzKok02';
UPDATE core_polity SET world_region = 'Central Eurasia' WHERE name = 'IrAchae';
UPDATE core_polity SET world_region = 'Central Eurasia' WHERE name = 'IrSeleu';
UPDATE core_polity SET world_region = 'Central Eurasia' WHERE name = 'AfGrBct';
UPDATE core_polity SET world_region = 'Central Eurasia' WHERE name = 'AfTochr';
UPDATE core_polity SET world_region = 'Central Eurasia' WHERE name = 'AfKushn';
UPDATE core_polity SET world_region = 'Central Eurasia' WHERE name = 'IrSasn1';
UPDATE core_polity SET world_region = 'Central Eurasia' WHERE name = 'AfKidar';
UPDATE core_polity SET world_region = 'Central Eurasia' WHERE name = 'AfHepht';
UPDATE core_polity SET world_region = 'Central Eurasia' WHERE name = 'KgWTurk';
UPDATE core_polity SET world_region = 'Central Eurasia' WHERE name = 'UzSogdi';
UPDATE core_polity SET world_region = 'Central Eurasia' WHERE name = 'IqAbbs1';
UPDATE core_polity SET world_region = 'Central Eurasia' WHERE name = 'UzSamnd';
UPDATE core_polity SET world_region = 'Central Eurasia' WHERE name = 'KgKarKh';
UPDATE core_polity SET world_region = 'Central Eurasia' WHERE name = 'UzChagt';
UPDATE core_polity SET world_region = 'Central Eurasia' WHERE name = 'UzTimur';
UPDATE core_polity SET world_region = 'Central Eurasia' WHERE name = 'UzJanid';
UPDATE core_polity SET world_region = 'Central Eurasia' WHERE name = 'MnXngnE';
UPDATE core_polity SET world_region = 'Central Eurasia' WHERE name = 'MnXngnM';
UPDATE core_polity SET world_region = 'Central Eurasia' WHERE name = 'MnXngnL';
UPDATE core_polity SET world_region = 'Central Eurasia' WHERE name = 'MnXianb';
UPDATE core_polity SET world_region = 'Central Eurasia' WHERE name = 'MnRourn';
UPDATE core_polity SET world_region = 'Central Eurasia' WHERE name = 'MnETurk';
UPDATE core_polity SET world_region = 'Central Eurasia' WHERE name = 'MnTurk2';
UPDATE core_polity SET world_region = 'Central Eurasia' WHERE name = 'MnUigur';
UPDATE core_polity SET world_region = 'Central Eurasia' WHERE name = 'MnShiwe';
UPDATE core_polity SET world_region = 'Central Eurasia' WHERE name = 'MnKhitn';
UPDATE core_polity SET world_region = 'Central Eurasia' WHERE name = 'MnMongE';
UPDATE core_polity SET world_region = 'Central Eurasia' WHERE name = 'MnMngKh';
UPDATE core_polity SET world_region = 'Central Eurasia' WHERE name = 'MnMongL';
UPDATE core_polity SET world_region = 'Central Eurasia' WHERE name = 'MnZungh';
UPDATE core_polity SET world_region = 'Central Eurasia' WHERE name = 'CnQingL';
UPDATE core_polity SET world_region = 'Central Eurasia' WHERE name = 'RuYakuE';
UPDATE core_polity SET world_region = 'Central Eurasia' WHERE name = 'RuYakuL';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'PkAcerN';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'PkCeraN';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'PkChalc';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'PkPreUr';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'PkUrbn1';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'PkUrbn2';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'PkPostU';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'PkProto';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'IrAchae';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'InMaury';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'PkIndGr';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'IrPart1';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'AfKushn';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'IrSasn1';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'AfHepht';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'IrSasn2';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'SyCalUm';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'IqAbbs1';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'PkSind1';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'AfGhurd';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'InDelh*';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'PkSind2';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'InMugl*';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'AfDurrn';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'InGangN';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'InGangC';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'InMahaJ';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'InSunga';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'InAyodE';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'InGupta';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'InMagad';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'InKanau';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'InRasht';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'InGurjr';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'InGhdvl';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'InDecNL';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'InDecIA';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'InDecKg';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'InSataL';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'InVakat';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'InKadam';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'InChaBd';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'InChaKl';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'InHoysa';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'InKampi';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'InVijay';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'GbEmpr2';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'InGaroE';
UPDATE core_polity SET world_region = 'South Asia' WHERE name = 'InGaroL';
UPDATE core_polity SET world_region = 'Southeast Asia' WHERE name = 'KhMekBA';
UPDATE core_polity SET world_region = 'Southeast Asia' WHERE name = 'KhMekIA';
UPDATE core_polity SET world_region = 'Southeast Asia' WHERE name = 'KhFunaE';
UPDATE core_polity SET world_region = 'Southeast Asia' WHERE name = 'KhFunaL';
UPDATE core_polity SET world_region = 'Southeast Asia' WHERE name = 'KhChenl';
UPDATE core_polity SET world_region = 'Southeast Asia' WHERE name = 'KhAngkE';
UPDATE core_polity SET world_region = 'Southeast Asia' WHERE name = 'KhAngkC';
UPDATE core_polity SET world_region = 'Southeast Asia' WHERE name = 'KhAngkL';
UPDATE core_polity SET world_region = 'Southeast Asia' WHERE name = 'KhCambd';
UPDATE core_polity SET world_region = 'Southeast Asia' WHERE name = 'ThAyuth';
UPDATE core_polity SET world_region = 'Southeast Asia' WHERE name = 'ThRattn';
UPDATE core_polity SET world_region = 'Southeast Asia' WHERE name = 'IdCJBun';
UPDATE core_polity SET world_region = 'Southeast Asia' WHERE name = 'IdKalin';
UPDATE core_polity SET world_region = 'Southeast Asia' WHERE name = 'IdMedng';
UPDATE core_polity SET world_region = 'Southeast Asia' WHERE name = 'IdKedir';
UPDATE core_polity SET world_region = 'Southeast Asia' WHERE name = 'IdMajap';
UPDATE core_polity SET world_region = 'Southeast Asia' WHERE name = 'IdMatrm';
UPDATE core_polity SET world_region = 'Southeast Asia' WHERE name = 'IdBrokE';
UPDATE core_polity SET world_region = 'Southeast Asia' WHERE name = 'IdBrokL';
UPDATE core_polity SET world_region = 'East Asia' WHERE name = 'CnPeili';
UPDATE core_polity SET world_region = 'East Asia' WHERE name = 'CnYngsh';
UPDATE core_polity SET world_region = 'East Asia' WHERE name = 'CnLngsh';
UPDATE core_polity SET world_region = 'East Asia' WHERE name = 'CnErlit';
UPDATE core_polity SET world_region = 'East Asia' WHERE name = 'CnErlig';
UPDATE core_polity SET world_region = 'East Asia' WHERE name = 'CnShang';
UPDATE core_polity SET world_region = 'East Asia' WHERE name = 'CnWZhou';
UPDATE core_polity SET world_region = 'East Asia' WHERE name = 'CnJinSA';
UPDATE core_polity SET world_region = 'East Asia' WHERE name = 'CnWeiWS';
UPDATE core_polity SET world_region = 'East Asia' WHERE name = 'CnWHan*';
UPDATE core_polity SET world_region = 'East Asia' WHERE name = 'CnEHan*';
UPDATE core_polity SET world_region = 'East Asia' WHERE name = 'CnErJin';
UPDATE core_polity SET world_region = 'East Asia' WHERE name = 'CnNWei*';
UPDATE core_polity SET world_region = 'East Asia' WHERE name = 'CnSui**';
UPDATE core_polity SET world_region = 'East Asia' WHERE name = 'CnTangE';
UPDATE core_polity SET world_region = 'East Asia' WHERE name = 'CnTangL';
UPDATE core_polity SET world_region = 'East Asia' WHERE name = 'CnNSong';
UPDATE core_polity SET world_region = 'East Asia' WHERE name = 'CnLrJin';
UPDATE core_polity SET world_region = 'East Asia' WHERE name = 'CnYuan*';
UPDATE core_polity SET world_region = 'East Asia' WHERE name = 'CnMing*';
UPDATE core_polity SET world_region = 'East Asia' WHERE name = 'CnQingE';
UPDATE core_polity SET world_region = 'East Asia' WHERE name = 'CnQingL';
UPDATE core_polity SET world_region = 'East Asia' WHERE name = 'JpJomo1';
UPDATE core_polity SET world_region = 'East Asia' WHERE name = 'JpJomo2';
UPDATE core_polity SET world_region = 'East Asia' WHERE name = 'JpJomo3';
UPDATE core_polity SET world_region = 'East Asia' WHERE name = 'JpJomo4';
UPDATE core_polity SET world_region = 'East Asia' WHERE name = 'JpJomo5';
UPDATE core_polity SET world_region = 'East Asia' WHERE name = 'JpJomo6';
UPDATE core_polity SET world_region = 'East Asia' WHERE name = 'JpYayoi';
UPDATE core_polity SET world_region = 'East Asia' WHERE name = 'JpKofun';
UPDATE core_polity SET world_region = 'East Asia' WHERE name = 'JpAsuka';
UPDATE core_polity SET world_region = 'East Asia' WHERE name = 'JpNara*';
UPDATE core_polity SET world_region = 'East Asia' WHERE name = 'JpHeian';
UPDATE core_polity SET world_region = 'East Asia' WHERE name = 'JpKamak';
UPDATE core_polity SET world_region = 'East Asia' WHERE name = 'JpAshik';
UPDATE core_polity SET world_region = 'East Asia' WHERE name = 'JpSengk';
UPDATE core_polity SET world_region = 'East Asia' WHERE name = 'JpAzMom';
UPDATE core_polity SET world_region = 'East Asia' WHERE name = 'JpTokgw';
UPDATE core_polity SET world_region = 'East Asia' WHERE name = 'CnHQngL';
UPDATE core_polity SET world_region = 'East Asia' WHERE name = 'CnHChin';
UPDATE core_polity SET world_region = 'Oceania-Australia' WHERE name = 'Hawaii1';
UPDATE core_polity SET world_region = 'Oceania-Australia' WHERE name = 'Hawaii2';
UPDATE core_polity SET world_region = 'Oceania-Australia' WHERE name = 'Hawaii3';
UPDATE core_polity SET world_region = 'Oceania-Australia' WHERE name = 'USKameh';
UPDATE core_polity SET world_region = 'Oceania-Australia' WHERE name = 'PgOrokE';
UPDATE core_polity SET world_region = 'Oceania-Australia' WHERE name = 'PgOrokL';
UPDATE core_polity SET world_region = 'Oceania-Australia' WHERE name = 'FmTrukE';
UPDATE core_polity SET world_region = 'Oceania-Australia' WHERE name = 'FmTrukL';
UPDATE core_polity SET world_region = 'North America' WHERE name = 'MxTieLa';
UPDATE core_polity SET world_region = 'North America' WHERE name = 'MxSanGu';
UPDATE core_polity SET world_region = 'North America' WHERE name = 'MxRosar';
UPDATE core_polity SET world_region = 'North America' WHERE name = 'MxAlb1E';
UPDATE core_polity SET world_region = 'North America' WHERE name = 'MxAlb1L';
UPDATE core_polity SET world_region = 'North America' WHERE name = 'MxAlb2*';
UPDATE core_polity SET world_region = 'North America' WHERE name = 'MxAlb3A';
UPDATE core_polity SET world_region = 'North America' WHERE name = 'MxAlb3B';
UPDATE core_polity SET world_region = 'North America' WHERE name = 'MxAlb5*';
UPDATE core_polity SET world_region = 'North America' WHERE name = 'EsHabsb';
UPDATE core_polity SET world_region = 'North America' WHERE name = 'MxArch*';
UPDATE core_polity SET world_region = 'North America' WHERE name = 'MxInitl';
UPDATE core_polity SET world_region = 'North America' WHERE name = 'MxFormE';
UPDATE core_polity SET world_region = 'North America' WHERE name = 'MxFormM';
UPDATE core_polity SET world_region = 'North America' WHERE name = 'MxFormL';
UPDATE core_polity SET world_region = 'North America' WHERE name = 'MxFormT';
UPDATE core_polity SET world_region = 'North America' WHERE name = 'MxClass';
UPDATE core_polity SET world_region = 'North America' WHERE name = 'MxEpicl';
UPDATE core_polity SET world_region = 'North America' WHERE name = 'MxToltc';
UPDATE core_polity SET world_region = 'North America' WHERE name = 'MxPostM';
UPDATE core_polity SET world_region = 'North America' WHERE name = 'MxAztec';
UPDATE core_polity SET world_region = 'North America' WHERE name = 'USMisEW';
UPDATE core_polity SET world_region = 'North America' WHERE name = 'USMisMW';
UPDATE core_polity SET world_region = 'North America' WHERE name = 'USMisRo';
UPDATE core_polity SET world_region = 'North America' WHERE name = 'USMisMu';
UPDATE core_polity SET world_region = 'North America' WHERE name = 'USMisPa';
UPDATE core_polity SET world_region = 'North America' WHERE name = 'USMisSp';
UPDATE core_polity SET world_region = 'North America' WHERE name = 'USMisME';
UPDATE core_polity SET world_region = 'North America' WHERE name = 'USCahoE';
UPDATE core_polity SET world_region = 'North America' WHERE name = 'USCahoL';
UPDATE core_polity SET world_region = 'North America' WHERE name = 'USMisSd';
UPDATE core_polity SET world_region = 'North America' WHERE name = 'USOneot';
UPDATE core_polity SET world_region = 'North America' WHERE name = 'USIllin';
UPDATE core_polity SET world_region = 'North America' WHERE name = 'UsIroqP';
UPDATE core_polity SET world_region = 'North America' WHERE name = 'UsIroqE';
UPDATE core_polity SET world_region = 'North America' WHERE name = 'UsIroqL';
UPDATE core_polity SET world_region = 'South America' WHERE name = 'PeCuzLF';
UPDATE core_polity SET world_region = 'South America' WHERE name = 'PeCuzE1';
UPDATE core_polity SET world_region = 'South America' WHERE name = 'PeCuzE2';
UPDATE core_polity SET world_region = 'South America' WHERE name = 'PeWari*';
UPDATE core_polity SET world_region = 'South America' WHERE name = 'PeCuzL1';
UPDATE core_polity SET world_region = 'South America' WHERE name = 'PeCuzL2';
UPDATE core_polity SET world_region = 'South America' WHERE name = 'PeInca*';
UPDATE core_polity SET world_region = 'South America' WHERE name = 'EsHabsb';
UPDATE core_polity SET world_region = 'South America' WHERE name = 'CoNahua';
UPDATE core_polity SET world_region = 'South America' WHERE name = 'CoTairo';
UPDATE core_polity SET world_region = 'South America' WHERE name = 'EcJivaE';
UPDATE core_polity SET world_region = 'South America' WHERE name = 'EcJivaL';