UPDATE core_nga SET subregion = 'West Africa', fao_country = 'Ghana' WHERE name = 'Ghanaian Coast';
UPDATE core_nga SET subregion = 'Sahel', fao_country = 'Mali' WHERE name = 'Niger Inland Delta';
UPDATE core_nga SET subregion = 'Northeastern Africa', fao_country = 'Egypt' WHERE name = 'Upper Egypt';
UPDATE core_nga SET subregion = 'Northern Europe', fao_country = 'Iceland' WHERE name = 'Iceland';
UPDATE core_nga SET subregion = 'Western Europe', fao_country = 'France' WHERE name = 'Paris Basin';
UPDATE core_nga SET subregion = 'Southern Europe', fao_country = 'Italy' WHERE name = 'Latium';
UPDATE core_nga SET subregion = 'Siberia', fao_country = 'Russia' WHERE name = 'Lena River Valley';
UPDATE core_nga SET subregion = 'Mongolia', fao_country = 'Mongolia' WHERE name = 'Orkhon Valley';
UPDATE core_nga SET subregion = 'Turkestan', fao_country = 'Uzbekistan' WHERE name = 'Sogdiana';
UPDATE core_nga SET subregion = 'Arabia', fao_country = 'Yemen' WHERE name = 'Yemeni Coastal Plain';
UPDATE core_nga SET subregion = 'Anatolia-Caucasus', fao_country = 'Turkey' WHERE name = 'Konya Plain';
UPDATE core_nga SET subregion = 'Levant-Mesopotamia', fao_country = 'Iran' WHERE name = 'Susiana';
UPDATE core_nga SET subregion = 'Eastern India', fao_country = 'India' WHERE name = 'Garo Hills';
UPDATE core_nga SET subregion = 'Central India', fao_country = 'India' WHERE name = 'Deccan';
UPDATE core_nga SET subregion = 'Indo-Gangetic Plain', fao_country = 'Pakistan' WHERE name = 'Kachi Plain';
UPDATE core_nga SET subregion = 'Indonesia', fao_country = 'Indonesia' WHERE name = 'Kapuasi Basin';
UPDATE core_nga SET subregion = 'Indonesia', fao_country = 'Indonesia' WHERE name = 'Central Java';
UPDATE core_nga SET subregion = 'Siam', fao_country = 'Cambodia' WHERE name = 'Cambodian Basin';
UPDATE core_nga SET subregion = 'South China', fao_country = 'China' WHERE name = 'Southern China Hills';
UPDATE core_nga SET subregion = 'Northeast Asia', fao_country = 'Japan' WHERE name = 'Kansai';
UPDATE core_nga SET subregion = 'North China', fao_country = 'China' WHERE name = 'Middle Yellow River Valley';
UPDATE core_nga SET subregion = 'East Coast', fao_country = 'United States' WHERE name = 'Finger Lakes';
UPDATE core_nga SET subregion = 'Mississippi Basin', fao_country = 'United States' WHERE name = 'Cahokia';
UPDATE core_nga SET subregion = 'Mexico', fao_country = 'Mexico' WHERE name = 'Valley of Oaxaca';
UPDATE core_nga SET subregion = 'Amazonia', fao_country = 'Ecuador' WHERE name = 'Lowland Andes';
UPDATE core_nga SET subregion = 'Caribbean', fao_country = 'Colombia' WHERE name = 'North Colombia';
UPDATE core_nga SET subregion = 'Andes', fao_country = 'Peru' WHERE name = 'Cuzco';
UPDATE core_nga SET subregion = 'New Guinea', fao_country = 'Papua New Guinea' WHERE name = 'Oro PNG';
UPDATE core_nga SET subregion = 'Micronesia', fao_country = 'Micronesia' WHERE name = 'Chuuk Islands';
UPDATE core_nga SET subregion = 'Polynesia', fao_country = 'United States' WHERE name = 'Big Island Hawaii';
UPDATE core_nga SET subregion = 'Levant-Mesopotamia', fao_country = 'Iraq' WHERE name = 'Southern Mesopotamia';
UPDATE core_nga SET subregion = 'Levant-Mesopotamia', fao_country = 'Israel' WHERE name = 'Galilee';
UPDATE core_nga SET subregion = 'Southeastern Europe', fao_country = 'Greece' WHERE name = 'Crete';
UPDATE core_nga SET subregion = 'Indo-Gangetic Plain', fao_country = 'India' WHERE name = 'Middle Ganga';
UPDATE core_nga SET subregion = 'Mexico', fao_country = 'Mexico' WHERE name = 'Basin of Mexico';