INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (254, 'Chinese Buddhist Traditions', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (266, 'Chinese Buddhist Traditions', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (425, 'Chinese Buddhist Traditions', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (258, 'Chinese Buddhist Traditions', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (260, 'Chinese Buddhist Traditions', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (261, 'Chinese Buddhist Traditions', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (367, 'Sufi', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (232, 'Sufi', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (239, 'Sufi', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (236, 'Sufi', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (92, 'Vaisnava Traditions', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (94, 'Vaisnava Traditions', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (135, 'Sufi', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (93, 'Vaishnava Traditions', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (132, 'Shia', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (484, 'Shia', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (186, 'Catholic', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (149, 'Japanese Buddhism', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (148, 'Japanese Buddhism', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (263, 'Japanese Buddhism', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (289, 'Sufi', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (41, 'Mahayana', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (40, 'Mahayana', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (42, 'Mahayana', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (42, 'Saiva Traditions', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (39, 'Mahayana', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (37, 'Mahayana', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (38, 'Mahayana', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (136, 'Sufi', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (175, 'Sufi', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (176, 'Sufi', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (296, 'Sunni', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (368, 'Shia', 'TRS', 'true', 'alternate_religion_family');