INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (137, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (134, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (134, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (350, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (129, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (129, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (281, 'confederate state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (127, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (467, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (253, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (253, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (254, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (422, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (422, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (421, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (471, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (470, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (245, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (420, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (266, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (269, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (425, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (258, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (1, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (2, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (243, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (260, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (261, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (264, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (424, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (251, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (244, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (244, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (419, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (268, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (435, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (436, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (196, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (196, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (197, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (367, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (367, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (367, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (510, 'suspected unknown', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (514, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (515, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (205, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (232, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (239, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (236, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (519, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (511, 'none', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (511, 'suspected unknown', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (512, 'unknown', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (513, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (199, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (199, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (198, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (516, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (517, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (517, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (109, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (207, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (518, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (518, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (518, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (203, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (203, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (520, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (520, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (520, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (200, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (200, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (361, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (84, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (208, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (208, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (208, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (57, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (58, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (448, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (447, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (460, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (461, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (457, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (457, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (458, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (458, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (309, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (311, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (311, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (449, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (450, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (451, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (452, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (304, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (304, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (304, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (304, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (306, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (306, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (306, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (306, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (453, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (453, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (454, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (454, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (455, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (455, 'confederation', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (333, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (459, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (459, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (99, 'confederation', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (99, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (113, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (114, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (67, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (68, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (74, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (65, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (66, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (69, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (63, 'polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (59, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (62, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (61, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (64, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (60, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (17, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (18, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (19, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (19, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (19, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (19, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (19, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (19, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (153, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (154, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (47, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (49, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (50, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (51, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (48, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (103, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (110, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (105, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (92, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (94, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (86, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (88, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (85, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (135, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (111, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (112, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (388, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (95, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (91, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (96, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (96, 'nominal allegiance', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (87, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (98, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (93, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (89, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (89, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (385, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (90, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (97, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (97, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (97, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (132, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (132, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (484, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (476, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (479, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (479, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (342, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (481, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (482, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (475, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (475, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (480, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (478, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (106, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (346, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (473, 'suspected unknown', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (477, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (474, 'suspected unknown', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (107, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (107, 'confederate state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (508, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (508, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (487, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (495, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (362, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (502, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (502, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (507, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (486, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (172, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (489, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (491, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (490, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (499, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (500, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (501, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (503, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (503, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (504, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (504, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (505, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (505, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (125, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (483, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (485, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (509, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (374, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (128, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (130, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (108, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (108, 'confederate state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (364, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (496, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (497, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (497, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (498, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (492, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (493, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (494, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (494, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (115, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (179, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (178, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (186, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (186, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (189, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (190, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (190, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (190, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (190, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (192, 'unitary', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (193, 'unitary', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (191, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (187, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (187, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (187, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (182, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (184, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (183, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (70, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (181, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (185, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (188, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (544, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (545, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (149, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (146, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (151, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (151, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (147, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (138, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (139, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (140, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (141, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (142, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (143, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (148, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (145, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (263, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (150, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (152, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (144, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (289, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (282, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (282, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (41, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (40, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (42, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (43, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (39, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (37, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (38, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (463, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (104, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (432, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (434, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (427, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (428, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (430, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (431, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (229, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (229, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (433, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (433, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (242, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (288, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (267, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (442, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (443, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (443, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (278, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (439, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (440, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (440, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (286, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (438, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (438, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (274, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (272, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (444, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (224, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (216, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (525, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (526, 'confederation', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (526, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (527, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (528, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (529, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (532, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (8, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (10, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (9, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (11, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (524, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (523, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (522, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (116, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (78, 'none', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (79, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (81, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (82, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (77, 'none', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (83, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (80, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (445, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (446, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (117, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (118, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (119, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (126, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (123, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (120, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (124, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (133, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (133, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (133, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (136, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (121, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (122, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (194, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (195, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (521, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (131, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (45, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (462, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (221, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (160, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (161, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (161, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (73, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (75, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (76, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (170, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (170, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (170, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (158, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (159, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (72, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (164, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (162, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (168, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (169, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (156, 'unknown', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (155, 'unknown', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (165, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (173, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (173, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (174, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (175, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (176, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (166, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (71, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (171, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (167, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (32, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (33, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (30, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (101, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (102, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (20, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (22, 'none', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (34, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (25, 'none', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (23, 'none', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (26, 'none', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (24, 'none', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (28, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (27, 'none', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (29, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (296, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (469, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (465, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (464, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (466, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (287, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (468, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (370, 'nominal allegiance', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (370, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (370, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (353, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (354, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (541, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (539, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (368, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (538, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (372, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (365, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (359, 'loose', 'TRS', 'true', 'degree_of_centralization');