INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (147, 147, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (127, 147, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (121, 121, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (471, 121, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (148, 148, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (261, 148, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (196, 121, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (197, 121, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (149, 149, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (367, 149, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (150, 150, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (519, 150, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (199, 150, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (198, 150, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (516, 150, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (151, 151, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (516, 151, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (517, 150, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (517, 151, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (109, 150, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (207, 150, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (518, 151, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (520, 151, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (152, 152, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (99, 152, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (118, 118, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (67, 118, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (68, 118, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (74, 118, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (66, 118, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (69, 118, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (59, 118, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (62, 118, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (61, 118, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (64, 118, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (60, 118, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (153, 153, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (17, 153, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (18, 153, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (19, 153, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (154, 154, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (51, 154, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (155, 155, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (103, 155, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (110, 155, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (105, 155, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (111, 121, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (112, 121, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (418, 121, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (390, 121, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (98, 121, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (476, 121, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (475, 121, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (156, 156, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (472, 156, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (473, 156, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (364, 121, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (157, 157, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (115, 157, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (158, 158, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (115, 158, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (126, 126, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (190, 126, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (192, 126, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (193, 126, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (191, 126, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (187, 121, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (182, 121, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (159, 159, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (184, 159, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (183, 121, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (70, 159, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (181, 121, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (185, 121, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (188, 121, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (104, 155, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (267, 121, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (160, 160, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (442, 160, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (161, 161, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (532, 161, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (162, 162, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (6, 162, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (16, 162, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (12, 162, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (13, 162, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (8, 162, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (10, 162, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (9, 162, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (11, 162, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (7, 162, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (15, 162, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (14, 162, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (116, 157, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (116, 158, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (163, 163, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (83, 163, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (445, 121, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (446, 121, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (164, 164, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (117, 164, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (118, 164, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (119, 164, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (120, 164, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (124, 164, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (121, 164, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (122, 164, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (521, 121, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (131, 121, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (221, 121, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (165, 165, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (73, 165, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (75, 165, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (76, 165, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (166, 166, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (158, 166, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (72, 165, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (157, 121, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (173, 165, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (174, 165, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (175, 121, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (176, 121, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (71, 121, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (167, 167, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (32, 167, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (33, 167, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (20, 153, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (22, 167, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (34, 167, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (25, 167, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (23, 167, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (26, 167, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (24, 167, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (28, 167, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (27, 167, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (168, 168, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (537, 168, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (536, 168, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (538, 168, 'TRS', 'true', 'expert');