INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (137, 'Pashto', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (137, 'Persian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (134, 'Persian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (350, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (350, 'Bactrian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (129, 'Bactrian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (281, 'Sogdian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (281, 'Bactrian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (281, 'Pahlavi', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (281, 'Brahmi', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (127, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (127, 'Bactrian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (127, 'Kharoshthi', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (467, 'Tocharian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (467, 'Bactrian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (253, 'Chinese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (254, 'Chinese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (422, 'archaic Chinese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (421, 'archaic Chinese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (471, 'Xiangxi', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (471, 'Qiandong', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (471, 'Chuanqiandian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (470, 'Hmong-Mien', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (470, 'Hmongic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (470, 'Chuanqiandian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (245, 'Chinese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (266, 'Middle Chinese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (266, 'Jurchen', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (266, 'Khitan', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (269, 'Chinese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (425, 'Chinese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (258, 'Chinese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (258, 'Xianbei', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (1, 'Manchu language', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (1, 'Chinese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (2, 'Manchu language', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (2, 'Chinese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (243, 'Chinese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (260, 'Chinese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (261, 'Chinese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (264, 'Chinese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (424, 'Chinese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (251, 'Chinese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (244, 'Chinese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (268, 'Mongolian language', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (268, 'Chinese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (436, 'Atanque', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (196, 'Shuar', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (197, 'Shuar', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (367, 'Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (510, 'suspected unknown', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (514, 'suspected unknown', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (515, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (205, 'Demotic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (232, 'Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (239, 'Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (236, 'Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (519, 'Ancient Egyptian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (511, 'suspected unknown', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (512, 'suspected unknown', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (513, 'suspected unknown', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (199, 'Late Egyptian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (198, 'Late Egyptian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (516, 'Ancient Egyptian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (517, 'Ancient Egyptian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (109, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (109, 'demotic Egyptian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (207, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (518, 'Ancient Egyptian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (203, 'Demotic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (520, 'Ancient Egyptian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (200, 'Ancient Egyptian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (361, 'Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (84, 'Castilian Spanish', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (84, 'Castilian Spanish', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (57, 'Chuukese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (58, 'Chuukese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (460, 'French', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (461, 'French', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (457, 'French', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (457, 'Langues dOil', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (457, 'Occitan', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (458, 'French', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (458, 'Langues dOil', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (458, 'Occitan', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (309, 'Latin', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (449, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (304, 'Old Frankish', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (456, 'Latin', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (456, 'Germanic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (306, 'Latin', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (306, 'Germanic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (453, 'Gallic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (454, 'Gallic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (455, 'Gaulish', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (333, 'French', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (459, 'French', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (99, 'English', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (113, 'Akan', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (113, 'Twi', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (114, 'Akan', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (114, 'Twi', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (67, 'Doric Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (68, 'Doric Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (74, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (74, 'Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (65, 'Minoan', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (65, 'Early Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (66, 'Doric Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (66, 'Eteocretan', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (63, 'Minoan', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (63, 'Early Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (62, 'suspected unknown', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (64, 'Minoan', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (64, 'Early Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (60, 'suspected unknown', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (17, 'Old Hawaiian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (18, 'Hawaiian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (19, 'Hawaiian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (153, 'Iban', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (154, 'Iban', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (47, 'Sanskrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (49, 'Sanskrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (49, 'Old Javanese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (50, 'Middle Javanese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (50, 'Sanskrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (51, 'Javanese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (48, 'Sanskrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (48, 'Old Javanese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (103, 'Canaanite', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (110, 'Aramaic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (110, 'Hebrew', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (110, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (105, 'Hebrew', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (92, 'Sanskrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (92, 'Kannada', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (94, 'Kannada', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (94, 'Sanskrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (135, 'Persian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (135, 'Urdu', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (111, 'A’chik', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (112, 'A’chik', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (388, 'Sanskrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (388, 'Prakrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (95, 'Kannada', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (95, 'Sanskrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (91, 'Sanskrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (91, 'Prakrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (91, 'Kannada', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (96, 'Kannada', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (96, 'Sanskrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (87, 'Prakrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (87, 'Sanskrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (98, 'Urdu', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (98, 'Persian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (93, 'Sanskrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (93, 'Kannada', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (89, 'Prakrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (89, 'Kannada', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (385, 'Sanskrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (385, 'Prakrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (90, 'Sanskrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (97, 'Sanskrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (97, 'Telugu', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (97, 'Tamil', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (97, 'Kannada', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (132, 'Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (484, 'Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (476, 'Akkadian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (476, 'Sumerian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (479, 'Amorite', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (479, 'Old Babylonian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (481, 'Akkadian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (482, 'Mesopotamian Religions', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (475, 'Sumerian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (480, 'Akkadian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (478, 'Akkadian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (106, 'Aramaic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (473, 'suspected unknown', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (477, 'Sumerian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (477, 'Akkadian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (474, 'suspected unknown', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (107, 'Old Persian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (107, 'Aramaic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (107, 'Elamite', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (107, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (107, 'Egyptian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (508, 'Persian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (495, 'Old Elamite', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (495, 'Akkadian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (362, 'Persian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (362, 'Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (507, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (172, 'Mongolian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (172, 'Persian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (172, 'Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (499, 'Elamite', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (499, 'Akkadian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (500, 'Elamite', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (500, 'Akkadian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (501, 'Elamite', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (501, 'Akkadian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (504, 'Elamite', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (504, 'native Iranian languages', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (505, 'Elamite', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (125, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (125, 'Pahlavi', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (483, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (483, 'Pahlavi', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (509, 'Persian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (374, 'Persian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (374, 'Turkic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (374, 'Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (128, 'Pahlavi', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (130, 'Pahlavi', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (108, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (364, 'Turkish', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (364, 'Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (364, 'Persian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (496, 'Elamite', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (496, 'Akkadian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (496, 'Babylonian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (497, 'Elamite', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (497, 'Akkadian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (497, 'Babylonian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (497, 'Hurrian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (497, 'Amorite', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (493, 'Sumerian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (494, 'Sumerian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (494, 'Proto-Elamite', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (115, 'Old Norse', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (179, 'Latin', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (180, 'Latin', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (186, 'Latin', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (186, 'Germanic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (189, 'Latin', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (190, 'Latin', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (192, 'Latin', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (193, 'Latin', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (191, 'Latin', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (187, 'Latin', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (187, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (182, 'Latin', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (182, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (184, 'Latin', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (184, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (183, 'Latin', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (183, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (70, 'Latin', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (181, 'Latin', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (185, 'Latin', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (188, 'Latin', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (544, 'Italian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (545, 'Italian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (149, 'Middle Japanese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (146, 'Old Japanese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (151, 'Middle Japanese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (147, 'Late Old Japanese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (147, 'Middle Japanese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (138, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (139, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (140, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (141, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (142, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (143, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (148, 'Middle Japanese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (145, 'Japanese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (263, 'Old Japanese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (150, 'Middle Japanese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (152, 'Early Modern Japanese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (144, 'Japanese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (289, 'Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (289, 'Turkic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (282, 'Sogdian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (282, 'Old Turkic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (282, 'Iranian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (41, 'Old Khmer', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (41, 'Mon', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (41, 'Tai', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (40, 'Old Khmer', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (42, 'Khmer', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (43, 'Khmer', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (43, 'Mon', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (43, 'Tai', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (43, 'Pali', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (39, 'Old Khmer', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (39, 'Sanskrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (37, 'Khmer', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (37, 'Mon', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (38, 'Khmer', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (38, 'Mon', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (104, 'Phoenician', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (432, 'Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (432, 'Berber', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (432, 'Spanish', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (432, 'Portuguese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (434, 'Bambara', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (427, 'suspected unknown', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (229, 'Mande', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (229, 'Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (433, 'Bambara', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (242, 'Mande', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (242, 'Songhay', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (283, 'Old Turkic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (283, 'Sogdian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (288, 'Khitan', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (267, 'Mongolian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (267, 'Persian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (267, 'Chinese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (267, 'Latin', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (267, 'Russian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (267, 'Georgian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (267, 'Armenian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (442, 'Mongolian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (442, 'Kereid', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (442, 'Tatar', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (442, 'Naimans', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (443, 'Khalkha', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (278, 'Rouran', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (440, 'Old Turkic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (286, 'Old Turkic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (438, 'Xianbei', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (437, 'Xiongnu', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (274, 'Xiongnu', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (272, 'Xiongnu', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (444, 'Oirat', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (224, 'Mande', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (216, 'Mande', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (525, 'Zapotec', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (526, 'Zapotec', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (527, 'Zapotec', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (528, 'Zapotec', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (529, 'Zapotec', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (532, 'Zapotec', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (10, 'suspected unknown', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (11, 'suspected unknown', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (524, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (523, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (522, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (116, 'Icelandic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (78, 'suspected unknown', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (79, 'suspected unknown', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (81, 'Aymara', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (81, 'Puquina', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (82, 'Aymara', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (82, 'Puquina', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (77, 'suspected unknown', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (83, 'Quechua', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (80, 'suspected unknown', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (445, 'Orokaiva', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (446, 'Orokaiva', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (117, 'unknown', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (118, 'unknown', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (119, 'unknown', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (126, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (126, 'Sanskrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (126, 'Prakrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (126, 'Bactrian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (126, 'Aramaic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (123, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (120, 'unknown', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (124, 'unknown', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (133, 'Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (133, 'Sindhi', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (136, 'Sindhi', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (136, 'Punjabi', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (121, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (122, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (194, 'Sakha (Yakut)', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (195, 'Sakha (Yakut)', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (521, 'Merotic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (521, 'Egyptian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (131, 'Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (131, 'Coptic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (131, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (131, 'Persian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (44, 'Tai', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (44, 'Thai', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (45, 'Thai', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (221, 'Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (160, 'Proto-Indo-European language', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (163, 'Nesite', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (163, 'Luwian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (161, 'Hattic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (161, 'Luwian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (161, 'Hittite', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (161, 'Hurrian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (161, 'Old Assyrian dialect of Akkadian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (73, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (75, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (76, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (170, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (158, 'Indo-European language', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (159, 'Indo-European language', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (72, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (164, 'Nesite', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (164, 'Luwian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (162, 'Nesite', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (162, 'Luwian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (168, 'Lydian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (169, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (156, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (157, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (165, 'Luwian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (173, 'Ottoman Turkish', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (174, 'Turkish', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (174, 'Persian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (175, 'Turkish', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (176, 'Turkish', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (166, 'Phrygian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (71, 'Latin', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (71, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (171, 'Turkish', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (171, 'Persian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (171, 'Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (167, 'Luwian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (32, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (33, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (30, 'Miami Illinois', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (101, 'Cayuga', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (101, 'Mohawk', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (101, 'Oneida', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (101, 'Onondaga', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (101, 'Seneca', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (101, 'Tuscarora', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (102, 'Cayuga', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (102, 'Mohawk', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (102, 'Oneida', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (102, 'Onondaga', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (102, 'Seneca', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (102, 'Tuscarora', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (20, 'Hawaiian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (34, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (28, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (296, 'Middle Mongolian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (469, 'Persian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (465, 'Sogdian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (466, 'Ancient Iranian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (287, 'Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (287, 'Persian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (468, 'Sogdian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (370, 'Chagatai Turkish', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (370, 'Persian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (541, 'Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (539, 'Sabaic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (539, 'Mainic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (539, 'Qatabanic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (539, 'Hadramawtic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (539, 'Old Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (538, 'Sabaic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (538, 'Mainic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (538, 'Qatabanic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (538, 'Hadramawtic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (538, 'Old Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (540, 'Sabaic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (540, 'Mainic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (540, 'Qatabanic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (540, 'Hadramawtic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (540, 'Old Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (372, 'Arabic', 'TRS', 'true', 'language');