INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (137, 'Durrani Empire', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (134, 'Principality of Ghur', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (350, 'Greco-Bactrian Kingdom', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (129, 'Hepthalite Empire', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (281, 'Kidarite Kingdom', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (127, 'Kushan Empire', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (467, 'Tocharians', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (253, 'Eastern Han', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (254, 'Western Jin', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (422, 'Erligang', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (421, 'Erlitou', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (471, 'Hmong - Early Chinese', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (470, 'Hmong - Late Qing', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (245, 'Jin', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (420, 'Longshan', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (266, 'Later Jin', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (269, 'Great Ming', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (425, 'Northern Song', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (258, 'Northern Wei', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (1, 'Early Qing', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (2, 'Late Qing', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (243, 'Late Shang', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (260, 'Sui Dynasty', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (261, 'Early Tang Dynasty', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (264, 'Later Tang Dynasty', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (424, 'Early Wei Dynasty', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (251, 'Western Han', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (244, 'Western Zhou', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (419, 'Yangshao', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (268, 'Great Yuan', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (435, 'Neguanje', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (436, 'Tairona', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (196, 'Shuar - Early', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (197, 'Shuar - Late', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (367, 'Ayyubid Sultanate', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (510, 'Badarian', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (514, 'Egypt - Dynasty I', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (515, 'Egypt - Dynasty II', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (205, 'Egypt - Inter-Occupation Period', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (232, 'Egypt - Mamluk Sultanate I', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (239, 'Egypt - Mamluk Sultanate III', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (236, 'Egypt - Mamluk Sultanate II', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (519, 'Egypt - Middle Kingdom', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (511, 'Naqada I', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (512, 'Naqada II', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (513, 'Egypt - Dynasty 0', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (199, 'Egypt - New Kingdom Ramesside Period', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (198, 'Egypt - New Kingdom Thutmosid Period', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (516, 'Egypt - Classic Old Kingdom', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (517, 'Egypt - Late Old Kingdom', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (109, 'Ptolemaic Kingdom I', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (207, 'Ptolemaic Kingdom II', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (518, 'Egypt - Period of the Regions', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (203, 'Egypt - Saite Period', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (520, 'Egypt - Thebes-Hyksos Period', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (200, 'Egypt - Thebes-Libyan Period', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (361, 'Egypt - Tulunid-Ikhshidid Period', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (84, 'Spanish Empire', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (208, 'Proto-Aksumite Period', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (57, 'Early Truk', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (58, 'Chuuk - Late Truk', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (448, 'Atlantic Complex', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (447, 'Beaker Culture', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (460, 'French Kingdom - Early Bourbon', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (461, 'French Kingdom - Late Bourbon', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (457, 'Proto-French Kingdom', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (458, 'French Kingdom - Late Capetian', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (309, 'Carolingian Empire I', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (311, 'Carolingian Empire II', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (449, 'Hallstatt A-B1', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (450, 'Hallstatt B', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (451, 'Hallstatt C', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (452, 'Hallstatt D', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (304, 'Early Merovingian', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (456, 'Proto-Carolingian', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (306, 'Middle Merovingian', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (453, 'La Tene A-B1', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (454, 'La Tene B2-C1', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (455, 'La Tene C2-D', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (333, 'French Kingdom - Early Valois', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (459, 'French Kingdom - Late Valois', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (99, 'Second British Empire', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (113, 'Akan - Pre-Ashanti', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (114, 'Ashanti Empire', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (67, 'Archaic Crete', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (68, 'Classical Crete', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (74, 'The Emirate of Crete', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (65, 'Final Postpalatial Crete', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (66, 'Geometric Crete', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (69, 'Hellenistic Crete', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (63, 'Monopalatial Crete', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (59, 'Neolithic Crete', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (62, 'New Palace Crete', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (61, 'The Old Palace Crete', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (64, 'Postpalatial Crete', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (60, 'Prepalatial Crete', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (17, 'Hawaii I', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (18, 'Hawaii II', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (19, 'Hawaii III', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (153, 'Iban - Pre-Brooke', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (154, 'Iban - Brooke Raj and Colonial', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (46, 'Java - Buni Culture', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (47, 'Kalingga Kingdom', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (49, 'Kediri Kingdom', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (50, 'Majapahit Kingdom', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (51, 'Mataram Kingdom', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (48, 'Medang Kingdom', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (103, 'Canaan', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (110, 'Yehuda', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (105, 'Yisrael', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (92, 'Chalukyas of Badami', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (94, 'Chalukyas of Kalyani', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (86, 'Deccan - Iron Age', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (88, 'Post-Mauryan Kingdoms', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (85, 'Deccan - Neolithic', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (135, 'Delhi Sultanate', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (415, 'Chalcolithic Middle Ganga', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (414, 'Neolithic Middle Ganga', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (111, 'Achik', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (111, 'Mande', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (112, 'A’chik', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (112, 'Mande', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (405, 'Gahadavala Kingdom', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (418, 'Gurjar Dynasty', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (95, 'Hoysala Kingdom', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (91, 'Kadamba Empire', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (96, 'Kampili Kingdom', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (390, 'Magadha', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (87, 'Mauryan Empire', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (98, 'Mughal Empire', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (93, 'Rashtrakuta Empire', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (89, 'Satavahana Empire', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (90, 'Vakataka Kingdom', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (97, 'Vijayanagara Empire', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (132, 'Abbasid Caliphate I', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (484, 'Abbasid Caliphate II', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (476, 'Akkadian Empire', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (479, 'Old Babylonian', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (479, 'Amorite Dynasty', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (342, 'Babylonian Empire', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (342, 'Kassite Dynasty', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (475, 'Early Dynastic', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (106, 'Neo-Assyrian Empire', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (473, 'Ubaid', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (477, 'Ur - Dynasty III', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (474, 'Uruk', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (107, 'Achaemenid Empire', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (508, 'Ak Koyunlu', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (487, 'Susiana - Muhammad Jaffar', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (495, 'Elam - Awan Dynasty I', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (362, 'Buyid Confederation', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (502, 'Elam - Crisis Period', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (507, 'Elymais II', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (486, 'Formative Period', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (172, 'Il-khanate', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (488, 'Susiana A', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (489, 'Susiana B', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (491, 'Susiana - Late Ubaid', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (490, 'Susiana - Early Ubaid', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (499, 'Elam - Kidinuid Period', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (500, 'Elam - Igihalkid Period', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (501, 'Elam - Shutrukid Period', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (503, 'Elam', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (504, 'Elam', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (505, 'Elam', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (125, 'Parthian Empire I', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (483, 'Parthian Empire II', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (485, 'Pre-Ceramic Period', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (509, 'Qajar Dynasty', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (374, 'Safavid Empire', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (128, 'Sassanid Empire I', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (130, 'Sasanid Empire II', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (108, 'Seleucid Empire', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (364, 'Seljuk Empire', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (496, 'Elam - Shimashki Period', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (497, 'Elam - Early Sukkalmah', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (498, 'Elam - Late Sukkalmah', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (492, 'Susa I', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (493, 'Susa II', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (494, 'Susa III', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (115, 'Icelandic Commonwealth', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (179, 'Latium - Bronze Age', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (178, 'Latium - Copper Age', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (180, 'Latium - Iron Age', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (186, 'Ostrogothic Kingdom', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (189, 'Rome - Republic of St Peter II', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (190, 'Papal States - High Medieval Period', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (192, 'Papal States - Medieval Period I', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (193, 'Papal States - Medieval Period II', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (191, 'Papal States - Renaissance Period', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (187, 'Exarchate of Ravenna', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (182, 'Roman Republic', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (184, 'Late Roman Republic', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (183, 'Middle Roman Republic', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (70, 'Roman Empire - Principate', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (181, 'Roman Kingdom', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (185, 'Western Roman Empire - Late Antiquity', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (188, 'Republic of St Peter I', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (544, 'Venetian Republic', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (545, 'Venetian Republic', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (149, 'Ashikaga Shogunate', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (146, 'Kansai - Asuka Period', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (151, 'Japan - Azuchi-Momoyama', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (147, 'Kansai - Heian Period', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (138, 'Japan - Incipient Jomon', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (139, 'Japan - Initial Jomon', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (140, 'Japan - Early Jomon', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (141, 'Japan - Middle Jomon', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (142, 'Japan - Late Jomon', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (143, 'Japan - Final Jomon', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (148, 'Kamakura Shogunate', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (145, 'Kansai - Kofun Period', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (263, 'Kansai - Nara Period', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (150, 'Japan - Sengoku Jidai', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (152, 'Tokugawa Shogunate', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (144, 'Kansai - Yayoi Period', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (289, 'Kara-Khanids', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (282, 'Western Turk Khaganate', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (41, 'Classical Angkor', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (40, 'Early Angkor', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (42, 'Late Angkor', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (43, 'Khmer Kingdom', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (39, 'Chenla', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (37, 'Funan I', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (38, 'Funan II', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (35, 'Bronze Age Cambodia', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (36, 'Iron Age Cambodia', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (463, 'Andronovo', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (104, 'Phoenician Empire', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (432, 'Saadi Sultanate', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (434, 'Bamana kingdom', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (427, 'Jenne-jeno I', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (428, 'Jenne-jeno II', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (430, 'Jenne-jeno III', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (431, 'Jenne-jeno IV', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (229, 'Mali Empire', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (433, 'Segou Kingdom', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (242, 'Songhai Empire - Askiya Dynasty', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (283, 'Eastern Turk Khaganate', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (288, 'Khitan Empire', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (267, 'Mongol Empire', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (442, 'Early Mongols', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (443, 'Late Mongols', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (278, 'Rouran Khaganate', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (439, 'Shiwei', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (440, 'Second Turk Khaganate', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (286, 'Uigur Khaganate', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (438, 'Xianbei Confederation', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (437, 'Early Xiongnu', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (274, 'Late Xiongnu', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (272, 'Xiongnu Imperial Confederation', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (444, 'Zungharian Empire', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (224, 'Ghana Empire II', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (216, 'Ghana Empire I', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (525, 'Early Monte Alban I', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (526, 'Monte Alban Late I', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (527, 'Monte Alban II', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (528, 'Monte Alban III', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (529, 'Monte Albán IIIB and IV', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (532, 'Monte Alban V', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (8, 'Early Formative Basin of Mexico', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (10, 'Late Formative Basin of Mexico', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (9, 'Middle Formative Basin of Mexico', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (11, 'Terminal Formative Basin of Mexico', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (7, 'Initial Formative Basin of Mexico', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (524, 'Rosario', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (523, 'Oaxaca-San Jose', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (522, 'Tierras Largas', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (116, 'Kingdom of Norway', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (78, 'Cuzco - Early Intermediate I', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (79, 'Cuzco - Early Intermediate II', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (81, 'Cuzco - Late Intermediate I', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (82, 'Cuzco - Late Intermediate II', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (77, 'Cuzco - Late Formative', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (83, 'Inca Empire', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (80, 'Wari Empire', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (445, 'Orokaiva - Pre-Colonial', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (446, 'Orokaiva - Colonial', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (117, 'Kachi Plain - Aceramic Neolithic', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (118, 'Kachi Plain - Ceramic Neolithic', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (119, 'Kachi Plain - Chalcolithic', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (126, 'Indo-Greek Kingdom', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (123, 'Kachi Plain - Post-Urban Period', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (120, 'Kachi Plain - Pre-Urban Period', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (124, 'Kachi Plain - Proto-Historic Period', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (133, 'Sind - Abbasid-Fatimid Period', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (136, 'Sind - Samma Dynasty', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (121, 'Kachi Plain - Urban Period I', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (122, 'Kachi Plain - Urban Period II', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (194, 'Sakha', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (195, 'Sakha', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (521, 'Egypt - Kushite Period', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (131, 'Umayyad Caliphate', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (44, 'Ayutthaya', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (45, 'Rattanakosin', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (462, 'Sarazm', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (462, 'Sarazm', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (221, 'Fatimid Caliphate', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (160, 'Konya Plain - Early Bronze Age', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (163, 'Konya Plain - Late Bronze Age II', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (161, 'Middle Bronze Age in Central Anatolia', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (73, 'Byzantine Empire I', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (75, 'Bzyantine Empire II', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (76, 'Bzyantine Empire III', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (170, 'Late Cappadocia', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (158, 'Konya Plain - Early Chalcolithic', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (159, 'Konya Plain - Late Chalcolithic', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (72, 'East Roman Empire', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (164, 'Hatti - New Kingdom', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (162, 'Hatti - Old Kingdom', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (168, 'Kingdom of Lydia', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (169, 'Kingdom of Lysimachus', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (156, 'Konya Plain - Ceramic Neolithic', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (155, 'Konya Plain - Early Neolithic', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (157, 'Konya Plain - Late Neolithic', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (165, 'Neo-Hittite Kingdoms', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (173, 'Ottoman Emirate', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (174, 'Ottoman Empire I', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (175, 'Ottoman Empire II', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (176, 'Ottoman Empire III', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (166, 'Phrygian Kingdom', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (71, 'Roman Empire - Dominate', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (171, 'Sultanate of Rum', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (167, 'Tabal Kingdoms', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (32, 'Cahokia - Lohman-Stirling', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (33, 'Cahokia - Moorehead', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (30, 'Early Illinois Confederation', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (101, 'Haudenosaunee Confederacy', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (102, 'Haudenosaunee Confederacy', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (100, 'Proto-Iroquois Confederacy', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (20, 'Kingdom of Hawaii - Kamehameha Period', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (22, 'Cahokia - Early Woodland', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (34, 'Cahokia - Emergent Mississippian II', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (25, 'Cahokia - Late Woodland II', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (23, 'Cahokia - Middle Woodland', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (26, 'Cahokia - Late Woodland III', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (24, 'Cahokia - Late Woodland I', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (28, 'Cahokia - Sand Prairie', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (27, 'Cahokia - Emergent Mississippian I', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (29, 'Oneota', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (296, 'Chagatai Khaganate', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (469, 'Khanate of Bukhara', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (465, 'Ancient Khwarazm', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (464, 'Koktepe I', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (466, 'Koktepe II', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (287, 'Samanid Empire', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (468, 'Sogdiana - City-States Period', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (370, 'Timurid Empire', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (353, 'Himyar - Pagan Period', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (354, 'Himyar - Judaistic Period', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (537, 'Yemen - Late Bronze Age', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (536, 'Neolithic Yemen', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (541, 'Yemen - Qasimid Dynasty', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (539, 'Qatabanian Commonwealth', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (368, 'Yemen - Rasulid Dynasty', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (538, 'Sabaean Commonwealth', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (540, 'Kingdom of Saba and Dhu Raydan', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (372, 'Yemen - Tahirid Dynasty', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (365, 'Era of the War Lords', 'TRS', 'true', 'original_name');
INSERT INTO general_polity_original_name (polity_id, original_name, tag, finalized, name) VALUES (359, 'Banu Ziyad', 'TRS', 'true', 'original_name');