INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (137, 1761, 1761, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (134, 1200, 1200, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (350, -180, -180, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (129, 509, 522, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (281, 420, 440, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (127, 229, 229, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (253, 88, 88, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (254, 280, 300, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (422, -1500, -1450, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (421, -1700, -1530, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('471', None, None, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (470, 1790, 1790, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('245', None, None, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (266, 1207, 1207, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (269, 1450, 1480, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (425, 1050, 1050, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (258, 439, 439, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (1, 1796, 1796, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (2, 1850, 1850, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (243, -1200, -1200, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (260, 609, 609, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (261, 740, 740, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (264, 820, 820, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (424, -353, -353, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (251, -100, -100, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (244, -950, -925, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (268, 1310, 1310, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('196', None, None, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('197', None, None, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (367, 1193, 1193, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (510, -4400, -4000, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (232, 1341, 1341, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (239, 1425, 1425, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (239, 1495, 1495, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (236, 1348, 1348, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (519, -1850, -1850, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('511', None, None, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('512', None, None, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (513, -3300, -3200, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (199, -1250, -1250, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (198, -1300, -1300, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (516, -2400, -2400, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (517, -2300, -2300, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (109, -300, -300, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (518, -2063, -2063, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (203, -550, -550, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (520, -1555, -1555, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (200, -924, -924, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (361, 895, 895, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (84, 1556, 1598, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (208, 250, 250, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (460, 1611, 1611, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (461, 1723, 1743, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (457, 1150, 1150, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (458, 1285, 1314, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (309, 811, 811, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (311, 840, 840, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (449, -900, -900, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (304, 543, 543, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (456, 751, 751, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (306, 584, 629, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (453, -450, -450, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (454, -200, -200, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (455, -125, -125, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (333, 1364, 1380, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (459, 1515, 1515, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (99, 1815, 1815, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (113, 1650, 1701, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (114, 1800, 1824, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (67, -650, -650, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (68, -350, -350, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (74, 824, 961, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (65, -1200, -1100, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (66, -800, -800, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (69, -250, -250, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (63, -1390, -1300, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (59, -4500, -3000, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (62, -1500, -1450, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (61, -1800, -1700, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (64, -1300, -1200, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (60, -2300, -1900, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (17, 1200, 1200, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (18, 1580, 1580, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('153', None, None, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (154, 1900, 1946, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (46, 100, 100, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (50, 1389, 1389, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (48, 850, 850, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (103, -1550, -1550, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (110, -105, -105, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (105, -855, -855, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (92, 609, 643, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (94, 1076, 1126, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (135, 1296, 1316, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('111', None, None, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (112, 1867, 1900, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (388, 400, 400, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (95, 1225, 1225, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (91, 435, 455, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (87, -269, -232, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (98, 1630, 1707, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (93, 814, 878, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (89, 106, 130, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (90, 510, 510, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (97, 1505, 1542, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (132, 809, 809, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (484, 1226, 1226, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (476, -2190, -2154, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (479, -1792, -1750, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (342, -1359, -1333, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (481, -1005, -989, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('475', None, None, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (480, -1119, -1098, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (106, -668, -668, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (346, -604, -562, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (473, -5000, -4000, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (477, -2097, -2038, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (474, -3200, -3050, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (107, -500, -500, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (508, 1453, 1478, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (362, 983, 983, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (507, 100, 100, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (172, 1316, 1316, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (499, -1158, -1158, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (500, -1300, -1300, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (501, -1158, -1158, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (504, -743, -717, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (125, -120, -120, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (483, 50, 100, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (509, 1900, 1900, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (374, 1629, 1629, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (128, 309, 379, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (130, 570, 570, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (108, -281, -281, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (108, -190, -190, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (364, 1092, 1092, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (497, -1900, -1800, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('115', None, None, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (186, 525, 525, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (189, 1030, 1030, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (190, 1240, 1240, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (192, 1571, 1571, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (193, 1750, 1750, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (191, 1506, 1506, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (187, 640, 640, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (182, -287, -287, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (184, -49, -49, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (183, -133, -133, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (70, 117, 117, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (181, -535, -535, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (185, 439, 439, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (188, 850, 900, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (544, 1481, 1550, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (545, 1565, 1565, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (149, 1368, 1394, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (147, 794, 930, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (148, 1225, 1225, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (263, 781, 794, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (150, 1568, 1568, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (152, 1688, 1704, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (144, 125, 125, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (289, 1068, 1068, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (41, 1150, 1220, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (40, 900, 900, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (42, 1220, 1353, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (43, 1400, 1400, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (39, 650, 650, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (37, 250, 514, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (38, 450, 650, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('35', None, None, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('36', None, None, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (104, -570, -570, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (432, 1578, 1603, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (434, 1800, 1800, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (427, 49, 49, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (428, 399, 399, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (430, 899, 899, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (431, 1100, 1100, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (229, 1312, 1337, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (433, 1650, 1680, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (242, 1550, 1550, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (267, 1251, 1259, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (442, 1206, 1206, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (278, 402, 429, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (440, 691, 716, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (438, 155, 155, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (444, 1679, 1745, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('224', None, None, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (216, 1025, 1050, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (526, -100, -100, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (527, -200, -200, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('8', None, None, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (10, -200, -200, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (9, -650, -650, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (523, -1150, -850, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (522, -1400, -1150, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('116', None, None, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (79, 600, 600, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (81, 1250, 1250, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (82, 1400, 1400, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (77, 200, 200, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (83, 1525, 1525, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (80, 800, 800, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('445', None, None, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (446, 1921, 1942, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('117', None, None, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('118', None, None, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (126, -155, -130, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('120', None, None, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (133, 985, 985, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (136, 1486, 1486, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (121, -2500, -2100, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (122, -1800, -1300, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('194', None, None, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (195, 1850, 1900, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (521, -663, -663, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (131, 724, 724, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (44, 1733, 1758, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (45, 1793, 1810, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (221, 996, 996, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (221, 1058, 1058, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('160', None, None, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (163, -1450, -1450, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (161, -1850, -1750, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (73, 741, 775, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (75, 1025, 1025, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (76, 1180, 1180, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (170, -302, -95, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('158', None, None, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('159', None, None, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (72, 527, 542, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (164, -1240, -1240, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (168, -560, -560, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (169, -306, -281, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('156', None, None, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('155', None, None, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('165', None, None, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (173, 1402, 1402, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (174, 1517, 1517, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (175, 1520, 1566, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (176, 1683, 1683, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (166, -738, -696, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (71, 394, 394, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (171, 1220, 1237, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (32, 1100, 1100, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (33, 1200, 1200, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (101, 1650, 1701, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (102, 1714, 1765, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (20, 1810, 1810, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (22, 150, 150, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (34, 1050, 1050, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (25, 600, 600, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (23, 300, 300, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (26, 750, 750, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (24, 450, 450, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (27, 900, 900, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (287, 942, 942, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (468, 700, 700, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (370, 1449, 1449, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (353, 300, 300, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (354, 378, 378, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (368, 1300, 1350, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (365, 1067, 1091, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (359, 1000, 1000, 'TRS', 'true', 'peak_date');