INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (137, 'Afsharid Dynasty', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (350, 'Seleucid Empire', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (129, 'Sassanid Empire I', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (281, 'Sassanid Empire I', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (127, 'Tocharians', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (467, 'Sakas', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (253, 'Xin Dynasty', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (254, 'Later Wei Dynasty', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (422, 'Erlitou', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (421, 'Longshan', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (471, 'Hmong - Late Qing', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (470, 'Hmong - Early Qing', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (245, 'Western Zhou', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (420, 'Yangshao', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (266, 'Khitan Empire', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (269, 'Great Yuan', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (425, 'China - Five Dynasties Period', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (258, 'Dai', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (1, 'Great Ming', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (2, 'Early Qing', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (243, 'Erligang period', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (260, 'Northern Zhou', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (261, 'Sui Dynasty', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (264, 'Early Tang Dynasty', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (424, 'Jin Dynasty', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (251, 'Imperial Qin', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (244, 'Late Shang', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (419, 'Peiligang', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (268, 'Mongol Empire', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (435, 'Malambo', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (436, 'Neguanje', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (196, 'Shuar Tribes', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (197, 'Shuar - Colonial', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (367, 'Abbasid Caliphate I', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (510, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (514, 'Egypt - Dynasty 0', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (515, 'Egypt - Dynasty I', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (205, 'Achaemenid Empire', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (232, 'Ayyubid Sultanate', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (239, 'Egypt - Mamluk Sultanate II', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (236, 'Egypt - Mamluk Sultanate I', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (519, 'Egypt - Period of the Regions', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (511, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (512, 'Naqada I', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (513, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (199, 'Egypt - New Kingdom Thutmosid Period', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (198, 'Egypt - Thebes-Hyksos Period', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (516, 'Egypt - Dynasty II', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (517, 'Egypt - Classic Old Kingdom', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (109, 'Macedonian Empire', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (207, 'Ptolemaic Kingdom I', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (518, 'Egypt - Late Old Kingdom', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (203, 'Neo-Assyrian Empire', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (520, 'Egypt - Middle Kingdom', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (200, 'Egypt - New Kingdom Ramesside Period', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (361, 'Abbasid Caliphate I', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (84, 'Crown of Castile and Aragon', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (208, 'Pre-Aksumite Period', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (57, 'Moen Culture', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (58, 'FmTrukE', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (448, 'Beaker Culture', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (447, 'Late Neolithic Europe', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (460, 'French Kingdom - Late Valois', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (461, 'French Kingdom - Early Bourbon', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (457, 'Carolingian Empire II', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (458, 'Proto-French Kingdom', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (309, 'Proto-Carolingian', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (311, 'Carolingian Empire I', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (449, 'Atlantic Complex', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (450, 'Hallstatt A-B1', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (451, 'Hallstatt B', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (452, 'Hallstatt C', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (304, 'Roman Late Antiquity', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (456, 'Middle Merovingian', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (306, 'Early Merovingian', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (453, 'Hallstatt D', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (454, 'La Tene A-B1', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (455, 'La Tene B2-C1', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (333, 'French Kingdom - Late Capetian', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (459, 'French Kingdom - Early Valois', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (99, 'First British Empire', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (113, 'Akan States', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (114, 'Akan - Pre-Ashanti', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (67, 'Geometric Crete', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (68, 'Archaic Crete', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (74, 'Middle Byzantine Empire', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (65, 'Postpalatial Crete', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (66, 'Mycenaean Crete', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (69, 'Cretan city-states', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (63, 'Neopalatial Crete', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (59, 'Mesolithic Crete', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (62, 'Old Palace Crete', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (61, 'Prepalatial Crete', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (64, 'Monopalatial Crete', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (60, 'Neolithic Crete', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (17, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (18, 'Hawaii I', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (19, 'Hawaii II', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (153, 'Iban Communities', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (154, 'Sultanate of Brunei', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (47, 'Java - Buni Culture', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (49, 'Kahuripan Kingdom', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (50, 'Singhasari Kingdom', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (51, 'Demak Sultanate', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (48, 'Kalingga Kingdom', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (103, 'Intermediate Bronze-Age Canaan', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (110, 'Seleucid Empire', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (105, 'Ancient Phoenicia', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (92, 'Kadamba Empire', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (94, 'Rashtrakuta Empire', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (86, 'Deccan - Neolithic', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (88, 'Deccan - Iron Age', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (135, 'Principality of Gur', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (111, 'A’chik Tribes', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (112, 'Mechpara and Karaibari Zamindars', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (95, 'Chalukyas of Kalyani', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (91, 'Pallava Empire', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (96, 'Hoysala Empire', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (87, 'Nanda Empire', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (98, 'Timurid Empire', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (93, 'Chalukyas of Badami', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (89, 'Mauryan Empire', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (90, 'Satavahana Empire', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (97, 'Delhi Sultanate', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (132, 'Umayyad Caliphate', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (484, 'Seljuk Empire', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (476, 'Lagash Dynasty', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (479, 'Isin', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (342, 'Sealand', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (481, 'Second Sealand Dynasty', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (482, 'Elamite Dynasty', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (475, 'Uruk', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (480, 'IqBabKs', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (478, 'IqUrIII', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (346, 'IqNAssr', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (473, 'Samarra and Halaf culture', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (477, 'Gutian Dynasty', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (474, 'Ubaid', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (107, 'Median Empire', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (508, 'Kara Koyunlu', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (487, 'Formative Period', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (495, 'Susa III', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (362, 'Abbasid Caliphate I', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (502, 'Elam - Inshushinak Period', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (507, 'Parthian Empire I', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (486, 'Pre-Ceramic Period', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (172, 'Seljuk Empire', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (488, 'Susiana - Muhammad Jaffar', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (489, 'Susiana A', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (491, 'Susiana - Early Ubaid', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (490, 'Susiana B', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (499, 'Elam - Late Sukkalmah', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (500, 'Elam - Kidinuid Period', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (501, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (503, 'Elam - Crisis Period', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (504, 'Elam - Neo-Elamite I', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (505, 'Neo-Assyrian Empire', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (125, 'Confederacy of the Dahae', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (483, 'Parthian Empire I', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (509, 'Zandiyeh', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (374, 'Ak Koyunlu', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (128, 'Parthian Empire II', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (130, 'Sassanid Empire I', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (108, 'Macedonian Empire', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (364, 'Kara-Khanids', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (496, 'Ur - Dynasty III', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (497, 'Sumer', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (498, 'Elam - Early Sukkalmah', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (492, 'Susiana - Late Ubaid', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (493, 'Susa I', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (494, 'Susa II', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (115, 'Early Settlers', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (179, 'Latium - Copper Age', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (178, 'Latium - Neolithic', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (180, 'Latium - Bronze Age', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (186, 'Rome - Late Antiquity', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (189, 'Rome - Republic of St Peter I', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (190, 'Rome - Republic of St Peter II', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (192, 'Papal States - Renaissance Period', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (193, 'ItPapM1', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (191, 'Rome - Republic Restoration Period', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (187, 'East Roman Empire', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (182, 'Roman Kingdom', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (184, 'Middle Roman Republic', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (183, 'Early Roman Republic', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (70, 'Ptolemaic Kingdom II', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (181, 'Latium - Iron Age', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (185, 'Roman Empire-Dominate', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (188, 'Exarchate of Ravenna', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (544, 'Venetian Republic', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (149, 'Japan - Kemmu Restoration', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (146, 'Kanai - Kofun Period', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (151, 'Japan - Sengoku Jidai', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (147, 'Kansai - Nara Period', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (138, 'Soso-ki', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (139, 'Incipient Jomon', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (140, 'Japan - Initial Jomon', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (141, 'Japan - Early Jomon', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (142, 'Japan - Middle Jomon', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (143, 'Japan - Late Jomon', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (148, 'Kansai - Heian Period', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (145, 'Kansai - Yayoi Period', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (263, 'Kansai - Asuka Period', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (150, 'Ashikaga Shogunate', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (152, 'Japan - Azuchi-Momoyama', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (144, 'Japan - Final Jomon', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (289, 'Samanid Empire', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (282, 'First Turk Khaganate', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (41, 'Early Angkor', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (40, 'Chenla', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (42, 'Classical Angkor', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (43, 'Late Angkor', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (39, 'Funan II', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (37, 'Iron Age chiefdoms', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (38, 'Funan I', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (463, 'Sarazm', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (104, 'Canaan', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (432, 'Principality of Saadi', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (434, 'Segou Kingdom', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (427, 'suspected unknown', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (428, 'Jenne-jeno I', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (430, 'Jenne-jeno II', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (431, 'Jenne-Jeno III', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (229, 'Sosso Kingdom', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (433, 'suspected unknown', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (242, 'Songhai Empire - Sonni Dynasty', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (283, 'First Turk Khaganate', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (288, 'Uigur Khaganate', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (267, 'Early Mongols', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (442, 'Khitan Empire', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (443, 'Great Yuan', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (278, 'Xianbei Confederation', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (439, 'Eastern Turk Khaganate', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (440, 'Tang Dynasty', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (286, 'Second Turk Khaganate', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (438, 'Donghu', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (274, 'Xiongnu Imperial Confederation', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (272, 'MnXngnE', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (444, 'Khalkhas', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (224, 'Ghana I', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (216, 'Wagadu', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (525, 'MxRosar', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (526, 'MxAlb1E', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (527, 'MxAlb1L', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (528, 'MxAlb2*', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (529, 'MxAlb3A', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (532, 'Monte Alban IIIB and IV', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (12, 'MxCuicu', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (8, 'MxInitl', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (10, 'MxFormM', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (9, 'MxFormE', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (11, 'MxFormL', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (7, 'MxArch*', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (524, 'MxSanGu', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (523, 'MxTieLa', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (522, 'Archaic Period', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (116, 'Icelandic Commonwealth', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (78, 'PeCuzLF', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (79, 'PeCuzE1', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (81, 'PeWari*', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (82, 'PeCuzL1', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (77, 'Cuzco - Formative', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (83, 'PeCuzL2', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (80, 'PeCuzE2', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (445, 'Orokaiva Tribes', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (446, 'Orokaiva - Pre-Colonial', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (117, 'not applicable', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (118, 'Kachi Plain - Aceramic Neolithic', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (119, 'not applicable', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (126, 'Graeco-Bactrian Kingdom', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (123, 'Kachi Plain - Urban Period II', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (120, 'Kachi Plain - Chalcolithic', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (124, 'Post-Urban Period', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (136, 'Delhi Sultanate', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (121, 'Kachi Plain - Pre-Urban Period', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (122, 'Kachi Plain - Urban Period I', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (194, 'Kurumchi Culture', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (195, 'Sakha Tribes', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (521, 'Egypt - Thebes-Libyan Period', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (131, 'Rashidun Caliphate', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (44, 'Ayutthaya', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (45, 'Ayutthaya', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (221, 'Abbasid Caliphate I', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (160, 'Konya Plain - Late Chalcolithic', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (163, 'Hatti - Old Kingdom', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (161, 'KonyEBA', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (73, 'East Roman Empire', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (75, 'Byzantine Empire I', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (76, 'Byzantine Empire II', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (170, 'Seleucid Empire', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (158, 'Konya Plain - Late Neolithic', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (159, 'Konya Plain - Early Chalcolithic', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (72, 'Roman Empire - Dominate', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (164, 'Konya Plain - Late Bronze Age II', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (162, 'Konya Plain - Late Bronze Age I', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (168, 'Konya Plain - Cimmerian Period', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (169, 'Macedonian Empire', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (156, 'Konya Plain - Early Neolithic', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (157, 'Konya Plain - Ceramic Neolithic', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (165, 'Hatti - New Kingdom', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (173, 'Late Byzantine', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (173, 'Karamanid Emirate', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (174, 'Ottoman Emirate', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (175, 'Ottoman Empire I', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (176, 'Ottoman Empire II', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (166, 'Tabal Kingdoms', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (71, 'Roman Empire - Principate', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (171, 'Bzyantine Empire III', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (167, 'Neo-Hittite Kingdoms', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (32, 'Cahokia - Emergent Mississippian II', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (33, 'Cahokia - Lohmann-Stirling', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (30, 'Oneota', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (101, 'Iroquois Confederacy', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (102, 'Iroquois Confederacy', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (20, 'Hawaii III', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (22, 'Cahokia - Prairie Lake', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (34, 'Cahokia - Emergent Mississippian I', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (25, 'Cahokia - Late Woodland I', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (23, 'Cahokia - Early Woodland', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (26, 'Cahokia - Late Woodland II', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (24, 'Cahokia - Middle Woodland', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (28, 'Cahokia - Moorehead', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (27, 'Cahokia - Late Woodland III', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (29, 'Cahokia - Sand Prairie', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (296, 'Mongolian Empire', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (469, 'Shaybanid Kingdom', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (465, 'Koktepe I', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (464, 'Andronovo', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (466, 'Ancient Khwarazm', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (287, 'Abbasid Caliphate I', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (468, 'Western Turk Khaganate', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (370, 'Chagatai Khaganate', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (353, 'EtAksm1', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (354, 'YeHmyr2', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (537, 'YeNeol*', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (541, 'TrOttm3', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (539, 'YeSabaC', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (368, 'EgAyyub', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (538, 'YeLBA***', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (540, 'YeQatab', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (372, 'YeRasul', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (365, 'YeZiyad', 'TRS', 'true', 'preceding_(quasi)polity');
INSERT INTO general_polity_preceding_entity (polity_id, preceding_entity, tag, finalized, name) VALUES (359, 'IqAbbs1', 'TRS', 'true', 'preceding_(quasi)polity');