INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (134, 'Karrami', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (134, 'Hanafi', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (134, 'Shafii', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (253, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (367, 'Shafii', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (232, 'Hanafi', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (239, 'Hanafi', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (236, 'Hanafi', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (309, 'Roman Catholic', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (311, 'Roman Catholic', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (304, 'Roman Catholic', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (306, 'Roman Catholic', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (333, 'Roman Catholic', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (132, 'Hanafi', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (484, 'Hanafi', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (374, 'Twelver', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (189, 'Roman Catholic', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (190, 'Roman Catholic', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (192, 'Roman Catholic', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (193, 'Roman Catholic', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (191, 'Roman Catholic', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (188, 'Roman Catholic', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (289, 'Hanafi', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (133, 'Sunni', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (133, 'Shia', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (136, 'Ismaili', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (131, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (221, 'Ismaili', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (73, 'Roman Catholic', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (75, 'Roman Catholic', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (75, 'Byzantine Orthodox', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (76, 'Byzantine Orthodox', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (72, 'Roman Catholic', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (173, 'Mevlevi', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (173, 'Bektasi', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (174, 'Mevlevi', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (174, 'Bektasi', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (175, 'Hanafi', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (176, 'Hanafi', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (370, 'Hanafi', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (368, 'Islam', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (365, 'Islam', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (359, 'Islam', 'TRS', 'true', 'religion');