INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (134, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (254, 'Imperial Confucian Traditions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (245, 'Chinese Folk Religion', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (266, 'Imperial Confucian Traditions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (425, 'Imperial Confucian Traditions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (258, 'Imperial Confucian Traditions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (243, 'Shang Religion', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (260, 'Imperial Confucian Traditions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (261, 'Imperial Confucian Traditions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (244, 'Western Zhou Religion', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (367, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (232, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (239, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (236, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (198, 'Atenism', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (109, 'Ptolemaic Religion', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (207, 'Ptolemaic Religion', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (361, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (84, 'Catholic', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (309, 'Catholic', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (311, 'Catholic', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (304, 'Catholic', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (306, 'Catholic', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (333, 'Catholic', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (92, 'Saiva Traditions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (94, 'Saiva Traditions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (135, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (388, 'Vaisnava Traditions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (93, 'Saiva Traditions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (89, 'Saivist Traditions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (89, 'Vedist Traditions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (89, 'Bhagavatist Traditions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (385, 'Vedic Traditions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (90, 'Saivist Traditions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (97, 'Saivist Traditions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (97, 'Vaisnava Traditions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (132, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (484, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (482, 'Semitic', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (106, 'Assyrian Religions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (508, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (172, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (172, 'Shii', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (172, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (374, 'Shia', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (108, 'Seleucid Religion', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (364, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (186, 'Arian', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (189, 'Catholic', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (190, 'Catholic', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (192, 'Catholic', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (193, 'Catholic', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (191, 'Catholic', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (182, 'Republican Religions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (184, 'Republican Religions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (183, 'Republican Religions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (70, 'Imperial Cult', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (188, 'Catholic', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (149, 'Japanese State Shinto', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (148, 'Japanese State Shinto', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (263, 'Japanese State Shinto', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (289, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (41, 'Saiva Traditions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (40, 'Saiva Traditions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (42, 'Saiva Traditions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (42, 'Theravada', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (39, 'Saivist', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (37, 'Saivist', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (38, 'Saivist', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (242, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (78, 'suspected unknown', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (79, 'suspected unknown', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (81, 'suspected unknown', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (82, 'suspected unknown', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (77, 'suspected unknown', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (80, 'suspected unknown', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (133, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (133, 'Shia', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (136, 'Shia', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (131, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (221, 'Shia', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (73, 'Catholic', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (75, 'Catholic', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (75, 'Orthodox', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (76, 'Orthodox', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (72, 'Catholic', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (173, 'Sufi', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (174, 'Sufi', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (175, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (176, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (71, 'Imperial Cult', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (171, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (370, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (541, 'Islam', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (368, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (365, 'Shia', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (359, 'Sunni', 'TRS', 'true', 'religion_family');