INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (134, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (350, 'Graeco-Bactrian Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (129, 'Hephthalite Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (281, 'Zoroastrianism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (281, 'Buddhism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (281, 'Hinduism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (127, 'Graeco-Bactrian Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (127, 'Ancient Iranian Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (127, 'Hinduism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (127, 'Buddhism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (127, 'Zoroastrianism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (254, 'Chinese State Religion', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (245, 'Ancient East Asian Religion', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (266, 'Chinese State Religion', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (425, 'Chinese State Religion', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (258, 'Chinese State Religion', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (243, 'Chinese State Religion', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (260, 'Chinese State Religion', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (261, 'Chinese State Religion', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (244, 'Chinese State Religion', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (268, 'Mongolian Shamanism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (367, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (205, 'Egyptian Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (232, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (239, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (236, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (199, 'Egyptian Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (198, 'Egyptian Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (109, 'Hellenistic Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (207, 'Hellenistic Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (203, 'Egyptian Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (200, 'Egyptian Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (361, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (309, 'Christianity', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (311, 'Christianity', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (304, 'Christianity', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (306, 'Christianity', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (333, 'Christianity', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (47, 'Ancient Javanese Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (92, 'Hinduism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (94, 'Hinduism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (135, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (388, 'Hinduism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (87, 'Hinduism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (87, 'Jain Traditions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (87, 'Buddhism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (93, 'Hinduism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (89, 'Hinduism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (385, 'Hinduism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (90, 'Hinduism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (97, 'Hinduism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (132, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (484, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (106, 'Mesopotamian Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (107, 'Zoroastrianism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (508, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (172, 'Buddhism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (172, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (483, 'Zoroastrianism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (374, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (130, 'Zoroastrianism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (108, 'Hellenistic Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (364, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (186, 'Christianity', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (189, 'Christianity', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (190, 'Christianity', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (192, 'Christianity', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (193, 'Christianity', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (191, 'Christianity', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (182, 'Roman State Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (184, 'Roman State Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (183, 'Roman State Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (70, 'Roman State Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (185, 'Christianity', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (188, 'Christianity', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (149, 'Shinto', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (148, 'Shinto', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (263, 'Shinto', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (289, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (282, 'Buddhism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (41, 'Hinduism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (40, 'Hinduism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (42, 'Hinduism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (42, 'Buddhism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (39, 'Hinduism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (37, 'Hinduism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (38, 'Hinduism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (229, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (242, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (283, 'Buddhism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (288, 'Buddhism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (267, 'Mongolian Shamanism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (278, 'Buddhism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (286, 'Manichaeism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (274, 'Xiongnu Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (272, 'Xiongnu Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (126, 'Graeco-Bactrian Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (133, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (136, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (521, 'Egyptian Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (131, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (221, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (163, 'Hittite Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (73, 'Christianity', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (75, 'Christianity', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (76, 'Christianity', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (72, 'Christianity', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (164, 'Hittite Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (162, 'Hittite Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (168, 'Lydian Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (169, 'Hellenistic Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (165, 'Hittite Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (173, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (174, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (175, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (176, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (166, 'Phrygian Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (71, 'Roman State Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (171, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (296, 'Mongolian Shamanism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (370, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (365, 'Ismaili', 'TRS', 'true', 'religion_genus');