INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (84, 'Christianity', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (208, 'South Arabian Religions', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (99, 'Christianity', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (342, 'Mesopotamian Religions', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (481, 'Mesopotamian Religions', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (482, 'Akkadian', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (480, 'Mesopotamian Religions', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (478, 'Mesopotamian Religions', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (346, 'Mesopotamian Religions', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (528, 'Monte Albán Religion', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (529, 'Monte Albán Religion', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (78, 'suspected unknown', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (79, 'suspected unknown', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (81, 'suspected unknown', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (82, 'suspected unknown', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (77, 'suspected unknown', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (83, 'Inca Religion', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (80, 'suspected unknown', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (353, 'South Arabian Religions', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (354, 'Judaism', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (541, 'Sunni Islam', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (539, 'South Arabian Religions', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (538, 'South Arabian Religions', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (540, 'South Arabian Religions', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (372, 'Islam', 'TRS', 'true', 'religious_tradition');