INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (137, 'Barkzai Dynasty', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (350, 'Sakas', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (129, 'First Turk Khaganate', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (281, 'Hephthalite Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (127, 'Sassanid Empire I', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (467, 'Kushan Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (253, 'Wei Dynasty', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (254, 'Northern Wei', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (422, 'Late Shang', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (421, 'Erligang', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (471, 'Peoples Republic of China', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (470, 'Hmong - Early Chinese', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (245, 'Zhao', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (245, 'Wei', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (245, 'Qin', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (420, 'Erlitou', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (266, 'Great Yuan', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (425, 'Later Jin', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (258, 'Western Wei', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (1, 'Late Qing', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (2, 'Republic of China', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (243, 'Western Zhou', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (260, 'Early Tang', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (261, 'Later Tang Dynasty', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (264, 'China - Five Dynasties Period and Ten Kingdoms Period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (424, 'Imperial Qin', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (251, 'Wang Mang interregnum', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (244, 'Zhou Kingdom', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (419, 'Longshan', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (268, 'China - Early Ming', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (435, 'CoTairo', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (436, 'Spanish Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (196, 'Shuar - Ecuadorian', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (197, 'Republic of Ecuador', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (367, 'Egypt - Mamluk Sultanate I', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (510, 'Naqada I', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (514, 'Egypt - Dynasty II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (515, 'Egypt - Classic Old Kingdom', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (205, 'Achaemenid Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (232, 'Egypt - Mamluk Sultanate II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (239, 'Ottoman Empire II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (236, 'Egypt - Mamluk Sultanate III', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (519, 'Egypt - Thebes-Hyksos Period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (511, 'Naqada II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (512, 'Egypt - Dynasty 0', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (513, 'Egypt - Dynasty I', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (199, 'Egypt - Thebes-Libyan Period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (198, 'Ramesside period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (516, 'Egypt - Late Old Kingdom', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (517, 'Egypt - Period of the Regions', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (109, 'Ptolemaic Kingdom II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (207, 'Roman Empire - Principate', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (518, 'Egypt - Middle Kingdom', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (203, 'Achaemenid Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (520, 'Egypt - New Kingdom Thutmosid Period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (200, 'Egypt - Kushite Period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (361, 'Fatimid Caliphate', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (84, 'House of Bourbon-Spain', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (208, 'EtAksm2', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (57, 'FmTrukL', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (58, 'United Nations Trusteeship', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (58, 'Federated States of Micronesia', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (448, 'Hallstatt A-B1', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (447, 'Atlantic Complex', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (460, 'French Kingdom - Late Bourbon', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (461, 'Revolutionary Republic', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (457, 'French Kingdom - Late Capetian', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (458, 'French Kingdom - Early Valois', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (309, 'Carolingian Empire II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (311, 'Proto-French Kingdom', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (449, 'Hallstatt B', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (450, 'Hallstatt C', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (451, 'Hallstatt D', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (452, 'La Tene A-B1', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (304, 'Middle Merovingian', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (456, 'Carolingian Empire I', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (306, 'Proto-Carolingian', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (453, 'La Tene B2-C1', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (454, 'La Tene C2-D', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (455, 'Late Roman Republic', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (333, 'French Kingdom - Late Valois', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (459, 'French Kingdom - Early Bourbon', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (99, 'British Empire - Victorian Period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (113, 'Ashanti Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (114, 'British Empire Gold Coast Colony', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (67, 'Classical Crete', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (68, 'Hellenistic Crete', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (74, 'Middle Byzantine Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (65, 'Geometric Crete', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (66, 'Archaic Crete', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (69, 'Roman Republic', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (63, 'Final Palatial Crete', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (59, 'Prepalatial Crete', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (62, 'Monopalatial Crete', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (61, 'Neopalatial Crete', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (64, 'Final Postpalatial Crete', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (60, 'Protopalatial Crete', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (17, 'Hawaii II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (18, 'Hawaii III', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (19, 'Kingdom of Hawaii - Kamehameha Period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (153, 'Brooke Raj', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (153, 'White Rajahs', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (154, 'Malaysia', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (154, 'Indonesia', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (46, 'Kalingga Kingdom', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (47, 'Medang Kingdom', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (49, 'Singhasari Kingdom', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (50, 'Demak Sultanate', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (48, 'Kahuripan Kingdom', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (103, 'Ancient Phoenicia', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (110, 'Late Roman Republic', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (105, 'Neo-Assyrian Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (92, 'Rashtrakuta Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (94, 'Hoysala Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (86, 'Mauryan Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (88, 'Satavahana Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (85, 'Deccan - Iron Age', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (111, 'British Colonial India', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (112, 'Republic of India', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (95, 'Vijayanagara Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (91, 'Chalukyas of Badami', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (96, 'Vijayanagara Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (87, 'Shunga Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (98, 'Durrani Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (93, 'Chalukyas of Kalyani', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (89, 'Vakataka Kingdom', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (97, 'Mughal Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (132, 'Buyid Confederation', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (484, 'Il-khanate', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (476, 'Gutian Dynasty', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (479, 'Sealand', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (342, 'Middle Elamite Kingdom', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (481, 'Elamite Dynasty', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (482, 'IqNAssr', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (475, 'Akkadian Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (480, 'Second Sealand Dynasty', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (478, 'IqBabAm', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (346, 'IrAchae', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (473, 'Uruk culture', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (477, 'Isin', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (474, 'Early Dynastic Sumer', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (107, 'Macedonian Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (508, 'Safavid Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (487, 'Susiana A', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (495, 'Akkadian Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (362, 'Seljuk Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (502, 'Elam - Dark Age', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (486, 'Archaic Period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (172, 'Chobanids', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (488, 'Susiana B', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (489, 'Susiana - Early Ubaid', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (491, 'Susa I', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (490, 'Susiana - Late Ubaid', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (499, 'Neo-Assyrian Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (500, 'Neo-Assyrian Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (501, 'Neo-Assyrian Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (503, 'Elam - Neo-Elamite II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (504, 'Neo-Assyrian Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (505, 'Achaemenid Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (125, 'Parthian Empire II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (483, 'Sassanid Empire I', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (485, 'Formative Period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (374, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (128, 'Sassanid Empire II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (130, 'Rashidun Caliphate', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (108, 'Parthian Empire I', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (364, 'Il-Khanate', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (496, 'Elam - Early Sukkalmah', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (497, 'Elam - Late Sukkalmah', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (498, 'Elam - Kidinuid Period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (492, 'Susa II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (493, 'Susa III', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (494, 'Elam - Awan Dynasty I', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (115, 'Kingdom of Norway', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (179, 'Latium - Iron Age', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (178, 'Latium - Bronze Age', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (180, 'Roman Kingdom', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (186, 'East Roman Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (189, 'Papal State I', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (190, 'Rome - Republic Restoration Period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (192, 'Papal States - Medieval Period II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (193, 'Napoleonic Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (191, 'Papal States - Medieval Period I', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (187, 'Republic of St Peter', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (182, 'Middle Roman Republic', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (184, 'Roman Empire - Principate', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (183, 'Late Roman Republic', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (70, 'Roman Empire - Dominate', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (181, 'Early Roman Republic', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (185, 'Roman Empire - Late Antiquity', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (188, 'Rome - Republic of St Peter II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (544, 'Venetian Republic', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (149, 'Japan - Sengoku Jidai', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (146, 'Kansai - Nara Period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (151, 'Tokugawa Shogunate', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (147, 'Kamakura Shogunate', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (138, 'Japan - Initial Jomon', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (139, 'Early Jomon', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (140, 'Japan - Middle Jomon', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (141, 'Japan - Late Jomon', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (142, 'Japan - Final Jomon', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (143, 'Kansai - Yayoi Period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (148, 'Japan - Kemmu Restoration', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (145, 'Kansai - Asuka Period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (263, 'Kansai - Heian Period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (150, 'Japan - Azuchi-Momoyama', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (152, 'Japan - Meiji Restoration', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (144, 'Kansai - Kofun Period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (289, 'Khwarezmid Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (282, 'Sogdiana - City-States Period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (41, 'Late Angkor', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (40, 'Classical Angkor', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (42, 'Khmer Kingdom', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (43, 'Ayutthaya', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (39, 'Early Angkor', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (37, 'Funan II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (38, 'Zhenla', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (463, 'Yaz I', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (104, 'Macedonian Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (432, 'Alaouite Dynasty', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (434, 'Toucouleur Kingdom', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (427, 'Jenne-jeno II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (428, 'Jenne-jeno III', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (430, 'Jenne-Jeno IV', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (431, 'Sosso Kingdom', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (229, 'Mande States', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (433, 'Bamana Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (242, 'Saadi Dynasty', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (283, 'Tang Dynasty', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (288, 'Early Mongols', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (267, 'Great Yuan', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (442, 'Mongol Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (443, 'Zungharian Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (278, 'First Turk Khaganate', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (439, 'Khitan Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (440, 'Uighur Khaganate', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (286, 'Khitan Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (438, 'Rouran Khaganate', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (437, 'Xiongnu Imperial Confederation', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (274, 'Xianbei Confederation', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (272, 'MnXngnL', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (444, 'China - Early Qing', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (224, 'Mali Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (216, 'Ghana II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (525, 'MxAlb1L', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (526, 'MxAlb2*', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (527, 'MxAlb3A', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (528, 'MxAlb3B', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (529, 'Zapotec', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (529, 'Monte Albán V', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (532, 'Spanish colonial rule', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (6, 'MxInitl', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (12, 'MxEpicl', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (8, 'MxFormM', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (10, 'MxFormT', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (9, 'MxCuicu', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (11, 'MxClass', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (7, 'MxFormE', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (524, 'MxAlb1E', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (523, 'MxRosar', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (522, 'MxSanGu', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (116, 'Kalmar Union', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (78, 'PeCuzE2', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (79, 'PeWari*', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (81, 'PeCuzL2', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (82, 'PeInca*', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (77, 'PeCuzE1', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (83, 'EsHabsb', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (80, 'PeCuzL1', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (445, 'Orokaiva - Colonial', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (446, 'Australian Territory of Papua and New Guinea', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (446, 'Independent State of Papua New Guinea', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (117, 'Kachi Plain - Ceramic Neolithic', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (118, 'Kachi Plain - Chalcolithic', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (119, 'not applicable', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (126, 'Parthian Empire I', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (123, 'Kachi Plain - Proto-Historic Period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (120, 'Kachi Plain - Urban Period I', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (124, 'Achaemenid Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (136, 'Mughal Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (121, 'Kachi Plain - Urban Period II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (122, 'Kachi Plain - Post-Urban Period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (194, 'Czarist Russia', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (195, 'Czarist Russia', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (195, 'USSR', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (521, 'Neo-Assyrian Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (131, 'Abbasid Caliphate I', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (44, 'Rattanakosin', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (45, 'Rattanakosin - Reform Period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (462, 'Andronovo', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (221, 'Ayyubid Sultanate', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (160, 'Konya Plain - Middle Bronze Age', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (163, 'Hatti - New Kingdom', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (161, 'KonLBA1', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (73, 'Byzantine Empire II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (75, 'Byzantine Empire III', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (76, 'Latin Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (170, 'Late Roman Republic', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (158, 'Konya Plain - Late Chalcolithic', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (159, 'Konya Plain - Early Bronze Age', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (72, 'Byzantine Empire I', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (164, 'Neo-Hittite Kingdoms', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (162, 'Konya Plain - Late Bronze Age II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (169, 'Seleucid Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (156, 'Konya Plain - Late Neolithic', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (155, 'Konya Plain - Ceramic Neolithic', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (157, 'Konya Plain - Early Chalcolithic Neolithic', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (165, 'Tabal Kingdoms', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (173, 'Ottoman Empire I', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (174, 'Ottoman Empire II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (175, 'Ottoman Empire III', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (176, 'Ottoman Empire IV', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (166, 'Konya Plain - Cimmerian Period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (71, 'Western Roman Empire - Late Antiquity', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (171, 'Mongol Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (167, 'Assyrian Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (32, 'Cahokia - Moorehead', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (33, 'Cahokia - Sand Prairie', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (30, 'Late Illinois Confederation', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (101, 'Iroquois Confederacy', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (102, 'United States of America', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (22, 'Cahokia - Middle Woodland', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (34, 'Cahokia - Lohmann-Stirling', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (25, 'Cahokia - Late Woodland III', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (23, 'Cahokia - Late Woodland I', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (26, 'Cahokia - Emergent Mississippian I', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (24, 'Cahokia - Late Woodland II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (28, 'Oneota', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (27, 'Merrell-Edlehardt', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (29, 'Early Illinois Confederation', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (296, 'Timurid Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (469, 'Manghits', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (465, 'Achaemenid Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (464, 'Koktepe II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (466, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (287, 'Kara-Khanids', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (468, 'Umayyad Caliphate', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (370, 'Shaybanid Kingdom', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (353, 'YeHmyr2', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (354, 'EtAksm1', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (537, 'YeSabaC', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (541, 'TrOttm4', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (539, 'YeSaRay', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (368, 'YeTahir', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (538, 'YeQatab', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (540, 'EtAksm1', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (372, 'TrOttm3', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (365, 'EgAyyub', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (359, 'YeWarLd', 'TRS', 'true', 'succeeding_(quasi)polity');