INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (137, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (134, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (134, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (350, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (129, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (129, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (281, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (281, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (127, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (127, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (253, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (254, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (422, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (421, 'suspected unknown', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (471, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (470, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (245, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (245, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (266, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (269, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (425, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (258, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (1, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (2, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (243, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (260, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (261, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (264, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (424, 'nominal', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (251, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (251, 'personal union', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (251, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (244, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (244, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (268, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (435, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (436, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (196, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (196, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (197, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (367, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (510, 'suspected unknown', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (514, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (515, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (205, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (232, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (239, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (236, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (519, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (511, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (512, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (513, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (199, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (198, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (516, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (517, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (109, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (207, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (518, 'nominal', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (518, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (203, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (520, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (200, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (361, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (361, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (208, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (208, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (57, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (58, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (448, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (447, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (460, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (461, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (457, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (458, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (311, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (449, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (450, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (451, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (452, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (304, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (456, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (306, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (453, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (454, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (455, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (333, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (459, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (99, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (113, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (114, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (67, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (74, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (66, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (63, 'suspected unknown', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (64, 'suspected unknown', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (17, 'suspected unknown', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (18, 'suspected unknown', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (153, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (154, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (154, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (154, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (47, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (48, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (103, 'unknown', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (103, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (103, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (103, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (110, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (110, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (110, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (105, 'personal union', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (105, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (105, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (105, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (105, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (92, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (94, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (135, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (111, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (112, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (388, 'Nominal', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (388, 'Alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (95, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (95, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (91, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (96, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (87, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (98, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (93, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (89, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (90, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (97, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (132, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (484, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (476, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (342, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (342, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (481, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (482, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (475, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (480, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (478, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (106, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (473, 'suspected unknown', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (477, 'personal union', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (477, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (474, 'suspected unknown', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (107, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (508, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (487, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (495, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (495, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (362, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (502, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (486, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (172, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (172, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (500, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (501, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (504, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (504, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (125, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (483, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (485, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (374, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (128, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (130, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (108, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (364, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (496, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (497, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (498, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (115, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (186, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (186, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (189, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (190, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (192, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (193, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (191, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (187, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (187, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (182, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (184, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (184, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (183, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (70, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (181, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (185, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (188, 'nominal', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (544, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (149, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (146, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (151, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (147, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (148, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (145, 'uncoded', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (263, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (150, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (152, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (144, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (289, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (289, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (289, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (282, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (41, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (40, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (42, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (43, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (39, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (37, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (38, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (35, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (36, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (463, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (104, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (104, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (104, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (104, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (427, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (428, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (430, 'suspected unknown', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (431, 'suspected unknown', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (229, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (242, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (283, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (267, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (442, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (442, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (278, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (440, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (286, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (286, 'personal union', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (438, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (444, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (216, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (525, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (526, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (527, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (528, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (529, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (532, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (532, 'personal union', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (16, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (13, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (8, 'unknown', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (8, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (10, 'suspected unknown', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (9, 'unknown', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (9, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (11, 'suspected unknown', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (524, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (523, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (522, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (116, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (78, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (79, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (81, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (82, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (77, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (83, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (83, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (80, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (445, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (446, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (117, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (118, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (119, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (126, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (123, 'unknown', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (120, 'unknown', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (124, 'unknown', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (133, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (133, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (133, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (136, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (136, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (136, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (121, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (122, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (194, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (195, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (521, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (131, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (44, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (45, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (462, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (221, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (160, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (161, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (73, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (75, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (76, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (170, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (170, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (170, 'personal union', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (170, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (158, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (72, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (168, 'personal union', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (168, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (169, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (169, 'personal union', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (169, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (156, 'unknown', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (155, 'unknown', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (165, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (173, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (173, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (173, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (174, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (175, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (166, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (71, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (171, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (171, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (167, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (167, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (32, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (33, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (30, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (101, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (101, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (102, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (20, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (20, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (22, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (34, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (25, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (23, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (26, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (24, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (28, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (27, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (469, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (287, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (287, 'nominal', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (468, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (468, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (370, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (353, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (353, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (354, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (541, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (368, 'nominal', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (368, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (365, 'nominal', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (359, 'nominal', 'TRS', 'true', 'supra-polity_relations');