INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (350, 'Greek', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (129, 'Steppe nomads', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (281, 'Eurasian nomadic', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (281, 'Persian', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (281, 'Indian', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (127, 'Greco-Persian', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (467, 'Greco-Persian', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (253, 'Chinese', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (254, 'Chinese', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (422, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (421, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (471, 'East Asia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (470, 'China', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (245, 'China', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (420, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (266, 'China', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (269, 'China', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (425, 'China', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (258, 'Xianbei', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (1, 'China', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (2, 'China', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (243, 'China', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (260, 'Chinese', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (261, 'China', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (264, 'China', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (424, 'Chinese', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (251, 'China', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (419, 'China', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (268, 'China', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (435, 'Caribbean Colombia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (435, 'Central America-northern South America interaction sphere', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (436, 'Chibchan region', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (196, 'Amazonia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (197, 'Amazonia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (367, 'Islam', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (205, 'Egypt', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (232, 'Islam', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (239, 'Islam', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (236, 'Islam', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (512, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (199, 'Egyptian Civilization', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (109, 'Greek World', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (207, 'Greek World', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (203, 'Egypt', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (200, 'Libyan tribes', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (361, 'Islam', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (57, 'Micronesia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (58, 'Micronesia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (448, 'Bronze Age Europe', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (447, 'Chalcolithic', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (447, 'Late Neolithic', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (457, 'Latin Christendom', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (458, 'Latin Christendom', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (309, 'Latin Christendom', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (311, 'Latin Christendom', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (449, 'Hallstatt', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (450, 'Hallstatt', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (451, 'Hallstatt', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (452, 'Hallstatt', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (304, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (453, 'La Tene', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (454, 'La Tene', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (455, 'La Tene', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (333, 'Christendom', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (99, 'Anglosphere', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (113, 'West Africa', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (114, 'West Africa', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (67, 'Archaic Greece', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (68, 'Classical Greece', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (74, 'Christianity and Islam', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (65, 'Cretan Broze Age Civilization', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (66, 'Early Iron Age Greece/Geometric Greece', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (69, 'Hellenistic Greece', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (63, 'Cretan Broze Age Civilization', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (62, 'Cretan Broze Age Civiliazation or Minoan Civilazation', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (61, 'Cretan Broze Age Civilization', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (64, 'Cretan Broze Age Civilization', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (60, 'Cretan Broze Age Civilization', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (153, 'South-East Asia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (154, 'South-East Asia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (46, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (50, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (48, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (103, 'Amorite Near East', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (110, 'Jewish diaspora', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (105, 'Israelite', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (135, 'Persian', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (135, 'Turkish', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (135, 'Islamic', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (111, 'South Asia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (112, 'South Asia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (87, 'Hinduism', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (132, 'Perso-Islamic', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (484, 'Perso-Islamic', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (479, 'Mesopotamia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (342, 'Mesopotamia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (474, 'suspected unknown', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (107, 'Persian', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (495, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (362, 'Perso-Islamic', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (172, 'Mongolian', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (499, 'Mesopotamia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (499, 'Iran', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (500, 'Mesopotamia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (500, 'Iran', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (501, 'Mesopotamia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (501, 'Iran', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (125, 'Greco-Bactrian', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (483, 'Greco-Bactrian', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (374, 'Turco-Mongol', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (374, 'Perso-Islamic', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (374, 'Shia-Islamic', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (128, 'Persian', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (130, 'Persian', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (108, 'Greek', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (364, 'Perso-Islamic', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (497, 'Amorite world', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (493, 'Sumerian', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (494, 'Sumerian', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (115, 'Scandinavia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (115, 'Norden', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (115, 'Latin Christendom', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (179, 'Appenine culture', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (180, 'Latial Culture', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (189, 'Latin Christendom', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (190, 'Christendom', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (192, 'Roman Catholicism', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (193, 'Roman Catholicism', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (191, 'Christendom', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (187, 'Roman', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (182, 'Latin States', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (184, 'Roman', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (183, 'Roman', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (70, 'Greco-Roman', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (181, 'Hellenistic Civilization', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (185, 'Roman', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (188, 'Latin Christendom', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (544, 'Christiandom', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (149, 'Japanese', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (146, 'T''ang China', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (146, 'Korea', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (151, 'Japanese', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (147, 'Tang China', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (148, 'none', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (145, 'Initial Kofun Package', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (263, 'T''ang China', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (150, 'Japanese', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (152, 'Japanese', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (144, 'Western horizon', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (289, 'Perso-Islamic', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (41, 'Indianized Southeast Asia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (40, 'Indianized Southeast Asia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (42, 'Indianized Southeast Asia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (43, 'Indianized Southeast Asia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (39, 'Indianized Southeast Asia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (37, 'Chinese cultural sphere', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (37, 'Indian cultural sphere', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (38, 'Chinese cultural sphere', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (463, 'Andronovan', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (104, 'Phoenician', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (432, 'Arabic', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (432, 'Islamic', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (427, 'Sahel Tell Culture', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (428, 'Sahel Tell Culture', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (430, 'Jenne Culture', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (431, 'Jenne Culture', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (229, 'Mande', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (242, 'Mande', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (242, 'Islamic', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (267, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (443, 'Mongols', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (286, 'Turko-Sogdian', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (438, 'proto-Mongolian Donghu', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (437, 'Early Nomadic', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (444, 'Oirats', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (224, 'Mande', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (216, 'Mande', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (528, 'Zapotec', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (10, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (9, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (11, 'Central Highland Mesoamerican Late-Terminal Formative', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (524, 'Middle Formative', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (523, 'Early Formative', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (522, 'Early Formative', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (116, 'Latin Christendom', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (78, 'Lake Titicaca cultural sphere', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (79, 'Lake Titicaca cultural sphere', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (81, 'Wari cultural sphere', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (82, 'Lake Titicaca cultural sphere', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (77, 'Lake Titicaca cultural sphere', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (80, 'Middle Horizon', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (445, 'Melanesia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (446, 'Melanesia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (119, 'not applicable', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (120, 'Indus Civilisation', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (124, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (121, 'Indus Civilisation', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (122, 'Indus Civilisation', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (194, 'Siberia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (195, 'Siberia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (521, 'Nubia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (131, 'Islam', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (44, 'Indianized Southeast Asia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (45, 'Indianized Southeast Asia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (221, 'Islam', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (73, 'Christianity', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (75, 'Christianity', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (76, 'Christianity', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (72, 'Christianity', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (164, 'Hittite', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (168, 'Achaemenid Empire', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (169, 'Greek', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (165, 'Neo-Hittite', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (173, 'Turkic', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (173, 'Islamic', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (173, 'Persian', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (174, 'Turkish', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (174, 'Islamic', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (175, 'Turkish', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (176, 'Turkish', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (71, 'Greco-Roman', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (171, 'Islam', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (167, 'Neo-Hittite', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (32, 'Middle Mississippian', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (33, 'Middle Mississippian', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (101, 'Eastern Woodlands', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (102, 'Eastern Woodlands', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (20, 'Kingdom of Hawaii - Post-Kamehameha Period', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (22, 'Early Woodland', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (34, 'Emergent Mississippian', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (25, 'Middle Woodland', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (23, 'Middle Woodland', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (26, 'Late Woodland', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (24, 'Late Woodland', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (28, 'Middle Mississippian', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (27, 'Cahokia - Emergent Mississippian II', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (296, 'Islam', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (464, 'Burguluk culture', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (464, 'Yaz I civilization', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (287, 'Perso-Islamic', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (468, 'Sogdian', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (370, 'Turko-Islamic', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (353, 'Himyarite', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (354, 'Himyarite', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (541, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (539, 'Sabaean Culture', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (538, 'Sabaean Culture', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (540, 'Sabaean Culture', 'TRS', 'true', 'supracultural_entity');