INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (257, 'Chinese Buddhist Traditions', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (269, 'Chinese Buddhist Traditions', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (428, 'Chinese Buddhist Traditions', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (261, 'Chinese Buddhist Traditions', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (263, 'Chinese Buddhist Traditions', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (264, 'Chinese Buddhist Traditions', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (370, 'Sufi', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (235, 'Sufi', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (242, 'Sufi', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (239, 'Sufi', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (95, 'Vaisnava Traditions', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (97, 'Vaisnava Traditions', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (138, 'Sufi', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (96, 'Vaishnava Traditions', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (135, 'Shia', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (487, 'Shia', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (189, 'Catholic', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (152, 'Japanese Buddhism', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (151, 'Japanese Buddhism', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (266, 'Japanese Buddhism', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (292, 'Sufi', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (44, 'Mahayana', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (43, 'Mahayana', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (45, 'Mahayana', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (45, 'Saiva Traditions', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (42, 'Mahayana', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (40, 'Mahayana', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (41, 'Mahayana', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (139, 'Sufi', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (178, 'Sufi', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (179, 'Sufi', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (299, 'Sunni', 'TRS', 'true', 'alternate_religion_family');
INSERT INTO general_polity_alternate_religion_family (polity_id, alternate_religion_family, tag, finalized, name) VALUES (371, 'Shia', 'TRS', 'true', 'alternate_religion_family');