INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (140, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (137, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (137, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (353, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (132, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (132, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (284, 'confederate state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (130, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (470, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (256, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (256, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (257, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (425, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (425, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (424, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (474, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (473, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (248, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (423, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (269, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (272, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (428, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (261, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (1, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (2, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (246, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (263, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (264, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (267, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (427, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (254, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (247, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (247, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (422, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (271, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (438, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (439, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (199, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (199, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (200, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (370, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (370, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (370, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (513, 'suspected unknown', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (517, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (518, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (208, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (235, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (242, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (239, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (522, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (514, 'none', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (514, 'suspected unknown', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (515, 'unknown', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (516, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (202, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (202, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (201, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (519, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (520, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (520, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (112, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (210, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (521, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (521, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (521, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (206, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (206, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (523, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (523, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (523, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (203, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (203, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (364, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (87, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (211, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (211, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (211, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (60, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (61, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (451, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (450, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (463, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (464, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (460, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (460, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (461, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (461, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (312, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (314, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (314, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (452, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (453, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (454, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (455, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (307, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (307, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (307, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (307, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (309, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (309, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (309, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (309, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (456, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (456, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (457, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (457, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (458, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (458, 'confederation', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (336, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (462, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (462, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (102, 'confederation', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (102, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (116, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (117, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (70, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (71, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (77, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (68, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (69, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (72, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (66, 'polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (62, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (65, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (64, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (67, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (63, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (20, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (21, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (22, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (22, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (22, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (22, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (22, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (22, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (156, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (157, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (50, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (52, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (53, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (54, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (51, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (106, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (113, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (108, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (95, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (97, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (89, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (91, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (88, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (138, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (114, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (115, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (391, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (98, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (94, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (99, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (99, 'nominal allegiance', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (90, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (101, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (96, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (92, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (92, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (388, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (93, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (100, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (100, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (100, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (135, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (135, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (487, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (479, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (482, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (482, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (345, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (484, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (485, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (478, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (478, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (483, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (481, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (109, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (349, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (476, 'suspected unknown', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (480, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (477, 'suspected unknown', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (110, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (110, 'confederate state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (511, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (511, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (490, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (498, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (365, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (505, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (505, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (510, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (489, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (175, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (492, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (494, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (493, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (502, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (503, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (504, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (506, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (506, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (507, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (507, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (508, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (508, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (128, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (486, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (488, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (512, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (377, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (131, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (133, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (111, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (111, 'confederate state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (367, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (499, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (500, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (500, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (501, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (495, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (496, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (497, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (497, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (118, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (182, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (181, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (189, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (189, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (192, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (193, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (193, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (193, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (193, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (195, 'unitary', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (196, 'unitary', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (194, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (190, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (190, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (190, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (185, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (187, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (186, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (73, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (184, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (188, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (191, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (547, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (548, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (152, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (149, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (154, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (154, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (150, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (141, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (142, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (143, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (144, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (145, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (146, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (151, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (148, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (266, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (153, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (155, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (147, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (292, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (285, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (285, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (44, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (43, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (45, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (46, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (42, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (40, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (41, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (466, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (107, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (435, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (437, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (430, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (431, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (433, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (434, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (232, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (232, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (436, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (436, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (245, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (291, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (270, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (445, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (446, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (446, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (281, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (442, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (443, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (443, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (289, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (441, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (441, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (277, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (275, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (447, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (227, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (219, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (528, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (529, 'confederation', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (529, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (530, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (531, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (532, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (535, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (11, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (13, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (12, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (14, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (527, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (526, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (525, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (119, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (81, 'none', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (82, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (84, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (85, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (80, 'none', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (86, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (83, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (448, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (449, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (120, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (121, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (122, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (129, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (126, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (123, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (127, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (136, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (136, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (136, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (139, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (124, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (125, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (197, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (198, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (524, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (134, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (48, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (465, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (224, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (163, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (164, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (164, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (76, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (78, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (79, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (173, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (173, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (173, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (161, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (162, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (75, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (167, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (165, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (171, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (172, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (159, 'unknown', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (158, 'unknown', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (168, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (176, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (176, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (177, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (178, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (179, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (169, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (74, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (174, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (170, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (35, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (36, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (33, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (104, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (105, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (23, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (25, 'none', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (37, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (28, 'none', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (26, 'none', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (29, 'none', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (27, 'none', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (31, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (30, 'none', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (32, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (299, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (472, 'nominal', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (468, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (467, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (469, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (290, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (471, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (373, 'nominal allegiance', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (373, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (373, 'confederated state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (356, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (357, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (544, 'loose', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (542, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (371, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (541, 'quasi-polity', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (375, 'unitary state', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (368, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'degree_of_centralization');
INSERT INTO general_polity_degree_of_centralization (polity_id, degree_of_centralization, tag, finalized, name) VALUES (362, 'loose', 'TRS', 'true', 'degree_of_centralization');