INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (147, 147, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (130, 147, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (121, 121, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (474, 121, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (148, 148, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (264, 148, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (199, 121, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (200, 121, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (149, 149, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (370, 149, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (150, 150, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (522, 150, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (202, 150, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (201, 150, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (519, 150, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (151, 151, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (519, 151, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (520, 150, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (520, 151, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (112, 150, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (210, 150, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (521, 151, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (523, 151, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (152, 152, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (102, 152, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (118, 118, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (70, 118, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (71, 118, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (77, 118, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (69, 118, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (72, 118, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (62, 118, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (65, 118, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (64, 118, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (67, 118, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (63, 118, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (153, 153, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (20, 153, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (21, 153, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (22, 153, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (154, 154, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (54, 154, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (155, 155, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (106, 155, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (113, 155, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (108, 155, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (114, 121, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (115, 121, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (421, 121, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (393, 121, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (101, 121, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (479, 121, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (478, 121, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (156, 156, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (475, 156, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (476, 156, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (367, 121, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (157, 157, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (118, 157, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (158, 158, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (118, 158, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (126, 126, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (193, 126, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (195, 126, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (196, 126, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (194, 126, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (190, 121, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (185, 121, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (159, 159, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (187, 159, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (186, 121, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (73, 159, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (184, 121, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (188, 121, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (191, 121, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (107, 155, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (270, 121, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (160, 160, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (445, 160, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (161, 161, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (535, 161, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (162, 162, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (9, 162, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (19, 162, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (15, 162, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (16, 162, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (11, 162, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (13, 162, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (12, 162, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (14, 162, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (10, 162, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (18, 162, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (17, 162, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (119, 157, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (119, 158, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (163, 163, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (86, 163, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (448, 121, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (449, 121, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (164, 164, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (120, 164, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (121, 164, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (122, 164, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (123, 164, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (127, 164, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (124, 164, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (125, 164, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (524, 121, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (134, 121, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (224, 121, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (165, 165, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (76, 165, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (78, 165, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (79, 165, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (166, 166, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (161, 166, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (75, 165, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (160, 121, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (176, 165, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (177, 165, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (178, 121, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (179, 121, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (74, 121, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (167, 167, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (35, 167, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (36, 167, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (23, 153, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (25, 167, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (37, 167, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (28, 167, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (26, 167, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (29, 167, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (27, 167, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (31, 167, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (30, 167, 'TRS', 'true', 'expert');
INSERT INTO accounts_seshat_expert (id, user_id, role) VALUES (168, 168, 'Seshat Expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (540, 168, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (539, 168, 'TRS', 'true', 'expert');
INSERT INTO general_polity_expert (polity_id, expert_id, tag, finalized, name) VALUES (541, 168, 'TRS', 'true', 'expert');