INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (140, 'Pashto', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (140, 'Persian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (137, 'Persian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (353, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (353, 'Bactrian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (132, 'Bactrian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (284, 'Sogdian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (284, 'Bactrian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (284, 'Pahlavi', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (284, 'Brahmi', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (130, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (130, 'Bactrian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (130, 'Kharoshthi', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (470, 'Tocharian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (470, 'Bactrian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (256, 'Chinese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (257, 'Chinese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (425, 'archaic Chinese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (424, 'archaic Chinese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (474, 'Xiangxi', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (474, 'Qiandong', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (474, 'Chuanqiandian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (473, 'Hmong-Mien', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (473, 'Hmongic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (473, 'Chuanqiandian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (248, 'Chinese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (269, 'Middle Chinese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (269, 'Jurchen', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (269, 'Khitan', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (272, 'Chinese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (428, 'Chinese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (261, 'Chinese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (261, 'Xianbei', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (1, 'Manchu language', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (1, 'Chinese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (2, 'Manchu language', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (2, 'Chinese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (246, 'Chinese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (263, 'Chinese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (264, 'Chinese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (267, 'Chinese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (427, 'Chinese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (254, 'Chinese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (247, 'Chinese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (271, 'Mongolian language', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (271, 'Chinese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (439, 'Atanque', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (199, 'Shuar', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (200, 'Shuar', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (370, 'Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (513, 'suspected unknown', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (517, 'suspected unknown', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (518, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (208, 'Demotic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (235, 'Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (242, 'Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (239, 'Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (522, 'Ancient Egyptian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (514, 'suspected unknown', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (515, 'suspected unknown', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (516, 'suspected unknown', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (202, 'Late Egyptian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (201, 'Late Egyptian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (519, 'Ancient Egyptian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (520, 'Ancient Egyptian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (112, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (112, 'demotic Egyptian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (210, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (521, 'Ancient Egyptian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (206, 'Demotic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (523, 'Ancient Egyptian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (203, 'Ancient Egyptian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (364, 'Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (87, 'Castilian Spanish', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (87, 'Castilian Spanish', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (60, 'Chuukese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (61, 'Chuukese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (463, 'French', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (464, 'French', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (460, 'French', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (460, 'Langues dOil', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (460, 'Occitan', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (461, 'French', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (461, 'Langues dOil', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (461, 'Occitan', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (312, 'Latin', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (452, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (307, 'Old Frankish', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (459, 'Latin', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (459, 'Germanic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (309, 'Latin', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (309, 'Germanic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (456, 'Gallic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (457, 'Gallic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (458, 'Gaulish', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (336, 'French', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (462, 'French', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (102, 'English', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (116, 'Akan', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (116, 'Twi', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (117, 'Akan', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (117, 'Twi', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (70, 'Doric Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (71, 'Doric Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (77, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (77, 'Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (68, 'Minoan', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (68, 'Early Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (69, 'Doric Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (69, 'Eteocretan', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (66, 'Minoan', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (66, 'Early Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (65, 'suspected unknown', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (67, 'Minoan', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (67, 'Early Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (63, 'suspected unknown', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (20, 'Old Hawaiian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (21, 'Hawaiian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (22, 'Hawaiian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (156, 'Iban', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (157, 'Iban', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (50, 'Sanskrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (52, 'Sanskrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (52, 'Old Javanese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (53, 'Middle Javanese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (53, 'Sanskrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (54, 'Javanese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (51, 'Sanskrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (51, 'Old Javanese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (106, 'Canaanite', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (113, 'Aramaic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (113, 'Hebrew', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (113, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (108, 'Hebrew', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (95, 'Sanskrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (95, 'Kannada', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (97, 'Kannada', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (97, 'Sanskrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (138, 'Persian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (138, 'Urdu', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (114, 'A’chik', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (115, 'A’chik', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (391, 'Sanskrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (391, 'Prakrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (98, 'Kannada', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (98, 'Sanskrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (94, 'Sanskrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (94, 'Prakrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (94, 'Kannada', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (99, 'Kannada', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (99, 'Sanskrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (90, 'Prakrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (90, 'Sanskrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (101, 'Urdu', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (101, 'Persian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (96, 'Sanskrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (96, 'Kannada', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (92, 'Prakrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (92, 'Kannada', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (388, 'Sanskrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (388, 'Prakrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (93, 'Sanskrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (100, 'Sanskrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (100, 'Telugu', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (100, 'Tamil', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (100, 'Kannada', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (135, 'Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (487, 'Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (479, 'Akkadian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (479, 'Sumerian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (482, 'Amorite', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (482, 'Old Babylonian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (484, 'Akkadian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (485, 'Mesopotamian Religions', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (478, 'Sumerian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (483, 'Akkadian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (481, 'Akkadian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (109, 'Aramaic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (476, 'suspected unknown', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (480, 'Sumerian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (480, 'Akkadian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (477, 'suspected unknown', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (110, 'Old Persian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (110, 'Aramaic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (110, 'Elamite', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (110, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (110, 'Egyptian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (511, 'Persian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (498, 'Old Elamite', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (498, 'Akkadian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (365, 'Persian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (365, 'Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (510, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (175, 'Mongolian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (175, 'Persian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (175, 'Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (502, 'Elamite', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (502, 'Akkadian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (503, 'Elamite', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (503, 'Akkadian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (504, 'Elamite', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (504, 'Akkadian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (507, 'Elamite', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (507, 'native Iranian languages', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (508, 'Elamite', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (128, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (128, 'Pahlavi', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (486, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (486, 'Pahlavi', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (512, 'Persian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (377, 'Persian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (377, 'Turkic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (377, 'Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (131, 'Pahlavi', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (133, 'Pahlavi', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (111, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (367, 'Turkish', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (367, 'Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (367, 'Persian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (499, 'Elamite', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (499, 'Akkadian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (499, 'Babylonian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (500, 'Elamite', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (500, 'Akkadian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (500, 'Babylonian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (500, 'Hurrian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (500, 'Amorite', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (496, 'Sumerian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (497, 'Sumerian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (497, 'Proto-Elamite', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (118, 'Old Norse', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (182, 'Latin', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (183, 'Latin', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (189, 'Latin', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (189, 'Germanic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (192, 'Latin', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (193, 'Latin', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (195, 'Latin', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (196, 'Latin', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (194, 'Latin', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (190, 'Latin', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (190, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (185, 'Latin', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (185, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (187, 'Latin', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (187, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (186, 'Latin', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (186, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (73, 'Latin', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (184, 'Latin', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (188, 'Latin', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (191, 'Latin', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (547, 'Italian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (548, 'Italian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (152, 'Middle Japanese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (149, 'Old Japanese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (154, 'Middle Japanese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (150, 'Late Old Japanese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (150, 'Middle Japanese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (141, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (142, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (143, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (144, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (145, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (146, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (151, 'Middle Japanese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (148, 'Japanese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (266, 'Old Japanese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (153, 'Middle Japanese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (155, 'Early Modern Japanese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (147, 'Japanese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (292, 'Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (292, 'Turkic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (285, 'Sogdian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (285, 'Old Turkic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (285, 'Iranian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (44, 'Old Khmer', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (44, 'Mon', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (44, 'Tai', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (43, 'Old Khmer', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (45, 'Khmer', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (46, 'Khmer', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (46, 'Mon', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (46, 'Tai', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (46, 'Pali', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (42, 'Old Khmer', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (42, 'Sanskrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (40, 'Khmer', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (40, 'Mon', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (41, 'Khmer', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (41, 'Mon', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (107, 'Phoenician', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (435, 'Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (435, 'Berber', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (435, 'Spanish', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (435, 'Portuguese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (437, 'Bambara', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (430, 'suspected unknown', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (232, 'Mande', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (232, 'Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (436, 'Bambara', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (245, 'Mande', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (245, 'Songhay', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (286, 'Old Turkic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (286, 'Sogdian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (291, 'Khitan', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (270, 'Mongolian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (270, 'Persian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (270, 'Chinese', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (270, 'Latin', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (270, 'Russian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (270, 'Georgian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (270, 'Armenian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (445, 'Mongolian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (445, 'Kereid', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (445, 'Tatar', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (445, 'Naimans', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (446, 'Khalkha', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (281, 'Rouran', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (443, 'Old Turkic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (289, 'Old Turkic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (441, 'Xianbei', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (440, 'Xiongnu', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (277, 'Xiongnu', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (275, 'Xiongnu', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (447, 'Oirat', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (227, 'Mande', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (219, 'Mande', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (528, 'Zapotec', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (529, 'Zapotec', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (530, 'Zapotec', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (531, 'Zapotec', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (532, 'Zapotec', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (535, 'Zapotec', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (13, 'suspected unknown', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (14, 'suspected unknown', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (527, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (526, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (525, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (119, 'Icelandic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (81, 'suspected unknown', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (82, 'suspected unknown', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (84, 'Aymara', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (84, 'Puquina', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (85, 'Aymara', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (85, 'Puquina', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (80, 'suspected unknown', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (86, 'Quechua', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (83, 'suspected unknown', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (448, 'Orokaiva', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (449, 'Orokaiva', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (120, 'unknown', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (121, 'unknown', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (122, 'unknown', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (129, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (129, 'Sanskrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (129, 'Prakrit', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (129, 'Bactrian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (129, 'Aramaic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (126, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (123, 'unknown', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (127, 'unknown', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (136, 'Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (136, 'Sindhi', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (139, 'Sindhi', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (139, 'Punjabi', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (124, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (125, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (197, 'Sakha (Yakut)', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (198, 'Sakha (Yakut)', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (524, 'Merotic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (524, 'Egyptian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (134, 'Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (134, 'Coptic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (134, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (134, 'Persian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (47, 'Tai', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (47, 'Thai', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (48, 'Thai', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (224, 'Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (163, 'Proto-Indo-European language', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (166, 'Nesite', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (166, 'Luwian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (164, 'Hattic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (164, 'Luwian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (164, 'Hittite', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (164, 'Hurrian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (164, 'Old Assyrian dialect of Akkadian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (76, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (78, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (79, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (173, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (161, 'Indo-European language', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (162, 'Indo-European language', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (75, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (167, 'Nesite', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (167, 'Luwian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (165, 'Nesite', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (165, 'Luwian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (171, 'Lydian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (172, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (159, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (160, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (168, 'Luwian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (176, 'Ottoman Turkish', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (177, 'Turkish', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (177, 'Persian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (178, 'Turkish', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (179, 'Turkish', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (169, 'Phrygian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (74, 'Latin', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (74, 'Greek', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (174, 'Turkish', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (174, 'Persian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (174, 'Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (170, 'Luwian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (35, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (36, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (33, 'Miami Illinois', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (104, 'Cayuga', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (104, 'Mohawk', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (104, 'Oneida', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (104, 'Onondaga', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (104, 'Seneca', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (104, 'Tuscarora', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (105, 'Cayuga', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (105, 'Mohawk', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (105, 'Oneida', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (105, 'Onondaga', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (105, 'Seneca', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (105, 'Tuscarora', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (23, 'Hawaiian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (37, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (31, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (299, 'Middle Mongolian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (472, 'Persian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (468, 'Sogdian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (469, 'Ancient Iranian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (290, 'Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (290, 'Persian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (471, 'Sogdian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (373, 'Chagatai Turkish', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (373, 'Persian', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (544, 'Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (542, 'Sabaic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (542, 'Mainic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (542, 'Qatabanic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (542, 'Hadramawtic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (542, 'Old Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (541, 'Sabaic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (541, 'Mainic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (541, 'Qatabanic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (541, 'Hadramawtic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (541, 'Old Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (543, 'Sabaic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (543, 'Mainic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (543, 'Qatabanic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (543, 'Hadramawtic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (543, 'Old Arabic', 'TRS', 'true', 'language');
INSERT INTO general_polity_language (polity_id, language, tag, finalized, name) VALUES (375, 'Arabic', 'TRS', 'true', 'language');