INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (140, 1761, 1761, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (137, 1200, 1200, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (353, -180, -180, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (132, 509, 522, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (284, 420, 440, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (130, 229, 229, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (256, 88, 88, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (257, 280, 300, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (425, -1500, -1450, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (424, -1700, -1530, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('474', None, None, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (473, 1790, 1790, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('248', None, None, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (269, 1207, 1207, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (272, 1450, 1480, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (428, 1050, 1050, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (261, 439, 439, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (1, 1796, 1796, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (2, 1850, 1850, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (246, -1200, -1200, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (263, 609, 609, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (264, 740, 740, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (267, 820, 820, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (427, -353, -353, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (254, -100, -100, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (247, -950, -925, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (271, 1310, 1310, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('199', None, None, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('200', None, None, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (370, 1193, 1193, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (513, -4400, -4000, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (235, 1341, 1341, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (242, 1425, 1425, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (242, 1495, 1495, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (239, 1348, 1348, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (522, -1850, -1850, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('514', None, None, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('515', None, None, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (516, -3300, -3200, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (202, -1250, -1250, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (201, -1300, -1300, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (519, -2400, -2400, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (520, -2300, -2300, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (112, -300, -300, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (521, -2063, -2063, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (206, -550, -550, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (523, -1555, -1555, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (203, -924, -924, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (364, 895, 895, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (87, 1556, 1598, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (211, 250, 250, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (463, 1611, 1611, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (464, 1723, 1743, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (460, 1150, 1150, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (461, 1285, 1314, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (312, 811, 811, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (314, 840, 840, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (452, -900, -900, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (307, 543, 543, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (459, 751, 751, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (309, 584, 629, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (456, -450, -450, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (457, -200, -200, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (458, -125, -125, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (336, 1364, 1380, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (462, 1515, 1515, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (102, 1815, 1815, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (116, 1650, 1701, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (117, 1800, 1824, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (70, -650, -650, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (71, -350, -350, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (77, 824, 961, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (68, -1200, -1100, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (69, -800, -800, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (72, -250, -250, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (66, -1390, -1300, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (62, -4500, -3000, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (65, -1500, -1450, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (64, -1800, -1700, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (67, -1300, -1200, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (63, -2300, -1900, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (20, 1200, 1200, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (21, 1580, 1580, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('156', None, None, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (157, 1900, 1946, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (49, 100, 100, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (53, 1389, 1389, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (51, 850, 850, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (106, -1550, -1550, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (113, -105, -105, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (108, -855, -855, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (95, 609, 643, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (97, 1076, 1126, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (138, 1296, 1316, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('114', None, None, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (115, 1867, 1900, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (391, 400, 400, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (98, 1225, 1225, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (94, 435, 455, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (90, -269, -232, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (101, 1630, 1707, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (96, 814, 878, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (92, 106, 130, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (93, 510, 510, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (100, 1505, 1542, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (135, 809, 809, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (487, 1226, 1226, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (479, -2190, -2154, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (482, -1792, -1750, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (345, -1359, -1333, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (484, -1005, -989, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('478', None, None, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (483, -1119, -1098, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (109, -668, -668, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (349, -604, -562, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (476, -5000, -4000, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (480, -2097, -2038, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (477, -3200, -3050, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (110, -500, -500, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (511, 1453, 1478, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (365, 983, 983, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (510, 100, 100, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (175, 1316, 1316, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (502, -1158, -1158, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (503, -1300, -1300, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (504, -1158, -1158, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (507, -743, -717, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (128, -120, -120, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (486, 50, 100, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (512, 1900, 1900, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (377, 1629, 1629, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (131, 309, 379, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (133, 570, 570, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (111, -281, -281, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (111, -190, -190, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (367, 1092, 1092, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (500, -1900, -1800, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('118', None, None, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (189, 525, 525, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (192, 1030, 1030, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (193, 1240, 1240, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (195, 1571, 1571, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (196, 1750, 1750, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (194, 1506, 1506, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (190, 640, 640, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (185, -287, -287, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (187, -49, -49, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (186, -133, -133, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (73, 117, 117, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (184, -535, -535, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (188, 439, 439, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (191, 850, 900, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (547, 1481, 1550, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (548, 1565, 1565, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (152, 1368, 1394, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (150, 794, 930, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (151, 1225, 1225, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (266, 781, 794, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (153, 1568, 1568, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (155, 1688, 1704, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (147, 125, 125, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (292, 1068, 1068, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (44, 1150, 1220, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (43, 900, 900, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (45, 1220, 1353, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (46, 1400, 1400, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (42, 650, 650, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (40, 250, 514, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (41, 450, 650, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('38', None, None, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('39', None, None, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (107, -570, -570, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (435, 1578, 1603, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (437, 1800, 1800, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (430, 49, 49, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (431, 399, 399, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (433, 899, 899, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (434, 1100, 1100, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (232, 1312, 1337, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (436, 1650, 1680, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (245, 1550, 1550, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (270, 1251, 1259, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (445, 1206, 1206, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (281, 402, 429, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (443, 691, 716, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (441, 155, 155, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (447, 1679, 1745, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('227', None, None, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (219, 1025, 1050, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (529, -100, -100, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (530, -200, -200, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('11', None, None, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (13, -200, -200, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (12, -650, -650, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (526, -1150, -850, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (525, -1400, -1150, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('119', None, None, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (82, 600, 600, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (84, 1250, 1250, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (85, 1400, 1400, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (80, 200, 200, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (86, 1525, 1525, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (83, 800, 800, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('448', None, None, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (449, 1921, 1942, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('120', None, None, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('121', None, None, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (129, -155, -130, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('123', None, None, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (136, 985, 985, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (139, 1486, 1486, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (124, -2500, -2100, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (125, -1800, -1300, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('197', None, None, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (198, 1850, 1900, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (524, -663, -663, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (134, 724, 724, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (47, 1733, 1758, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (48, 1793, 1810, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (224, 996, 996, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (224, 1058, 1058, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('163', None, None, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (166, -1450, -1450, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (164, -1850, -1750, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (76, 741, 775, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (78, 1025, 1025, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (79, 1180, 1180, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (173, -302, -95, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('161', None, None, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('162', None, None, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (75, 527, 542, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (167, -1240, -1240, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (171, -560, -560, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (172, -306, -281, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('159', None, None, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('158', None, None, 'TRS', 'true', 'peak_date');
-- INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES ('168', None, None, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (176, 1402, 1402, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (177, 1517, 1517, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (178, 1520, 1566, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (179, 1683, 1683, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (169, -738, -696, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (74, 394, 394, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (174, 1220, 1237, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (35, 1100, 1100, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (36, 1200, 1200, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (104, 1650, 1701, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (105, 1714, 1765, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (23, 1810, 1810, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (25, 150, 150, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (37, 1050, 1050, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (28, 600, 600, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (26, 300, 300, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (29, 750, 750, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (27, 450, 450, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (30, 900, 900, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (290, 942, 942, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (471, 700, 700, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (373, 1449, 1449, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (356, 300, 300, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (357, 378, 378, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (371, 1300, 1350, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (368, 1067, 1091, 'TRS', 'true', 'peak_date');
INSERT INTO general_polity_peak_years (polity_id, peak_year_from, peak_year_to, tag, finalized, name) VALUES (362, 1000, 1000, 'TRS', 'true', 'peak_date');