INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (87, 'Christianity', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (211, 'South Arabian Religions', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (102, 'Christianity', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (345, 'Mesopotamian Religions', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (484, 'Mesopotamian Religions', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (485, 'Akkadian', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (483, 'Mesopotamian Religions', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (481, 'Mesopotamian Religions', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (349, 'Mesopotamian Religions', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (531, 'Monte Albán Religion', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (532, 'Monte Albán Religion', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (81, 'suspected unknown', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (82, 'suspected unknown', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (84, 'suspected unknown', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (85, 'suspected unknown', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (80, 'suspected unknown', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (86, 'Inca Religion', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (83, 'suspected unknown', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (356, 'South Arabian Religions', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (357, 'Judaism', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (544, 'Sunni Islam', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (542, 'South Arabian Religions', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (541, 'South Arabian Religions', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (543, 'South Arabian Religions', 'TRS', 'true', 'religious_tradition');
INSERT INTO general_polity_religious_tradition (polity_id, religious_tradition, tag, finalized, name) VALUES (375, 'Islam', 'TRS', 'true', 'religious_tradition');