INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (137, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (353, 'Graeco-Bactrian Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (132, 'Hephthalite Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (284, 'Zoroastrianism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (284, 'Buddhism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (284, 'Hinduism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (130, 'Graeco-Bactrian Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (130, 'Ancient Iranian Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (130, 'Hinduism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (130, 'Buddhism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (130, 'Zoroastrianism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (257, 'Chinese State Religion', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (248, 'Ancient East Asian Religion', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (269, 'Chinese State Religion', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (428, 'Chinese State Religion', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (261, 'Chinese State Religion', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (246, 'Chinese State Religion', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (263, 'Chinese State Religion', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (264, 'Chinese State Religion', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (247, 'Chinese State Religion', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (271, 'Mongolian Shamanism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (370, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (208, 'Egyptian Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (235, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (242, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (239, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (202, 'Egyptian Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (201, 'Egyptian Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (112, 'Hellenistic Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (210, 'Hellenistic Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (206, 'Egyptian Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (203, 'Egyptian Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (364, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (312, 'Christianity', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (314, 'Christianity', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (307, 'Christianity', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (309, 'Christianity', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (336, 'Christianity', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (50, 'Ancient Javanese Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (95, 'Hinduism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (97, 'Hinduism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (138, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (391, 'Hinduism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (90, 'Hinduism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (90, 'Jain Traditions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (90, 'Buddhism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (96, 'Hinduism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (92, 'Hinduism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (388, 'Hinduism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (93, 'Hinduism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (100, 'Hinduism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (135, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (487, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (109, 'Mesopotamian Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (110, 'Zoroastrianism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (511, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (175, 'Buddhism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (175, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (486, 'Zoroastrianism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (377, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (133, 'Zoroastrianism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (111, 'Hellenistic Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (367, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (189, 'Christianity', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (192, 'Christianity', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (193, 'Christianity', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (195, 'Christianity', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (196, 'Christianity', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (194, 'Christianity', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (185, 'Roman State Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (187, 'Roman State Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (186, 'Roman State Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (73, 'Roman State Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (188, 'Christianity', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (191, 'Christianity', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (152, 'Shinto', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (151, 'Shinto', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (266, 'Shinto', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (292, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (285, 'Buddhism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (44, 'Hinduism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (43, 'Hinduism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (45, 'Hinduism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (45, 'Buddhism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (42, 'Hinduism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (40, 'Hinduism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (41, 'Hinduism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (232, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (245, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (286, 'Buddhism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (291, 'Buddhism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (270, 'Mongolian Shamanism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (281, 'Buddhism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (289, 'Manichaeism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (277, 'Xiongnu Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (275, 'Xiongnu Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (129, 'Graeco-Bactrian Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (136, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (139, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (524, 'Egyptian Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (134, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (224, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (166, 'Hittite Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (76, 'Christianity', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (78, 'Christianity', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (79, 'Christianity', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (75, 'Christianity', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (167, 'Hittite Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (165, 'Hittite Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (171, 'Lydian Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (172, 'Hellenistic Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (168, 'Hittite Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (176, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (177, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (178, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (179, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (169, 'Phrygian Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (74, 'Roman State Religions', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (174, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (299, 'Mongolian Shamanism', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (373, 'Islam', 'TRS', 'true', 'religion_genus');
INSERT INTO general_polity_religion_genus (polity_id, religion_genus, tag, finalized, name) VALUES (368, 'Ismaili', 'TRS', 'true', 'religion_genus');