INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (137, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (257, 'Imperial Confucian Traditions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (248, 'Chinese Folk Religion', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (269, 'Imperial Confucian Traditions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (428, 'Imperial Confucian Traditions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (261, 'Imperial Confucian Traditions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (246, 'Shang Religion', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (263, 'Imperial Confucian Traditions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (264, 'Imperial Confucian Traditions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (247, 'Western Zhou Religion', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (370, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (235, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (242, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (239, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (201, 'Atenism', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (112, 'Ptolemaic Religion', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (210, 'Ptolemaic Religion', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (364, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (87, 'Catholic', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (312, 'Catholic', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (314, 'Catholic', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (307, 'Catholic', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (309, 'Catholic', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (336, 'Catholic', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (95, 'Saiva Traditions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (97, 'Saiva Traditions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (138, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (391, 'Vaisnava Traditions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (96, 'Saiva Traditions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (92, 'Saivist Traditions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (92, 'Vedist Traditions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (92, 'Bhagavatist Traditions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (388, 'Vedic Traditions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (93, 'Saivist Traditions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (100, 'Saivist Traditions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (100, 'Vaisnava Traditions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (135, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (487, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (485, 'Semitic', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (109, 'Assyrian Religions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (511, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (175, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (175, 'Shii', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (175, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (377, 'Shia', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (111, 'Seleucid Religion', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (367, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (189, 'Arian', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (192, 'Catholic', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (193, 'Catholic', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (195, 'Catholic', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (196, 'Catholic', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (194, 'Catholic', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (185, 'Republican Religions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (187, 'Republican Religions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (186, 'Republican Religions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (73, 'Imperial Cult', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (191, 'Catholic', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (152, 'Japanese State Shinto', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (151, 'Japanese State Shinto', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (266, 'Japanese State Shinto', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (292, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (44, 'Saiva Traditions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (43, 'Saiva Traditions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (45, 'Saiva Traditions', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (45, 'Theravada', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (42, 'Saivist', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (40, 'Saivist', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (41, 'Saivist', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (245, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (81, 'suspected unknown', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (82, 'suspected unknown', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (84, 'suspected unknown', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (85, 'suspected unknown', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (80, 'suspected unknown', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (83, 'suspected unknown', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (136, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (136, 'Shia', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (139, 'Shia', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (134, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (224, 'Shia', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (76, 'Catholic', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (78, 'Catholic', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (78, 'Orthodox', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (79, 'Orthodox', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (75, 'Catholic', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (176, 'Sufi', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (177, 'Sufi', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (178, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (179, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (74, 'Imperial Cult', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (174, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (373, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (544, 'Islam', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (371, 'Sunni', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (368, 'Shia', 'TRS', 'true', 'religion_family');
INSERT INTO general_polity_religion_family (polity_id, religion_family, tag, finalized, name) VALUES (362, 'Sunni', 'TRS', 'true', 'religion_family');