INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (137, 'Karrami', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (137, 'Hanafi', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (137, 'Shafii', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (256, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (370, 'Shafii', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (235, 'Hanafi', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (242, 'Hanafi', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (239, 'Hanafi', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (312, 'Roman Catholic', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (314, 'Roman Catholic', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (307, 'Roman Catholic', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (309, 'Roman Catholic', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (336, 'Roman Catholic', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (135, 'Hanafi', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (487, 'Hanafi', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (377, 'Twelver', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (192, 'Roman Catholic', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (193, 'Roman Catholic', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (195, 'Roman Catholic', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (196, 'Roman Catholic', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (194, 'Roman Catholic', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (191, 'Roman Catholic', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (292, 'Hanafi', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (136, 'Sunni', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (136, 'Shia', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (139, 'Ismaili', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (134, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (224, 'Ismaili', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (76, 'Roman Catholic', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (78, 'Roman Catholic', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (78, 'Byzantine Orthodox', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (79, 'Byzantine Orthodox', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (75, 'Roman Catholic', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (176, 'Mevlevi', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (176, 'Bektasi', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (177, 'Mevlevi', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (177, 'Bektasi', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (178, 'Hanafi', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (179, 'Hanafi', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (373, 'Hanafi', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (371, 'Islam', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (368, 'Islam', 'TRS', 'true', 'religion');
INSERT INTO general_polity_religion (polity_id, religion, tag, finalized, name) VALUES (362, 'Islam', 'TRS', 'true', 'religion');