INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (140, 'Barkzai Dynasty', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (353, 'Sakas', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (132, 'First Turk Khaganate', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (284, 'Hephthalite Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (130, 'Sassanid Empire I', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (470, 'Kushan Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (256, 'Wei Dynasty', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (257, 'Northern Wei', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (425, 'Late Shang', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (424, 'Erligang', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (474, 'Peoples Republic of China', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (473, 'Hmong - Early Chinese', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (248, 'Zhao', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (248, 'Wei', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (248, 'Qin', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (423, 'Erlitou', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (269, 'Great Yuan', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (428, 'Later Jin', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (261, 'Western Wei', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (1, 'Late Qing', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (2, 'Republic of China', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (246, 'Western Zhou', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (263, 'Early Tang', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (264, 'Later Tang Dynasty', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (267, 'China - Five Dynasties Period and Ten Kingdoms Period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (427, 'Imperial Qin', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (254, 'Wang Mang interregnum', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (247, 'Zhou Kingdom', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (422, 'Longshan', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (271, 'China - Early Ming', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (438, 'CoTairo', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (439, 'Spanish Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (199, 'Shuar - Ecuadorian', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (200, 'Republic of Ecuador', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (370, 'Egypt - Mamluk Sultanate I', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (513, 'Naqada I', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (517, 'Egypt - Dynasty II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (518, 'Egypt - Classic Old Kingdom', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (208, 'Achaemenid Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (235, 'Egypt - Mamluk Sultanate II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (242, 'Ottoman Empire II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (239, 'Egypt - Mamluk Sultanate III', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (522, 'Egypt - Thebes-Hyksos Period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (514, 'Naqada II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (515, 'Egypt - Dynasty 0', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (516, 'Egypt - Dynasty I', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (202, 'Egypt - Thebes-Libyan Period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (201, 'Ramesside period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (519, 'Egypt - Late Old Kingdom', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (520, 'Egypt - Period of the Regions', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (112, 'Ptolemaic Kingdom II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (210, 'Roman Empire - Principate', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (521, 'Egypt - Middle Kingdom', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (206, 'Achaemenid Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (523, 'Egypt - New Kingdom Thutmosid Period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (203, 'Egypt - Kushite Period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (364, 'Fatimid Caliphate', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (87, 'House of Bourbon-Spain', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (211, 'EtAksm2', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (60, 'FmTrukL', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (61, 'United Nations Trusteeship', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (61, 'Federated States of Micronesia', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (451, 'Hallstatt A-B1', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (450, 'Atlantic Complex', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (463, 'French Kingdom - Late Bourbon', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (464, 'Revolutionary Republic', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (460, 'French Kingdom - Late Capetian', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (461, 'French Kingdom - Early Valois', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (312, 'Carolingian Empire II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (314, 'Proto-French Kingdom', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (452, 'Hallstatt B', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (453, 'Hallstatt C', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (454, 'Hallstatt D', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (455, 'La Tene A-B1', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (307, 'Middle Merovingian', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (459, 'Carolingian Empire I', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (309, 'Proto-Carolingian', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (456, 'La Tene B2-C1', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (457, 'La Tene C2-D', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (458, 'Late Roman Republic', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (336, 'French Kingdom - Late Valois', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (462, 'French Kingdom - Early Bourbon', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (102, 'British Empire - Victorian Period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (116, 'Ashanti Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (117, 'British Empire Gold Coast Colony', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (70, 'Classical Crete', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (71, 'Hellenistic Crete', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (77, 'Middle Byzantine Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (68, 'Geometric Crete', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (69, 'Archaic Crete', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (72, 'Roman Republic', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (66, 'Final Palatial Crete', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (62, 'Prepalatial Crete', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (65, 'Monopalatial Crete', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (64, 'Neopalatial Crete', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (67, 'Final Postpalatial Crete', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (63, 'Protopalatial Crete', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (20, 'Hawaii II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (21, 'Hawaii III', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (22, 'Kingdom of Hawaii - Kamehameha Period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (156, 'Brooke Raj', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (156, 'White Rajahs', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (157, 'Malaysia', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (157, 'Indonesia', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (49, 'Kalingga Kingdom', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (50, 'Medang Kingdom', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (52, 'Singhasari Kingdom', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (53, 'Demak Sultanate', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (51, 'Kahuripan Kingdom', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (106, 'Ancient Phoenicia', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (113, 'Late Roman Republic', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (108, 'Neo-Assyrian Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (95, 'Rashtrakuta Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (97, 'Hoysala Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (89, 'Mauryan Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (91, 'Satavahana Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (88, 'Deccan - Iron Age', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (114, 'British Colonial India', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (115, 'Republic of India', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (98, 'Vijayanagara Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (94, 'Chalukyas of Badami', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (99, 'Vijayanagara Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (90, 'Shunga Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (101, 'Durrani Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (96, 'Chalukyas of Kalyani', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (92, 'Vakataka Kingdom', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (100, 'Mughal Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (135, 'Buyid Confederation', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (487, 'Il-khanate', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (479, 'Gutian Dynasty', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (482, 'Sealand', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (345, 'Middle Elamite Kingdom', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (484, 'Elamite Dynasty', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (485, 'IqNAssr', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (478, 'Akkadian Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (483, 'Second Sealand Dynasty', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (481, 'IqBabAm', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (349, 'IrAchae', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (476, 'Uruk culture', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (480, 'Isin', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (477, 'Early Dynastic Sumer', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (110, 'Macedonian Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (511, 'Safavid Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (490, 'Susiana A', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (498, 'Akkadian Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (365, 'Seljuk Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (505, 'Elam - Dark Age', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (489, 'Archaic Period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (175, 'Chobanids', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (491, 'Susiana B', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (492, 'Susiana - Early Ubaid', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (494, 'Susa I', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (493, 'Susiana - Late Ubaid', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (502, 'Neo-Assyrian Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (503, 'Neo-Assyrian Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (504, 'Neo-Assyrian Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (506, 'Elam - Neo-Elamite II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (507, 'Neo-Assyrian Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (508, 'Achaemenid Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (128, 'Parthian Empire II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (486, 'Sassanid Empire I', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (488, 'Formative Period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (377, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (131, 'Sassanid Empire II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (133, 'Rashidun Caliphate', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (111, 'Parthian Empire I', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (367, 'Il-Khanate', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (499, 'Elam - Early Sukkalmah', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (500, 'Elam - Late Sukkalmah', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (501, 'Elam - Kidinuid Period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (495, 'Susa II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (496, 'Susa III', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (497, 'Elam - Awan Dynasty I', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (118, 'Kingdom of Norway', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (182, 'Latium - Iron Age', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (181, 'Latium - Bronze Age', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (183, 'Roman Kingdom', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (189, 'East Roman Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (192, 'Papal State I', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (193, 'Rome - Republic Restoration Period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (195, 'Papal States - Medieval Period II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (196, 'Napoleonic Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (194, 'Papal States - Medieval Period I', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (190, 'Republic of St Peter', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (185, 'Middle Roman Republic', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (187, 'Roman Empire - Principate', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (186, 'Late Roman Republic', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (73, 'Roman Empire - Dominate', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (184, 'Early Roman Republic', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (188, 'Roman Empire - Late Antiquity', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (191, 'Rome - Republic of St Peter II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (547, 'Venetian Republic', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (152, 'Japan - Sengoku Jidai', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (149, 'Kansai - Nara Period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (154, 'Tokugawa Shogunate', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (150, 'Kamakura Shogunate', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (141, 'Japan - Initial Jomon', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (142, 'Early Jomon', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (143, 'Japan - Middle Jomon', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (144, 'Japan - Late Jomon', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (145, 'Japan - Final Jomon', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (146, 'Kansai - Yayoi Period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (151, 'Japan - Kemmu Restoration', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (148, 'Kansai - Asuka Period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (266, 'Kansai - Heian Period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (153, 'Japan - Azuchi-Momoyama', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (155, 'Japan - Meiji Restoration', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (147, 'Kansai - Kofun Period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (292, 'Khwarezmid Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (285, 'Sogdiana - City-States Period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (44, 'Late Angkor', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (43, 'Classical Angkor', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (45, 'Khmer Kingdom', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (46, 'Ayutthaya', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (42, 'Early Angkor', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (40, 'Funan II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (41, 'Zhenla', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (466, 'Yaz I', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (107, 'Macedonian Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (435, 'Alaouite Dynasty', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (437, 'Toucouleur Kingdom', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (430, 'Jenne-jeno II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (431, 'Jenne-jeno III', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (433, 'Jenne-Jeno IV', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (434, 'Sosso Kingdom', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (232, 'Mande States', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (436, 'Bamana Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (245, 'Saadi Dynasty', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (286, 'Tang Dynasty', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (291, 'Early Mongols', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (270, 'Great Yuan', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (445, 'Mongol Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (446, 'Zungharian Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (281, 'First Turk Khaganate', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (442, 'Khitan Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (443, 'Uighur Khaganate', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (289, 'Khitan Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (441, 'Rouran Khaganate', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (440, 'Xiongnu Imperial Confederation', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (277, 'Xianbei Confederation', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (275, 'MnXngnL', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (447, 'China - Early Qing', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (227, 'Mali Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (219, 'Ghana II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (528, 'MxAlb1L', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (529, 'MxAlb2*', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (530, 'MxAlb3A', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (531, 'MxAlb3B', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (532, 'Zapotec', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (532, 'Monte Albán V', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (535, 'Spanish colonial rule', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (9, 'MxInitl', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (15, 'MxEpicl', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (11, 'MxFormM', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (13, 'MxFormT', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (12, 'MxCuicu', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (14, 'MxClass', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (10, 'MxFormE', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (527, 'MxAlb1E', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (526, 'MxRosar', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (525, 'MxSanGu', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (119, 'Kalmar Union', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (81, 'PeCuzE2', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (82, 'PeWari*', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (84, 'PeCuzL2', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (85, 'PeInca*', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (80, 'PeCuzE1', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (86, 'EsHabsb', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (83, 'PeCuzL1', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (448, 'Orokaiva - Colonial', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (449, 'Australian Territory of Papua and New Guinea', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (449, 'Independent State of Papua New Guinea', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (120, 'Kachi Plain - Ceramic Neolithic', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (121, 'Kachi Plain - Chalcolithic', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (122, 'not applicable', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (129, 'Parthian Empire I', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (126, 'Kachi Plain - Proto-Historic Period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (123, 'Kachi Plain - Urban Period I', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (127, 'Achaemenid Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (139, 'Mughal Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (124, 'Kachi Plain - Urban Period II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (125, 'Kachi Plain - Post-Urban Period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (197, 'Czarist Russia', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (198, 'Czarist Russia', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (198, 'USSR', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (524, 'Neo-Assyrian Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (134, 'Abbasid Caliphate I', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (47, 'Rattanakosin', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (48, 'Rattanakosin - Reform Period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (465, 'Andronovo', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (224, 'Ayyubid Sultanate', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (163, 'Konya Plain - Middle Bronze Age', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (166, 'Hatti - New Kingdom', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (164, 'KonLBA1', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (76, 'Byzantine Empire II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (78, 'Byzantine Empire III', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (79, 'Latin Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (173, 'Late Roman Republic', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (161, 'Konya Plain - Late Chalcolithic', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (162, 'Konya Plain - Early Bronze Age', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (75, 'Byzantine Empire I', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (167, 'Neo-Hittite Kingdoms', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (165, 'Konya Plain - Late Bronze Age II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (172, 'Seleucid Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (159, 'Konya Plain - Late Neolithic', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (158, 'Konya Plain - Ceramic Neolithic', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (160, 'Konya Plain - Early Chalcolithic Neolithic', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (168, 'Tabal Kingdoms', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (176, 'Ottoman Empire I', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (177, 'Ottoman Empire II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (178, 'Ottoman Empire III', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (179, 'Ottoman Empire IV', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (169, 'Konya Plain - Cimmerian Period', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (74, 'Western Roman Empire - Late Antiquity', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (174, 'Mongol Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (170, 'Assyrian Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (35, 'Cahokia - Moorehead', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (36, 'Cahokia - Sand Prairie', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (33, 'Late Illinois Confederation', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (104, 'Iroquois Confederacy', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (105, 'United States of America', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (25, 'Cahokia - Middle Woodland', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (37, 'Cahokia - Lohmann-Stirling', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (28, 'Cahokia - Late Woodland III', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (26, 'Cahokia - Late Woodland I', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (29, 'Cahokia - Emergent Mississippian I', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (27, 'Cahokia - Late Woodland II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (31, 'Oneota', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (30, 'Merrell-Edlehardt', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (32, 'Early Illinois Confederation', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (299, 'Timurid Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (472, 'Manghits', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (468, 'Achaemenid Empire', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (467, 'Koktepe II', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (469, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (290, 'Kara-Khanids', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (471, 'Umayyad Caliphate', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (373, 'Shaybanid Kingdom', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (356, 'YeHmyr2', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (357, 'EtAksm1', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (540, 'YeSabaC', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (544, 'TrOttm4', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (542, 'YeSaRay', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (371, 'YeTahir', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (541, 'YeQatab', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (543, 'EtAksm1', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (375, 'TrOttm3', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (368, 'EgAyyub', 'TRS', 'true', 'succeeding_(quasi)polity');
INSERT INTO general_polity_succeeding_entity (polity_id, succeeding_entity, tag, finalized, name) VALUES (362, 'YeWarLd', 'TRS', 'true', 'succeeding_(quasi)polity');