INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (353, 'Greek', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (132, 'Steppe nomads', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (284, 'Eurasian nomadic', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (284, 'Persian', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (284, 'Indian', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (130, 'Greco-Persian', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (470, 'Greco-Persian', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (256, 'Chinese', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (257, 'Chinese', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (425, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (424, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (474, 'East Asia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (473, 'China', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (248, 'China', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (423, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (269, 'China', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (272, 'China', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (428, 'China', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (261, 'Xianbei', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (1, 'China', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (2, 'China', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (246, 'China', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (263, 'Chinese', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (264, 'China', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (267, 'China', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (427, 'Chinese', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (254, 'China', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (422, 'China', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (271, 'China', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (438, 'Caribbean Colombia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (438, 'Central America-northern South America interaction sphere', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (439, 'Chibchan region', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (199, 'Amazonia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (200, 'Amazonia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (370, 'Islam', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (208, 'Egypt', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (235, 'Islam', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (242, 'Islam', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (239, 'Islam', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (515, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (202, 'Egyptian Civilization', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (112, 'Greek World', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (210, 'Greek World', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (206, 'Egypt', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (203, 'Libyan tribes', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (364, 'Islam', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (60, 'Micronesia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (61, 'Micronesia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (451, 'Bronze Age Europe', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (450, 'Chalcolithic', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (450, 'Late Neolithic', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (460, 'Latin Christendom', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (461, 'Latin Christendom', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (312, 'Latin Christendom', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (314, 'Latin Christendom', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (452, 'Hallstatt', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (453, 'Hallstatt', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (454, 'Hallstatt', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (455, 'Hallstatt', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (307, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (456, 'La Tene', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (457, 'La Tene', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (458, 'La Tene', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (336, 'Christendom', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (102, 'Anglosphere', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (116, 'West Africa', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (117, 'West Africa', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (70, 'Archaic Greece', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (71, 'Classical Greece', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (77, 'Christianity and Islam', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (68, 'Cretan Broze Age Civilization', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (69, 'Early Iron Age Greece/Geometric Greece', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (72, 'Hellenistic Greece', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (66, 'Cretan Broze Age Civilization', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (65, 'Cretan Broze Age Civiliazation or Minoan Civilazation', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (64, 'Cretan Broze Age Civilization', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (67, 'Cretan Broze Age Civilization', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (63, 'Cretan Broze Age Civilization', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (156, 'South-East Asia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (157, 'South-East Asia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (49, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (53, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (51, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (106, 'Amorite Near East', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (113, 'Jewish diaspora', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (108, 'Israelite', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (138, 'Persian', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (138, 'Turkish', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (138, 'Islamic', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (114, 'South Asia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (115, 'South Asia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (90, 'Hinduism', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (135, 'Perso-Islamic', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (487, 'Perso-Islamic', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (482, 'Mesopotamia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (345, 'Mesopotamia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (477, 'suspected unknown', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (110, 'Persian', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (498, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (365, 'Perso-Islamic', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (175, 'Mongolian', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (502, 'Mesopotamia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (502, 'Iran', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (503, 'Mesopotamia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (503, 'Iran', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (504, 'Mesopotamia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (504, 'Iran', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (128, 'Greco-Bactrian', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (486, 'Greco-Bactrian', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (377, 'Turco-Mongol', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (377, 'Perso-Islamic', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (377, 'Shia-Islamic', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (131, 'Persian', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (133, 'Persian', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (111, 'Greek', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (367, 'Perso-Islamic', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (500, 'Amorite world', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (496, 'Sumerian', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (497, 'Sumerian', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (118, 'Scandinavia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (118, 'Norden', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (118, 'Latin Christendom', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (182, 'Appenine culture', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (183, 'Latial Culture', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (192, 'Latin Christendom', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (193, 'Christendom', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (195, 'Roman Catholicism', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (196, 'Roman Catholicism', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (194, 'Christendom', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (190, 'Roman', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (185, 'Latin States', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (187, 'Roman', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (186, 'Roman', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (73, 'Greco-Roman', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (184, 'Hellenistic Civilization', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (188, 'Roman', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (191, 'Latin Christendom', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (547, 'Christiandom', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (152, 'Japanese', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (149, 'T''ang China', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (149, 'Korea', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (154, 'Japanese', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (150, 'Tang China', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (151, 'none', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (148, 'Initial Kofun Package', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (266, 'T''ang China', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (153, 'Japanese', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (155, 'Japanese', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (147, 'Western horizon', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (292, 'Perso-Islamic', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (44, 'Indianized Southeast Asia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (43, 'Indianized Southeast Asia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (45, 'Indianized Southeast Asia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (46, 'Indianized Southeast Asia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (42, 'Indianized Southeast Asia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (40, 'Chinese cultural sphere', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (40, 'Indian cultural sphere', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (41, 'Chinese cultural sphere', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (466, 'Andronovan', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (107, 'Phoenician', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (435, 'Arabic', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (435, 'Islamic', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (430, 'Sahel Tell Culture', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (431, 'Sahel Tell Culture', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (433, 'Jenne Culture', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (434, 'Jenne Culture', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (232, 'Mande', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (245, 'Mande', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (245, 'Islamic', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (270, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (446, 'Mongols', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (289, 'Turko-Sogdian', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (441, 'proto-Mongolian Donghu', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (440, 'Early Nomadic', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (447, 'Oirats', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (227, 'Mande', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (219, 'Mande', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (531, 'Zapotec', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (13, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (12, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (14, 'Central Highland Mesoamerican Late-Terminal Formative', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (527, 'Middle Formative', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (526, 'Early Formative', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (525, 'Early Formative', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (119, 'Latin Christendom', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (81, 'Lake Titicaca cultural sphere', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (82, 'Lake Titicaca cultural sphere', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (84, 'Wari cultural sphere', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (85, 'Lake Titicaca cultural sphere', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (80, 'Lake Titicaca cultural sphere', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (83, 'Middle Horizon', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (448, 'Melanesia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (449, 'Melanesia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (122, 'not applicable', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (123, 'Indus Civilisation', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (127, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (124, 'Indus Civilisation', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (125, 'Indus Civilisation', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (197, 'Siberia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (198, 'Siberia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (524, 'Nubia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (134, 'Islam', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (47, 'Indianized Southeast Asia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (48, 'Indianized Southeast Asia', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (224, 'Islam', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (76, 'Christianity', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (78, 'Christianity', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (79, 'Christianity', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (75, 'Christianity', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (167, 'Hittite', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (171, 'Achaemenid Empire', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (172, 'Greek', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (168, 'Neo-Hittite', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (176, 'Turkic', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (176, 'Islamic', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (176, 'Persian', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (177, 'Turkish', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (177, 'Islamic', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (178, 'Turkish', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (179, 'Turkish', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (74, 'Greco-Roman', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (174, 'Islam', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (170, 'Neo-Hittite', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (35, 'Middle Mississippian', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (36, 'Middle Mississippian', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (104, 'Eastern Woodlands', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (105, 'Eastern Woodlands', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (23, 'Kingdom of Hawaii - Post-Kamehameha Period', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (25, 'Early Woodland', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (37, 'Emergent Mississippian', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (28, 'Middle Woodland', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (26, 'Middle Woodland', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (29, 'Late Woodland', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (27, 'Late Woodland', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (31, 'Middle Mississippian', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (30, 'Cahokia - Emergent Mississippian II', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (299, 'Islam', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (467, 'Burguluk culture', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (467, 'Yaz I civilization', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (290, 'Perso-Islamic', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (471, 'Sogdian', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (373, 'Turko-Islamic', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (356, 'Himyarite', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (357, 'Himyarite', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (544, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (542, 'Sabaean Culture', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (541, 'Sabaean Culture', 'TRS', 'true', 'supracultural_entity');
INSERT INTO general_polity_supracultural_entity (polity_id, supracultural_entity, tag, finalized, name) VALUES (543, 'Sabaean Culture', 'TRS', 'true', 'supracultural_entity');