INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (140, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (137, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (137, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (353, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (132, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (132, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (284, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (284, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (130, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (130, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (256, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (257, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (425, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (424, 'suspected unknown', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (474, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (473, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (248, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (248, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (269, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (272, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (428, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (261, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (1, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (2, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (246, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (263, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (264, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (267, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (427, 'nominal', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (254, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (254, 'personal union', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (254, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (247, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (247, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (271, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (438, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (439, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (199, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (199, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (200, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (370, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (513, 'suspected unknown', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (517, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (518, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (208, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (235, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (242, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (239, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (522, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (514, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (515, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (516, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (202, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (201, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (519, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (520, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (112, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (210, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (521, 'nominal', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (521, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (206, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (523, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (203, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (364, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (364, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (211, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (211, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (60, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (61, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (451, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (450, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (463, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (464, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (460, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (461, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (314, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (452, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (453, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (454, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (455, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (307, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (459, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (309, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (456, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (457, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (458, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (336, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (462, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (102, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (116, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (117, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (70, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (77, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (69, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (66, 'suspected unknown', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (67, 'suspected unknown', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (20, 'suspected unknown', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (21, 'suspected unknown', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (156, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (157, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (157, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (157, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (50, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (51, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (106, 'unknown', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (106, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (106, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (106, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (113, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (113, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (113, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (108, 'personal union', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (108, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (108, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (108, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (108, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (95, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (97, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (138, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (114, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (115, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (391, 'Nominal', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (391, 'Alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (98, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (98, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (94, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (99, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (90, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (101, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (96, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (92, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (93, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (100, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (135, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (487, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (479, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (345, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (345, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (484, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (485, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (478, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (483, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (481, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (109, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (476, 'suspected unknown', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (480, 'personal union', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (480, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (477, 'suspected unknown', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (110, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (511, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (490, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (498, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (498, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (365, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (505, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (489, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (175, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (175, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (503, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (504, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (507, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (507, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (128, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (486, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (488, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (377, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (131, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (133, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (111, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (367, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (499, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (500, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (501, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (118, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (189, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (189, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (192, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (193, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (195, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (196, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (194, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (190, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (190, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (185, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (187, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (187, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (186, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (73, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (184, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (188, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (191, 'nominal', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (547, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (152, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (149, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (154, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (150, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (151, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (148, 'uncoded', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (266, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (153, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (155, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (147, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (292, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (292, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (292, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (285, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (44, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (43, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (45, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (46, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (42, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (40, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (41, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (38, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (39, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (466, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (107, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (107, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (107, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (107, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (430, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (431, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (433, 'suspected unknown', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (434, 'suspected unknown', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (232, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (245, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (286, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (270, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (445, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (445, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (281, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (443, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (289, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (289, 'personal union', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (441, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (447, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (219, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (528, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (529, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (530, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (531, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (532, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (535, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (535, 'personal union', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (19, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (16, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (11, 'unknown', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (11, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (13, 'suspected unknown', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (12, 'unknown', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (12, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (14, 'suspected unknown', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (527, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (526, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (525, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (119, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (81, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (82, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (84, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (85, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (80, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (86, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (86, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (83, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (448, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (449, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (120, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (121, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (122, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (129, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (126, 'unknown', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (123, 'unknown', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (127, 'unknown', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (136, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (136, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (136, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (139, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (139, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (139, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (124, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (125, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (197, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (198, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (524, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (134, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (47, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (48, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (465, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (224, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (163, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (164, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (76, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (78, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (79, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (173, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (173, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (173, 'personal union', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (173, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (161, 'NO_VALUE_ON_WIKI', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (75, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (171, 'personal union', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (171, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (172, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (172, 'personal union', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (172, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (159, 'unknown', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (158, 'unknown', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (168, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (176, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (176, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (176, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (177, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (178, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (169, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (74, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (174, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (174, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (170, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (170, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (35, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (36, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (33, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (104, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (104, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (105, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (23, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (23, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (25, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (37, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (28, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (26, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (29, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (27, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (31, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (30, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (472, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (290, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (290, 'nominal', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (471, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (471, 'nominal allegiance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (373, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (356, 'vassalage', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (356, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (357, 'alliance', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (544, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (371, 'nominal', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (371, 'none', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (368, 'nominal', 'TRS', 'true', 'supra-polity_relations');
INSERT INTO general_polity_suprapolity_relations (polity_id, supra_polity_relations, tag, finalized, name) VALUES (362, 'nominal', 'TRS', 'true', 'supra-polity_relations');